/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Coalescent.Encoding
import Mathlib.MeasureTheory.Constructions.Projective
import Mathlib.Tactic

namespace Descent

/-!
# There is at most one coalescent

K-C section 4, after constructing a coalescent in Theorem 3, says: "There are of course other
ways, but the Stone-Weierstrass property shows that they all have the same finite-dimensional
distributions.  Hence it is legitimate to talk of *the* coalescent."

That claim has two halves.  EXISTENCE -- that some measure on `𝓔` has the prescribed
restrictions -- needs the Kolmogorov extension theorem, and `Descent.Coalescent.Program`
lists it as open, because Mathlib's projective-limit machinery supplies uniqueness and the
`n = ∞` existence for product and Ionescu-Tulcea constructions but not for a general
consistent family.  UNIQUENESS is the half proved here, and it is the half that licenses the
definite article.

The statement is that a probability measure on `𝓔` is determined by its finite-dimensional
distributions -- the laws of `ρ_n R` for every `n`.  The proof is Dynkin's lemma: the
cylinder sets `ρ_n⁻¹{ξ}` form a π-system, they generate the σ-algebra that makes every `ρ_n`
measurable, and two probability measures agreeing on a generating π-system agree.

`Descent.Coalescent.Infinite.eq_ofCompatible` is the same statement one level down, for
points rather than measures: a relation on `ℕ` is determined by its restrictions.  Together
they say that both the state and its law are pinned by what happens on finite samples --
which is the whole reason Kingman's finite-`n` theory determines the infinite object.

## Main results

- `cylinderSpace`: the σ-algebra generated by the restrictions -- the natural one for
  finite-dimensional distributions.
- `cylinders`: the π-system of cylinder sets.
- `isPiSystem_cylinders`: it is one.
- `eq_of_restrictInf_eq`: **a probability measure on `𝓔` is determined by its
  finite-dimensional distributions.**  K-C section 4's uniqueness.
-/

namespace Coalescent

open MeasureTheory

/-- The σ-algebra on `𝓔` generated by the restrictions: the smallest one making every `ρ_n`
measurable, and so the one in which "finite-dimensional distribution" means anything. -/
def cylinderSpace : MeasurableSpace EInf :=
  ⨆ n : ℕ, MeasurableSpace.comap (restrictInf n) ⊤

/-- A cylinder set: the relations whose restriction to `{1, …, n}` is a given state. -/
def cylinders : Set (Set EInf) :=
  {s | ∃ (n : ℕ) (ξ : ER n), s = (restrictInf n) ⁻¹' {ξ}}

/-- **The cylinders are a π-system.**  Two cylinders at levels `m ≤ n` intersect in a
cylinder at level `n` -- the one whose state restricts correctly -- or in nothing, and
`Restriction.restrict_restrict` is what makes that dichotomy exhaustive. -/
theorem isPiSystem_cylinders : IsPiSystem cylinders := by
  rintro s ⟨m, ξ, rfl⟩ t ⟨n, η, rfl⟩ hst
  obtain ⟨R, hR⟩ := hst
  rcases le_total m n with hmn | hnm
  · refine ⟨n, η, ?_⟩
    ext S
    simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_singleton_iff]
    constructor
    · rintro ⟨-, h2⟩
      exact h2
    · intro h2
      refine ⟨?_, h2⟩
      have hres : restrict hmn (restrictInf n S) = restrictInf m S :=
        restrictInf_restrict hmn S
      have hRes : restrict hmn (restrictInf n R) = restrictInf m R :=
        restrictInf_restrict hmn R
      rw [hR.1, hR.2] at hRes
      rw [← hres, h2, hRes]
  · refine ⟨m, ξ, ?_⟩
    ext S
    simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_singleton_iff]
    constructor
    · rintro ⟨h1, -⟩
      exact h1
    · intro h1
      refine ⟨h1, ?_⟩
      have hres : restrict hnm (restrictInf m S) = restrictInf n S :=
        restrictInf_restrict hnm S
      have hRes : restrict hnm (restrictInf m R) = restrictInf n R :=
        restrictInf_restrict hnm R
      rw [hR.1, hR.2] at hRes
      rw [← hres, h1, hRes]

/-- Every cylinder is measurable in `cylinderSpace`: it is a `ρ_n`-preimage, and `ρ_n` is
measurable there by construction. -/
theorem measurableSet_cylinders {s : Set EInf} (hs : s ∈ cylinders) :
    MeasurableSet[cylinderSpace] s := by
  obtain ⟨n, ξ, rfl⟩ := hs
  have hle : MeasurableSpace.comap (restrictInf n) ⊤ ≤ cylinderSpace :=
    le_iSup (fun n : ℕ => MeasurableSpace.comap (restrictInf n) ⊤) n
  exact hle _ ⟨{ξ}, trivial, rfl⟩

/-- The cylinders generate the σ-algebra: a subset of a finite `𝓔ₙ` is a finite union of
singletons, so a `ρ_n`-preimage is a finite union of cylinders. -/
theorem cylinderSpace_eq_generateFrom :
    cylinderSpace = MeasurableSpace.generateFrom cylinders := by
  refine le_antisymm ?_ ?_
  · refine iSup_le fun n => ?_
    rintro _ ⟨A, -, rfl⟩
    have hunion : (restrictInf n) ⁻¹' A = ⋃ ξ ∈ A, (restrictInf n) ⁻¹' {ξ} := by
      ext S
      simp
    rw [hunion]
    refine MeasurableSet.biUnion (Set.to_countable A) fun ξ _ => ?_
    exact MeasurableSpace.measurableSet_generateFrom ⟨n, ξ, rfl⟩
  · exact MeasurableSpace.generateFrom_le fun s hs => measurableSet_cylinders hs

/-- **K-C section 4's uniqueness: a coalescent is determined by its finite-dimensional
distributions.**

Two probability measures on `𝓔` assigning the same mass to every cylinder are equal.  This
is what licenses Kingman's definite article -- "it is legitimate to talk of THE coalescent" --
and it is Dynkin's lemma over the π-system of cylinders.

The other half, that such a measure EXISTS, is the Kolmogorov extension `Program` still
lists.  Uniqueness without existence is not vacuous: it says any two constructions agree, so
`Descent.Coalescent.Law`'s finite-`n` coupling and any future infinite construction cannot
disagree about anything a finite sample can see. -/
theorem eq_of_restrictInf_eq (μ ν : @MeasureTheory.Measure EInf cylinderSpace)
    (hμ : @MeasureTheory.IsProbabilityMeasure _ cylinderSpace μ)
    (hν : @MeasureTheory.IsProbabilityMeasure _ cylinderSpace ν)
    (h : ∀ (n : ℕ) (ξ : ER n),
      μ ((restrictInf n) ⁻¹' {ξ}) = ν ((restrictInf n) ⁻¹' {ξ})) :
    μ = ν := by
  refine MeasureTheory.ext_of_generate_finite cylinders cylinderSpace_eq_generateFrom
    isPiSystem_cylinders ?_ ?_
  · rintro s ⟨n, ξ, rfl⟩
    exact h n ξ
  · rw [hμ.measure_univ, hν.measure_univ]

end Coalescent

end Descent
