/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Data.Setoid.Basic
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Tactic
import Descent.Layer

assert_below Descent.Coalescent Descent.PopGen Descent.Spectral Descent.Blindness
assert_below Descent.Conditionals Descent.Portability Descent.Decision Descent.Program

/-!
# What a pangenome graph IS: a quotient of positions, and the choice hidden in "generated"

`Descent.Pangenome.GaugeCounterexample` and `Descent.Pangenome.GaugeInvariance` take a
pangenome graph as given and ask which functionals survive a change of reference tree.  This
file is one level below them.  It asks what the graph is a graph OF, and finds a second
indeterminacy that the gauge results cannot see, because it acts on the base rather than on
the fibers.

## The object

Take the disjoint union of the haplotypes as a set of positions -- here a type `Pos` together
with `hap : Pos → Hap` recording which haplotype a position came from, which is the same data
as a `Σ`-type and easier to quotient.  An aligner reports a relation `A` on `Pos`: it is
reflexive and symmetric, and it is NOT transitive, because a pairwise aligner asserts nothing
about a pair it never compared.

A graph node is a class of positions.  So a construction is an equivalence relation on `Pos`,
and the one an aligner hands you is not one.  Something has to bridge that gap, and what
bridges it is a choice.

## The choice, and why it is not a gauge

`closure A` is the equivalence relation generated by `A`.  This is what seqwish computes, and
seqwish's own documentation states the consequence: closures imply pairwise relationships
between sequences that are absent from the input alignments.  `closure_forces_unasserted_pair`
is that sentence as a theorem -- three positions, two reported alignments, and a homology
statement in the output that no aligner asserted.

Transitivity is the cocycle condition for gluing local alignments into a global object.  It
fails.  Closure repairs it by fiat, from below: `honors_iff_closure_le` is the Galois
connection saying `closure A` is the LEAST equivalence relation that believes every alignment,
so every construction that believes the aligner sits at or above it, and every construction
that discards alignments -- reference-anchored pruning -- sits below.  `prune_le_closure` is
that second half.  The constructions are therefore ordered by refinement rather than being a
set of alternatives, and `closure A` is the top of the family generated by any sub-alignment
set.

This is NOT a gauge freedom.  A gauge acts on fibers and changes nothing about the object, so
the remedy is a hard invariance constraint.  A construction choice changes WHICH object you
have, so no invariance constraint can be the remedy; the remedy is a bracket, and the two
indeterminacies must not be conflated.

## What survives, and in which direction it moves

Mass survives.  `mass_conserved` says the total number of positions is the sum of the class
sizes under any construction whatever -- coarsening relocates mass in the subset lattice but
creates and destroys none.

Support does not survive, and it moves MONOTONICALLY.  `support hap r x` is the set of
haplotypes represented in the class of `x`, which is what a node frequency spectrum counts,
and `support_mono` says coarsening can only grow it.  So the direction of the confound is
known and not merely present: **a coarser construction reports a node frequency spectrum
shifted toward higher frequency.**  Closure inflates apparent core; pruning inflates apparent
private sequence.  A core/accessory number computed under one construction is one endpoint of
an interval, and `freq_mono` is the statement that the interval is oriented.

## The other thing "generated" does

`CollapseFree` names the case where the generated relation identifies no two positions OF THE
SAME HAPLOTYPE.  When it fails, a haplotype's positions do not inject into the nodes, so a
haplotype traverses a node more than once -- which is why `Descent.Pangenome.GaugeInvariance`
records a walk as `Walk E := E → Nat` and not as a set of edges.  The multiplicity in that
definition is exactly the failure of `CollapseFree`, and `collapseFree_iff_quotient_inj` says
so: collapse-freedom IS injectivity of the quotient map within a haplotype.

That failure is not an artifact.  It is where the repeats are -- the tandem arrays, the
segmental duplications, the transposable elements -- so it is where copy number lives, and it
is a statement about the same objects Ohta's multigene-family theory is about.

## Empirical status

None.  The bodies here are definitions and lemmas about equivalence relations on a finite
type.  Which relation a given aligner reports on a given panel, and how wide the resulting
bracket is on real data, are empirical questions and are not settled here.

## Main results

- `closure_forces_unasserted_pair`: **the forcing witness.**  An explicit `A` and a pair the
  closure relates that `A` does not.  Transitivity is not free.
- `honors_iff_closure_le`: closure is the least construction believing every alignment.
- `prune_le_closure`: discarding alignments only refines, so closure is the top.
- `mass_conserved`: total position count is construction-independent.
- `support_mono`, `freq_mono`: **the oriented confound.**  Coarsening only grows a node's
  haplotype support, so the frequency spectrum moves one way.
- `collapseFree_iff_quotient_inj`: within-haplotype collapse is exactly non-injectivity of
  the quotient map, which is what forces traversal multiplicities.
-/

namespace Descent.Pangenome.Construction

open Relation

/-! ### Constructions -/

/-- **A construction**: the equivalence relation on positions generated by an alignment
relation.  This is the free repair of the failed cocycle -- seqwish's transitive closure.

Empirical status: NOT AN EMPIRICAL CLAIM.  It names the least equivalence relation containing
`A`; whether a builder computes it, and whether the classes it produces are homologous in
fact, are the empirical questions and are not settled here. -/
def closure {Pos : Type*} (A : Pos → Pos → Prop) : Setoid Pos := EqvGen.setoid A

/-- The closure relates exactly what the equivalence closure of `A` relates.  Definitional,
and stated so that consumers can rewrite rather than re-derive. -/
theorem closure_rel_iff {Pos : Type*} (A : Pos → Pos → Prop) (x y : Pos) :
    (closure A) x y ↔ EqvGen A x y := Iff.rfl

/-- **A construction believes an aligner** if every reported alignment is an identification
it makes.  This is the only constraint the data places on a builder.

Empirical status: NOT AN EMPIRICAL CLAIM.  It is a relation between a reported relation and a
chosen equivalence relation; which builders satisfy it is not settled here. -/
def Honors {Pos : Type*} (A : Pos → Pos → Prop) (r : Setoid Pos) : Prop :=
  ∀ x y, A x y → r x y

/-- The closure believes the aligner.  This is the witness that `Honors` is inhabited, so the
constraint is not vacuous. -/
theorem closure_honors {Pos : Type*} (A : Pos → Pos → Prop) : Honors A (closure A) :=
  fun _ _ h => EqvGen.rel _ _ h

/-- **The Galois connection, and the reason closure is the free construction.**

A construction believes every reported alignment exactly when it sits at or above the
closure.  Both directions are content: forward, closure is the LEAST such construction, so
nothing that believes the aligner is finer than it; backward, anything above it believes the
aligner, so the whole up-set is admissible on the data alone.  The data therefore does not
determine the object -- it determines a lower bound. -/
theorem honors_iff_closure_le {Pos : Type*} (A : Pos → Pos → Prop) (r : Setoid Pos) :
    Honors A r ↔ closure A ≤ r :=
  ⟨fun h => Setoid.eqvGen_le h, fun h _ _ hxy => h (EqvGen.rel _ _ hxy)⟩

/-- **Pruning only refines.**  A builder that discards alignments -- restricting to what is
coherent with a chosen reference backbone -- produces a construction at or below the closure
of the full alignment set.  With `honors_iff_closure_le` this is the bracket: every
construction of either kind is comparable to `closure A`, from one side or the other. -/
theorem prune_le_closure {Pos : Type*} {A B : Pos → Pos → Prop} (h : ∀ x y, A x y → B x y) :
    closure A ≤ closure B :=
  Setoid.eqvGen_mono h

/-! ### The forcing witness -/

/-- Three positions, and the two alignments a pairwise aligner reports on them: `0` with `1`,
and `1` with `2`.  It says nothing about `0` and `2`, which is the ordinary situation -- those
two were never compared.

Empirical status: NOT AN EMPIRICAL CLAIM.  It is an explicit finite relation exhibited to
witness that the closure adds pairs; it models no particular alignment. -/
def forcingRel : Fin 3 → Fin 3 → Prop := fun p q =>
  p = q ∨ (p = 0 ∧ q = 1) ∨ (p = 1 ∧ q = 0) ∨ (p = 1 ∧ q = 2) ∨ (p = 2 ∧ q = 1)

instance : DecidableRel forcingRel := fun p q => by unfold forcingRel; infer_instance

/-- The witness relation is reflexive, as a reported alignment is. -/
theorem forcingRel_refl : ∀ p : Fin 3, forcingRel p p := by decide

/-- The witness relation is symmetric, as a reported alignment is. -/
theorem forcingRel_symm : ∀ p q : Fin 3, forcingRel p q → forcingRel q p := by decide

/-- **The closure manufactures a homology statement no aligner asserted.**

`forcingRel` does not relate position `0` to position `2` -- no alignment between them was
reported.  Its closure does.  So the transitive closure is not a neutral bookkeeping step
that tidies the aligner's output: it adds assertions of the same kind the aligner makes, and
those assertions are the construction's, not the data's.

This is the failure of the cocycle condition made explicit.  Transitivity is what would let
local alignments glue into a global object; it does not hold, and closure repairs it by
fiat.  Every downstream node, and hence every node-level statistic, carries the repair. -/
theorem closure_forces_unasserted_pair :
    ¬ forcingRel 0 2 ∧ EqvGen forcingRel 0 2 :=
  ⟨by decide,
    EqvGen.trans 0 1 2 (EqvGen.rel 0 1 (by decide)) (EqvGen.rel 1 2 (by decide))⟩

/-! ### Mass -/

/-- **Total mass is construction-independent.**  Every position lies in exactly one class
under any construction whatever, so the class sizes sum to the number of positions.
Coarsening relocates mass in the subset lattice and creates none.

This is the one conserved quantity, and it is why the confound below is a redistribution
rather than a gain or a loss. -/
theorem mass_conserved {Pos : Type*} [Fintype Pos] (r : Setoid Pos) [Fintype (Quotient r)]
    [DecidableEq (Quotient r)] :
    (∑ c : Quotient r, (Finset.univ.filter fun p : Pos => Quotient.mk r p = c).card)
      = Fintype.card Pos := by
  have h := Finset.card_eq_sum_card_fiberwise
    (s := (Finset.univ : Finset Pos)) (t := (Finset.univ : Finset (Quotient r)))
    (f := fun p : Pos => Quotient.mk r p) (fun x _ => Finset.mem_univ _)
  simpa using h.symm

/-! ### Support, and the direction the spectrum moves -/

/-- **The haplotype support of a node**: which haplotypes are represented in the class of `x`.
A node frequency spectrum is the distribution of the size of this set, so it is the quantity
a core/accessory split is computed from.

Empirical status: NOT AN EMPIRICAL CLAIM.  It names the image of a class under `hap`; what
the spectrum of a real pangenome looks like is not settled here. -/
def support {Pos Hap : Type*} (hap : Pos → Hap) (r : Setoid Pos) (x : Pos) : Set Hap :=
  {h | ∃ y, r x y ∧ hap y = h}

/-- A position is in its own node's support, so a support is never empty.  The witness that
`support` is not vacuous. -/
theorem hap_mem_support {Pos Hap : Type*} (hap : Pos → Hap) (r : Setoid Pos) (x : Pos) :
    hap x ∈ support hap r x :=
  ⟨x, r.iseqv.refl x, rfl⟩

/-- Support is a property of the node and not of the representative that names it. -/
theorem support_congr {Pos Hap : Type*} (hap : Pos → Hap) (r : Setoid Pos) {x y : Pos}
    (hxy : r x y) : support hap r x = support hap r y := by
  ext h
  constructor
  · rintro ⟨z, hz, rfl⟩
    exact ⟨z, r.iseqv.trans (r.iseqv.symm hxy) hz, rfl⟩
  · rintro ⟨z, hz, rfl⟩
    exact ⟨z, r.iseqv.trans hxy hz, rfl⟩

/-- **The confound is oriented.**  If `s` is coarser than `r` then every node's haplotype
support under `s` contains its support under `r`.  Merging classes takes the union of their
supports and can never shrink one.

This is the load-bearing statement of the file.  Construction coarseness does not perturb the
node frequency spectrum in an unknown direction -- it pushes it monotonically toward higher
frequency.  A closure-maximal build therefore over-reports core and a restriction-minimal
build over-reports private sequence, and the two are the endpoints of an interval rather than
competing estimates whose disagreement is noise. -/
theorem support_mono {Pos Hap : Type*} (hap : Pos → Hap) {r s : Setoid Pos} (h : r ≤ s)
    (x : Pos) : support hap r x ⊆ support hap s x := by
  rintro _ ⟨y, hy, rfl⟩
  exact ⟨y, h hy, rfl⟩

/-- **The frequency itself is monotone**, which is `support_mono` in the form a spectrum is
reported in: a node's frequency under a coarser construction is at least its frequency under
a finer one. -/
theorem freq_mono {Pos Hap : Type*} [Finite Hap] (hap : Pos → Hap) {r s : Setoid Pos}
    (h : r ≤ s) (x : Pos) : (support hap r x).ncard ≤ (support hap s x).ncard :=
  Set.ncard_le_ncard (support_mono hap h x) (Set.toFinite _)

/-! ### Collapse within a haplotype -/

/-- **A construction is collapse-free** when it identifies no two distinct positions of the
same haplotype.  Its failure is a repeat: the same haplotype visiting one node twice.

Empirical status: NOT AN EMPIRICAL CLAIM.  It names a property of an equivalence relation;
whether the closure of a real alignment set has it is exactly the empirical question about
repeat content, and is not settled here. -/
def CollapseFree {Pos Hap : Type*} (hap : Pos → Hap) (r : Setoid Pos) : Prop :=
  ∀ x y, r x y → hap x = hap y → x = y

/-- The finest construction collapses nothing, so `CollapseFree` is inhabited and the
definition is not vacuous. -/
theorem collapseFree_bot {Pos Hap : Type*} (hap : Pos → Hap) :
    CollapseFree hap (⊥ : Setoid Pos) :=
  fun _ _ h _ => h

/-- **Collapse-freedom is injectivity of the quotient map within a haplotype.**

Both readings are the same proposition, and stating the equivalence is what makes the
definition usable: it says a haplotype's positions inject into the nodes exactly when nothing
of that haplotype was merged with itself.  When it fails the injection fails, so a haplotype
is a walk that repeats nodes rather than a simple path -- which is why a traversal is
recorded with a multiplicity in `Descent.Pangenome.GaugeInvariance` and not with a Boolean. -/
theorem collapseFree_iff_quotient_inj {Pos Hap : Type*} (hap : Pos → Hap) (r : Setoid Pos) :
    CollapseFree hap r ↔
      ∀ x y : Pos, hap x = hap y → Quotient.mk r x = Quotient.mk r y → x = y :=
  ⟨fun hcf x y hh hq => hcf x y (Quotient.exact hq) hh,
    fun hinj x y hr hh => hinj x y hh (Quotient.sound hr)⟩

/-- **Collapse is created by the closure and not reported by the aligner.**  A construction
below a collapse-free one is collapse-free, so collapse can only appear as the construction
coarsens.  Together with `closure_forces_unasserted_pair` this places the repeats the graph
shows on the side of the builder: the closure both adds pairs and, in adding them, is the
only thing that can make a haplotype meet itself. -/
theorem collapseFree_mono {Pos Hap : Type*} (hap : Pos → Hap) {r s : Setoid Pos} (h : r ≤ s)
    (hs : CollapseFree hap s) : CollapseFree hap r :=
  fun x y hxy hh => hs x y (h hxy) hh

end Descent.Pangenome.Construction
