/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Pangenome.GaugeCounterexample
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Tactic

assert_below Descent.PopGen Descent.Spectral Descent.Blindness Descent.Conditionals
assert_below Descent.Portability Descent.Decision Descent.Program

/-!
# Which statistics a construction cannot move, and why `π` is one of them

`Descent.Pangenome.GaugeCounterexample` exhibits two spanning trees of one graph over one
dataset for which `S` differs and `π` does not, and
`Descent.Pangenome.CoalescentGauge` computes the exact defect.  That is a counterexample: it
shows `θ_W` moves.  It does not say WHICH statistics can move, and a reader who wanted to
know whether their own statistic was safe would have to run the counterexample against it.

This file replaces the counterexample by a criterion.

**A statistic is construction-invariant exactly when it factors through the sample's
distance matrix.**  Everything that factors is invariant under every relabelling of the
sample and under every change of construction that leaves the distances alone; anything that
differs on two constructions with equal distances provably does not factor, and no argument
about that particular statistic is needed.

## The frame

This is the finite, elementary shadow of the Gromov-weak topology on metric measure spaces
(Greven–Pfaffelhuber–Winter).  There a genealogy is a marked metric measure space `(X, r, μ)`
taken up to measure-preserving isometry, and the topology is generated by the POLYNOMIALS --
the laws of the finite distance matrices `(r(xᵢ,xⱼ))_{i,j≤k}` under `μ^{⊗k}`.  The point of
that construction is that the object carries no labelling, no leaf order and no embedding, so
it is invariant under exactly the choices a CONSTRUCTION makes.

`polynomial` below is that generating family at a uniform measure on a finite sample, and
`polynomial_relabel` is the invariance.  Nothing here needs the topology: the separating
content is already visible at the level of one sample, and the corpus's gauge results are
statements about one sample.

## What the criterion decides

* `S_not_factorsThroughDistance`: **Watterson's `S` is not a function of the data.**  The
  sequence distances do not mention a reference tree -- `seqDist` takes two haplotypes and
  nothing else -- so the two trees of `GaugeCounterexample` give literally equal distance
  matrices, while `S` differs (`1` against `2`).  By the criterion `S` cannot factor, and
  this is a proof rather than an observation about those two particular trees.
* `piSeq_factorsThroughDistance`: `π` does factor.  Trivially, and the triviality is the
  content: `piSeq6` never takes a reference tree, so it is already a function of the walks.

## Why this is the useful form

A builder asking "will my statistic move if I rebuild the graph?" now has a test that does
not require rebuilding it: write the statistic as a function of the pairwise distances, or
exhibit two constructions with equal distances on which it differs.  `polynomial` supplies
the positive side wholesale -- every degree-`k` polynomial of the distances factors by
construction (`factorsThroughDistance_polynomial`), so the whole Gromov-weak family is safe
at once, and `π` is its degree-two member.

## Main results

- `polynomial`: the degree-`k` polynomial statistics of a finite sample's distance.
- `polynomial_relabel`: **they are invariant under relabelling the sample.**
- `FactorsThroughDistance`, `factorsThroughDistance_polynomial`: the criterion and the
  family that satisfies it.
- `eq_of_factorsThrough`: what factoring buys -- equal distances force equal values.
- `not_factorsThroughDistance`: **the criterion's cutting edge.**
- `S_not_factorsThroughDistance`, `piSeq_factorsThroughDistance`: the corpus's own gauge
  witness, decided.
-/

namespace Descent.Pangenome.GromovWeak

open Finset

universe u

/-! ### The polynomials of a finite sample -/

/-- **The degree-`k` polynomial of a sample's distance with test function `f`**: draw `k`
sample members uniformly and independently, form their distance matrix, and average `f` of
it.  This is the generating family for the Gromov-weak topology, at a uniform measure on a
finite sample.

Empirical status: NOT AN EMPIRICAL CLAIM.  It is an average over a finite index type; what
carries empirical weight is the reading of `r` as a genealogical or sequence distance, and
that reading is supplied by whoever instantiates it. -/
noncomputable def polynomial {ι : Type u} [Fintype ι] (k : ℕ) (r : ι → ι → ℝ)
    (f : (Fin k → Fin k → ℝ) → ℝ) : ℝ :=
  ((Fintype.card ι : ℝ) ^ k)⁻¹ * ∑ x : Fin k → ι, f (fun i j ↦ r (x i) (x j))

/-- **Polynomials do not see a labelling.**  Relabelling the sample by any bijection leaves
every polynomial unchanged, because the sum runs over all `k`-tuples and the relabelling only
permutes them.

This is the finite form of "taken up to measure-preserving isometry", and it is the reason
the Gromov-weak family is the right one to call construction-invariant: a construction that
renames the haplotypes has changed nothing a polynomial can report. -/
theorem polynomial_relabel {ι : Type u} [Fintype ι] (k : ℕ) (r : ι → ι → ℝ)
    (f : (Fin k → Fin k → ℝ) → ℝ) (e : ι ≃ ι) :
    polynomial k (fun a b ↦ r (e a) (e b)) f = polynomial k r f := by
  unfold polynomial
  congr 1
  exact Fintype.sum_equiv (Equiv.piCongrRight fun _ : Fin k ↦ e) _ _ fun _ ↦ rfl

/-- **Pairwise diversity is the degree-two polynomial.**  `π` is what you get by drawing two
sample members and averaging their distance, which is the smallest nonconstant member of the
family.  That it sits inside the invariant family is the structural reason it survives the
reference-tree gauge, where `S` does not. -/
noncomputable def pairwiseDiversity {ι : Type u} [Fintype ι] (r : ι → ι → ℝ) : ℝ :=
  polynomial 2 r fun d ↦ d 0 1

theorem pairwiseDiversity_relabel {ι : Type u} [Fintype ι] (r : ι → ι → ℝ)
    (e : ι ≃ ι) :
    pairwiseDiversity (fun a b ↦ r (e a) (e b)) = pairwiseDiversity r :=
  polynomial_relabel 2 r _ e

/-! ### The criterion

A construction is anything a builder chooses -- a reference tree, a graph, a phasing.  The
data it is chosen over supply a distance.  The question is whether a statistic computed from
the construction is really a statistic of the data. -/

/-- **A statistic factors through the sample's distance.**  `dist x` is the distance matrix
that construction `x` presents and `stat x` the number reported from it; factoring says the
number was a function of the matrix all along.

Empirical status: NOT AN EMPIRICAL CLAIM.  It is a property of a pair of functions, decided
by `factorsThroughDistance_polynomial` on one side and `not_factorsThroughDistance` on the
other. -/
def FactorsThroughDistance {ι : Type u} {X : Type*} (dist : X → ι → ι → ℝ)
    (stat : X → ℝ) : Prop :=
  ∃ Φ : (ι → ι → ℝ) → ℝ, ∀ x, stat x = Φ (dist x)

/-- **The whole Gromov-weak family satisfies the criterion, wholesale.**  Every degree-`k`
polynomial of the presented distance factors through it, by construction and for every `k`
and every test function at once.

This is the witness that keeps `FactorsThroughDistance` from being an axiom with a friendly
name, and it is not a formality: it says the criterion admits a large, named, usable family
rather than being satisfiable only by constants. -/
theorem factorsThroughDistance_polynomial {ι : Type u} [Fintype ι] {X : Type*}
    (dist : X → ι → ι → ℝ) (k : ℕ) (f : (Fin k → Fin k → ℝ) → ℝ) :
    FactorsThroughDistance dist fun x ↦ polynomial k (dist x) f :=
  ⟨fun r ↦ polynomial k r f, fun _ ↦ rfl⟩

/-- What factoring buys: two constructions presenting the same distances report the same
number.  This is the guarantee a builder wants, and it is available for any statistic that
passes the criterion without knowing anything else about it.

Assumes: `FactorsThroughDistance dist stat`. -/
theorem eq_of_factorsThrough {ι : Type u} {X : Type*} {dist : X → ι → ι → ℝ}
    {stat : X → ℝ} (h : FactorsThroughDistance dist stat) {x y : X}
    (hd : dist x = dist y) : stat x = stat y := by
  obtain ⟨Φ, hΦ⟩ := h
  rw [hΦ x, hΦ y, hd]

/-- **The criterion's cutting edge.**  A statistic that differs on two constructions
presenting equal distances does not factor through the distance -- so it is not a statistic
of the data, whatever else it is.

One pair of constructions refutes it, permanently and for all readers.  That is the
improvement over a counterexample: the counterexample says this statistic moved between these
two trees, and this says the statistic is not a function of the data at all. -/
theorem not_factorsThroughDistance {ι : Type u} {X : Type*} {dist : X → ι → ι → ℝ}
    {stat : X → ℝ} {x y : X} (hd : dist x = dist y) (hs : stat x ≠ stat y) :
    ¬ FactorsThroughDistance dist stat :=
  fun h ↦ hs (eq_of_factorsThrough h hd)

/-! ### The corpus's own gauge witness, decided

`Descent.Pangenome.GaugeCounterexample` supplies two spanning trees of one graph and one
sample.  The distance those haplotypes carry is `seqDist`, which takes two haplotypes and
nothing else -- so as a function of the reference tree it is CONSTANT, and the two trees
present literally equal distance matrices.  Everything below is that observation run through
the criterion. -/

/-- The distances a pangenome sample carries, presented as a function of the reference tree.
It ignores its argument, which is the whole point: sequence distance is a property of the
walks, and the tree is a choice made after the walks exist. -/
noncomputable def treeDistance (_t : RefTree) (a b : Hap) : ℝ := (seqDist a b : ℝ)

/-- Two reference trees present the same distances -- definitionally, since `treeDistance`
discards the tree. -/
theorem treeDistance_const (t₁ t₂ : RefTree) : treeDistance t₁ = treeDistance t₂ := rfl

/-- **Watterson's `S` is not a function of the data.**  Under the two spanning trees of
`GaugeCounterexample` the sample presents equal distances and `S` reports `1` against `2`, so
by `not_factorsThroughDistance` no function of the distance matrix computes it.

This is the promotion of `subsample_S_not_invariant` from a counterexample to a
classification: the failure is not about those two trees, it is that `S` is not that kind of
statistic. -/
theorem S_not_factorsThroughDistance :
    ¬ FactorsThroughDistance treeDistance fun t ↦ (S t subsample : ℝ) := by
  refine not_factorsThroughDistance (x := Allele.A) (y := Allele.G) rfl ?_
  have h := subsample_S_not_invariant
  rw [h.1, h.2]
  norm_num

/-- **And sequence-level `π` is.**  `piSeq6` never takes a reference tree, so it factors
through anything at all -- in particular through the distance.

The triviality is the content, and it is the same content as
`GaugeCounterexample.subsample_piSeq_value`'s docstring records: the estimator that survives
a change of construction is the one whose definition never mentions the construction. What
the criterion adds is that this is sufficient as well as necessary, and that the same
guarantee extends to every polynomial of the distances rather than to `π` alone. -/
theorem piSeq_factorsThroughDistance :
    FactorsThroughDistance treeDistance fun _ : RefTree ↦ (piSeq6 subsample : ℝ) :=
  ⟨fun _ ↦ (piSeq6 subsample : ℝ), fun _ ↦ rfl⟩

end Descent.Pangenome.GromovWeak
