#!/usr/bin/env python3
"""Shared machinery: ancestral-configuration enumeration, symmetry lumping, and the
verification that makes lumping a proof rather than an assumption.

WHY THIS MODULE EXISTS.  Two derivations in this program solve stationary systems on
ancestral-configuration state spaces and both need the same three things: enumerate
the configurations, quotient them by the demography's symmetry group, and CHECK that
the quotient is legitimate.  The third is the point.  A symmetry reduction that is
merely asserted turns a 56-state proof into a 9-state guess; the reduction is only
sound if every member of an orbit gives the identical lumped row, and that is a
finite check which this module performs rather than trusts.

WHO CONSUMES WHAT, and the boundary between them.  The state spaces differ by the
number of ancestral units being tracked; everything downstream of that is shared:

  * ONE LOCUS (two units) -- `pair_states` / `pair_rows`.  The structured pair
    coalescent: a state is an unordered pair of deme labels.  This is the object the
    gap-7 route needs (Notohara's structured coalescent, exact under migration).
  * TWO LOCI (four units) -- `SHAPES` / `TwoLocusSpace`.  A state is a partition of
    {a1,a2,b1,b2} into lineages, each carrying a deme label, restricted to the phase
    in which neither locus has coalesced.  Seven partitions, times deme labels.

`orbits`, `lump`, `verify_lumpable`, `verify_source_orbit_constant`,
`verify_residual` and `solve_exact` are shared by both and know nothing about
either.

WHICH PARTS EACH DERIVATION EXERCISED, as the shared-machinery ruling requires:
  * the two-deme equilibrium closed form (derivation/ld2evidence.py) exercised
    `SHAPES`, `TwoLocusSpace`, `orbits` under the group generated by a1<->a2,
    b1<->b2, locus A<->B and deme0<->deme1, `verify_source_orbit_constant`,
    `verify_lumpable` on all 56 states, and `verify_residual` on the full system;
  * the stepping-stone extension (derivation/ldchain.py, and the dependency-free
    `ldchain_reduction.py` beside this file) exercised the same with the deme swap
    replaced by chain reflection, at n = 2, 3, 4 (56, 207, 544 states);
  * the post-split transient (derivation/ldtransient.py) exercised the same lumping
    and then took a matrix exponential of the LUMPED generator, which is only valid
    BECAUSE the lumping was verified;
  * `pair_states` / `pair_rows` are used here and by the pairwise-F tables; the
    one-locus consumer is expected to be the gap-7 build.

NO CLOSURE IS TAKEN ANYWHERE HERE, and the reason is structural rather than a
tolerance: four ancestral units admit finitely many partitions and the set is closed
under migration, coalescence and recombination, so the generator maps the span of
these states into itself.  There is no larger system any of this approximates.  (That
is a statement about THIS object, and says nothing about any other package's
implementation.)

ARITHMETIC-AGNOSTIC BY CONSTRUCTION.  A generator is a list of dicts: `Q[i][j]` is the
rate from state i to state j, and rates may be `Fraction`, `float`, or sympy
expressions -- nothing here does anything to a rate but add and multiply it.  Use
`Fraction` when the answer is meant to be exact; `solve_exact` is then an exact
rational solve and `verify_residual` is an exact zero rather than a tolerance.

This module is standard library only.  `argcore.py` beside it is the original
numpy/scipy implementation of the same two-locus space, kept as authored; the self
test below CHECKS THE TWO ENUMERATIONS AGREE when numpy is importable, so the
duplication cannot drift silently.

    python3 lumping.py        # runs the self test
"""

from __future__ import annotations

import itertools
from fractions import Fraction

# --------------------------------------------------------------------------- #
# two-locus ancestral configurations
# --------------------------------------------------------------------------- #


def _canon(part):
    """Canonical form of a set partition written as a label word."""
    m, out = {}, []
    for x in part:
        if x not in m:
            m[x] = len(m)
        out.append(m[x])
    return tuple(out)


#: unit indices 0,1 are locus A (a1,a2); 2,3 are locus B (b1,b2)
AU, BU = (0, 1), (2, 3)

#: the seven partitions of {a1,a2,b1,b2} in which neither locus has coalesced
SHAPES = [p for p in itertools.product(range(4), repeat=4)
          if _canon(p) == p and p[0] != p[1] and p[2] != p[3]]
SHAPE_IX = {s: i for i, s in enumerate(SHAPES)}
NBLK = [max(s) + 1 for s in SHAPES]
assert len(SHAPES) == 7, SHAPES


class TwoLocusSpace:
    """Two-locus ancestral configurations over `n` demes.

    A state is a shape (which units share a lineage) plus a deme label per lineage.
    `mk` returns `None` for a configuration in which a locus has coalesced -- those
    are absorbing for the second-moment problem and are dropped rather than tracked.
    """

    def __init__(self, n: int):
        self.n = n
        self.keys = [(si, dm) for si in range(len(SHAPES))
                     for dm in itertools.product(range(n), repeat=NBLK[si])]
        self.ix = {k: i for i, k in enumerate(self.keys)}
        self.ns = len(self.keys)
        self.udeme = [[dm[SHAPES[si][u]] for u in range(4)] for si, dm in self.keys]

    def mk(self, part_raw, dmu):
        cp = _canon(part_raw)
        if cp[0] == cp[1] or cp[2] == cp[3]:
            return None
        dm = [0] * NBLK[SHAPE_IX[cp]]
        for u in range(4):
            dm[cp[u]] = dmu[u]
        return self.ix[(SHAPE_IX[cp], tuple(dm))]

    def state(self, blocks):
        """Index of the state described by `[(units, deme), ...]`."""
        pr, dmu = [-1] * 4, [-1] * 4
        for bi, (units, d) in enumerate(blocks):
            for u in units:
                pr[u], dmu[u] = bi, d
        return self.mk(pr, dmu)

    def permute(self, i, unit_perm, relabel=None):
        """Image of state `i` under a permutation of the four units and an optional
        relabelling of demes (`relabel(d) -> d'`, e.g. a deme swap or a reflection)."""
        sh, dmu = SHAPES[self.keys[i][0]], self.udeme[i]
        inv = [0] * 4
        for u in range(4):
            inv[unit_perm[u]] = u
        nd = [dmu[inv[u]] for u in range(4)]
        if relabel is not None:
            nd = [relabel(d) for d in nd]
        return self.mk([sh[inv[u]] for u in range(4)], nd)


# --------------------------------------------------------------------------- #
# one-locus (structured pair coalescent) state space
# --------------------------------------------------------------------------- #


def pair_states(n: int):
    """Unordered deme pairs, and the index map `key(a, b)`."""
    idx = {}
    for i in range(n):
        for j in range(i, n):
            idx[(i, j)] = len(idx)
    return idx, (lambda a, b: idx[(min(a, b), max(a, b))])


def pair_rows(n, neighbours, mu, coal=1):
    """Generator rows for two lineages under migration and coalescence.

    `neighbours[i]` lists the demes reachable from `i`; a lineage hops to each at
    rate `mu`; two lineages in one deme coalesce at rate `coal`, which LEAKS (the
    pair is absorbed) rather than moving to another tracked state.
    """
    idx, key = pair_states(n)
    Q = [dict() for _ in idx]

    def add(r, c, v):
        Q[r][c] = Q[r].get(c, 0) + v

    for (i, j), r in idx.items():
        for (a, o) in ((i, j), (j, i)):
            for w in neighbours[a]:
                add(r, key(w, o), mu)
                add(r, r, -mu)
        if i == j:
            add(r, r, -coal)
    return [{c: v for c, v in row.items() if v != 0} for row in Q], idx, key


# --------------------------------------------------------------------------- #
# symmetry lumping -- and the checks that make it a proof
# --------------------------------------------------------------------------- #


def orbits(ns: int, maps):
    """Orbits of the group generated by `maps` (each a callable `i -> j`).

    Returns `(orbit_of, orbit_members)`.
    """
    orbit_of = [-1] * ns
    members = []
    for i in range(ns):
        if orbit_of[i] >= 0:
            continue
        o, stack, mem = len(members), [i], set()
        while stack:
            x = stack.pop()
            if x in mem:
                continue
            mem.add(x)
            orbit_of[x] = o
            for g in maps:
                stack.append(g(x))
        members.append(sorted(mem))
    return orbit_of, members


def verify_source_orbit_constant(src, orbit_members):
    """The inhomogeneous term must be constant on each orbit, or lumping is invalid."""
    for o, mem in enumerate(orbit_members):
        vals = {src[j] for j in mem}
        if len(vals) != 1:
            raise AssertionError(
                f"source is not constant on orbit {o}: {sorted(map(str, vals))}")


def verify_lumpable(Q, orbit_members):
    """EVERY member of an orbit must give the identical lumped row.

    This is the check that turns a symmetry reduction into a proof. It is deliberately
    exhaustive over states rather than sampled: the cost is one pass and the thing it
    rules out -- a quotient that is not a quotient -- is silent when it happens.
    """
    for a, mem in enumerate(orbit_members):
        ref = None
        for i in mem:
            row = tuple(sum(Q[i].get(j, 0) for j in tgt) for tgt in orbit_members)
            if ref is None:
                ref = row
            elif row != ref:
                raise AssertionError(
                    f"not lumpable: orbit {a} members disagree (state {i})")


def lump(Q, src, orbit_members, check=True):
    """Reduce `(Q, src)` to one equation per orbit. Verifies first unless told not to."""
    if check:
        verify_source_orbit_constant(src, orbit_members)
        verify_lumpable(Q, orbit_members)
    reps = [mem[0] for mem in orbit_members]
    Qr = [[sum(Q[i].get(j, 0) for j in tgt) for tgt in orbit_members] for i in reps]
    return Qr, [src[i] for i in reps], reps


def verify_residual(Q, src, P, zero=0):
    """Substitute a full-space solution back into `0 = src + Q P` on every equation."""
    for i in range(len(src)):
        r = sum(v * P[j] for j, v in Q[i].items()) + src[i]
        if r != zero:
            raise AssertionError(f"residual nonzero at state {i}: {r}")


def solve_exact(A, b):
    """Gauss-Jordan with partial pivoting. Exact when the entries are `Fraction`."""
    n = len(b)
    M = [list(row) + [b[i]] for i, row in enumerate(A)]
    for c in range(n):
        p = next((r for r in range(c, n) if M[r][c] != 0), None)
        if p is None:
            raise ValueError(f"singular system at column {c}")
        M[c], M[p] = M[p], M[c]
        inv = 1 / M[c][c] if not isinstance(M[c][c], Fraction) else Fraction(1) / M[c][c]
        M[c] = [v * inv for v in M[c]]
        for r in range(n):
            if r != c and M[r][c] != 0:
                f = M[r][c]
                M[r] = [a - f * bb for a, bb in zip(M[r], M[c])]
    return [M[i][n] for i in range(n)]


# --------------------------------------------------------------------------- #
# self test
# --------------------------------------------------------------------------- #


def _selftest():
    print("SHAPES: %d two-locus partitions with neither locus coalesced" % len(SHAPES))

    # (1) the panmictic two-locus system must reproduce Ohta-Kimura EXACTLY.
    # One deme, coalescence rate 1 per pair, recombination rho/2 per joint block,
    # source 2 * E[T2] = 2 (time in units of 2N). sigma_d^2 = N_ab / E[pq pq].
    for rho in (Fraction(1, 2), Fraction(1), Fraction(5), Fraction(20)):
        ts = TwoLocusSpace(1)
        Q = [dict() for _ in range(ts.ns)]

        def add(i, j, v):
            Q[i][j] = Q[i].get(j, 0) + v

        for i, (si, _) in enumerate(ts.keys):
            sh, nb = SHAPES[si], NBLK[si]
            for b1 in range(nb):
                for b2 in range(b1 + 1, nb):
                    j = ts.mk([b1 if sh[u] == b2 else sh[u] for u in range(4)], [0] * 4)
                    if j is not None:
                        add(i, j, Fraction(1))
                    add(i, i, Fraction(-1))
            for blk in range(nb):
                units = [u for u in range(4) if sh[u] == blk]
                if not (any(u in AU for u in units) and any(u in BU for u in units)):
                    continue
                pr, new = list(sh), max(sh) + 1
                for u in units:
                    if u in BU:
                        pr[u] = new
                add(i, ts.mk(pr, [0] * 4), rho / 2)
                add(i, i, -rho / 2)
        Q = [{c: v for c, v in row.items() if v != 0} for row in Q]
        src = [Fraction(2)] * ts.ns
        # the only symmetry here is among states of equal shape-size; use the trivial
        # group so the test exercises solve_exact and verify_residual on the FULL space
        P = solve_exact([[Q[i].get(j, Fraction(0)) for j in range(ts.ns)]
                         for i in range(ts.ns)], [-s for s in src])
        verify_residual(Q, src, P, zero=Fraction(0))
        s = lambda blocks: ts.state(blocks)
        num = (P[s([((0, 2), 0), ((1, 3), 0)])] - P[s([((0, 2), 0), ((1,), 0), ((3,), 0)])]
               - P[s([((0,), 0), ((2,), 0), ((1, 3), 0)])]
               + P[s([((0,), 0), ((2,), 0), ((1,), 0), ((3,), 0)])])
        den = P[s([((0,), 0), ((2,), 0), ((1,), 0), ((3,), 0)])]
        ok = (10 + rho) / ((2 + rho) * (11 + rho))
        assert num / den == ok, (rho, num / den, ok)
        print("  Ohta-Kimura at rho=%-6s : %s  EXACT" % (rho, num / den))

    # (2) orbits + lumpability on the two-deme space: the published count is 9.
    ts = TwoLocusSpace(2)
    maps = [lambda i: ts.permute(i, (1, 0, 2, 3)),
            lambda i: ts.permute(i, (0, 1, 3, 2)),
            lambda i: ts.permute(i, (2, 3, 0, 1)),
            lambda i: ts.permute(i, (0, 1, 2, 3), relabel=lambda d: 1 - d)]
    orbit_of, mem = orbits(ts.ns, maps)
    print("  two demes: %d states -> %d orbits, sizes %s"
          % (ts.ns, len(mem), [len(m) for m in mem]))
    assert (ts.ns, len(mem)) == (56, 9), (ts.ns, len(mem))

    # (3) one-locus: within-deme mean coalescence time is migration-free (Strobeck).
    for M in (Fraction(1, 2), Fraction(3), Fraction(12)):
        Q, idx, key = pair_rows(2, [[1], [0]], M / 2)
        t = solve_exact([[Q[i].get(j, Fraction(0)) for j in range(len(idx))]
                         for i in range(len(idx))], [Fraction(-1)] * len(idx))
        assert t[key(0, 0)] == 2, (M, t[key(0, 0)])
    print("  one locus: t2(same deme) = 2 for every M  (Strobeck/Nagylaki invariance)")

    # (4) the numpy/scipy original must enumerate the same space, or the duplication
    # between this module and argcore.py has drifted.
    try:
        import argcore
    except ImportError as e:
        print("  argcore cross-check SKIPPED (%s)" % e)
    else:
        for n in (1, 2, 3):
            a, b = argcore.TwoLocus(n), TwoLocusSpace(n)
            assert a.ns == b.ns and list(a.keys) == list(b.keys), n
            assert [list(r) for r in a.udeme] == b.udeme, n
        assert list(argcore.SHAPES) == SHAPES
        print("  argcore cross-check: identical enumeration at n = 1, 2, 3")

    print("SELF TEST PASSED")


if __name__ == "__main__":
    _selftest()
