/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.TwoLocusMicroscopicKernel

/-! Axiom audit of the assembled two-locus microscopic kernel. -/

open Descent.Portability.TwoLocusMicroscopicKernel

#print axioms enlargedCoordinateJet
#print axioms enlargedCoordinateJet_value
#print axioms enlargedFeature_eq_jet_value
#print axioms constantStageExpansion
#print axioms enlargedStageExpansion
#print axioms stageSlack_nonneg
#print axioms microscopicKernel
#print axioms microscopicError
#print axioms microscopicError_nonneg
#print axioms microscopicError_tendsto
#print axioms microscopicKernel_expansion
#print axioms twoLocusMicroscopicApproximation
#print axioms stageStructure
#print axioms sum_stage
#print axioms driftStage_sum_stored
#print axioms driftStage_sum_rightHeterozygosity
#print axioms driftStage_sum_constant
#print axioms recombinationLeftHeterozygosity_velocity
#print axioms recombinationRightHeterozygosity_velocity
#print axioms recombinationJointHeterozygosity_velocity
#print axioms recombinationDzObservable_velocity
#print axioms recombinationStage_sum_stored
#print axioms recombinationStage_sum_rightHeterozygosity
#print axioms migrationStage_sum_leftHeterozygosity
#print axioms migrationStage_sum_rightHeterozygosity
#print axioms rightMutationLeftHeterozygosity_velocity
#print axioms leftMutationRightHeterozygosity_velocity
#print axioms rightMutationRightHeterozygosity_velocity
#print axioms mutationStage_sum_leftHeterozygosity
#print axioms mutationStage_sum_rightHeterozygosity
#print axioms stage_generator_constant
#print axioms stage_generator_leftHeterozygosity
#print axioms stage_generator_rightHeterozygosity
#print axioms diracLowOrderLDState
#print axioms diracRealization
#print axioms lowOrderLDMigration_linkageProduct_pointwise
#print axioms migrationLinkageProduct_velocity
#print axioms migrationStage_sum_linkageProduct
#print axioms leftMutationLinkageProduct_velocity
#print axioms rightMutationLinkageProduct_velocity
#print axioms mutationStage_sum_linkageProduct
#print axioms stage_generator_linkageProduct
#print axioms lowOrderLDMigration_dzObservable_pointwise
#print axioms migrationDzObservable_velocity
#print axioms migrationStage_sum_dzObservable
#print axioms leftMutationDzObservable_velocity
#print axioms rightMutationDzObservable_velocity
#print axioms mutationStage_sum_dzObservable
#print axioms stage_generator_dzObservable
#print axioms migrationStage_sum_eq_rateWeighted
#print axioms mutationStageDrift
#print axioms enlargedGenerator_mulVec_stored_of_coupling_zero
