/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.SmoothedCoordinateLaws

/-! Axiom audit of SmoothedCoordinateLaws. -/

#print axioms Descent.Portability.SmoothedCoordinateLaws.uniformMoment_eq
#print axioms Descent.Portability.SmoothedCoordinateLaws.uniformMoment_odd
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothed_atom_moment
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothed_moment_match
#print axioms Descent.Portability.SmoothedCoordinateLaws.indicator_mem_unitInterval
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothDensity_nonneg
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothDensity_le
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothDensity_integral
#print axioms Descent.Portability.SmoothedCoordinateLaws.radial_smoothed_moment_match
#print axioms Descent.Portability.SmoothedCoordinateLaws.radial_smoothDensity_le
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothedLaw_absolutelyContinuous
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothedLaw_univ
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothedLaw_moment
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothedLaw_moment_match
#print axioms Descent.Portability.SmoothedCoordinateLaws.radial_smoothedLaw_moment_match
#print axioms Descent.Portability.SmoothedCoordinateLaws.radial_smoothedLaw_univ
#print axioms Descent.Portability.SmoothedCoordinateLaws.smoothedProduct_moment_match
#print axioms Descent.Portability.SmoothedCoordinateLaws.radial_smoothedProduct_moment_match
