/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.MomentOrderObstruction

/-! Axiom audit of MomentOrderObstruction. -/

#print axioms Descent.Portability.MomentOrderObstruction.abs_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.alternating_annihilates
#print axioms Descent.Portability.MomentOrderObstruction.sum_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.sum_abs_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.parityMass_nonneg
#print axioms Descent.Portability.MomentOrderObstruction.parityMass_sum
#print axioms Descent.Portability.MomentOrderObstruction.parity_gap
#print axioms Descent.Portability.MomentOrderObstruction.parity_moment_match
#print axioms Descent.Portability.MomentOrderObstruction.parity_separates
#print axioms Descent.Portability.MomentOrderObstruction.parity_gap_nodes
#print axioms Descent.Portability.MomentOrderObstruction.dot_smul_right
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_smul
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_self
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_line
#print axioms Descent.Portability.MomentOrderObstruction.partial_r2_fourth_order_gap
#print axioms Descent.Portability.MomentOrderObstruction.partial_r2_no_finite_moment_order
#print axioms Descent.Portability.MomentOrderObstruction.binProjection_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.meanProjection_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.explainedSum_closed
#print axioms Descent.Portability.MomentOrderObstruction.centeredSum_closed
#print axioms Descent.Portability.MomentOrderObstruction.lineResidual_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.lossReport_line
#print axioms Descent.Portability.MomentOrderObstruction.explainedSum_smul
#print axioms Descent.Portability.MomentOrderObstruction.centeredSum_smul
#print axioms Descent.Portability.MomentOrderObstruction.lossReport_smul
#print axioms Descent.Portability.MomentOrderObstruction.loss_report_fourth_order_gap
#print axioms Descent.Portability.MomentOrderObstruction.loss_report_no_finite_moment_order
