/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.ReplicaMetricInstances

/-! Axiom audit of ReplicaMetricInstances. -/

open Descent.Portability.ReplicaMetricInstances

#print axioms guardedRatio
#print axioms getD_guardedRatio
#print axioms conditionalMetric_guardedRatio
#print axioms expectation_guardedRatio_eq_tsum
#print axioms guardedRatio_certificate
#print axioms variance_le_quarter
#print axioms correlationNumerator_nonneg
#print axioms correlationNumerator_le_denominator
#print axioms correlationDenominator_le_one
#print axioms correlationDenominator_pos_iff
#print axioms squaredCorrelation_eq_guardedRatio
#print axioms expectation_squaredCorrelation_eq_tsum
#print axioms squaredCorrelation_certificate
#print axioms replicaCohortLaw_mass
#print axioms rankingCredit_bounds
#print axioms binaryAUCNumerator_eq_twoReplica
#print axioms binaryCaseMass_mem_unit
#print axioms aucNumerator_nonneg
#print axioms aucNumerator_le_denominator
#print axioms aucDenominator_le_one
#print axioms aucDenominator_pos_iff
#print axioms binaryAUC_eq_guardedRatio
#print axioms expectation_aucNumerator_eq_twoReplica
#print axioms expectation_binaryAUC_eq_tsum
#print axioms binaryAUC_certificate
#print axioms scoreGroupMass_eq_scoreCellMass
#print axioms scoreGroupMass_bool_eq_scoreMass
#print axioms scoreGroupMass_nonneg
#print axioms caseMass_le_scoreGroupMass
#print axioms scoreGroupMass_le_one
#print axioms squaredCaseMass_le_scoreGroupMass
#print axioms conditionalRepairedBrier_eq_sum_filter
#print axioms meanSquaredError_recalibration
#print axioms conditionalRepairedBrier_le_meanSquaredError
#print axioms meanSquaredError_conditionalMean
#print axioms expectation_conditionalRepairedBrier_eq_tsum
#print axioms repairedBrier_eq_conditionalRepairedBrier
#print axioms discreteECE_eq_calibrationError
#print axioms signedResidual_eq_expectation
#print axioms signedResidual_le_calibrationError
#print axioms calibrationError_eq_signedResidual
#print axioms calibrationError_isGreatest
#print axioms expectation_calibrationError_eq_strata
#print axioms calibrationError_continuous
#print axioms abs_convex_difference_le
#print axioms abs_calibrationError_sub_le
#print axioms eval_expectationPolynomial
#print axioms totalDegree_expectationPolynomial_le
#print axioms eval_pairPolynomial
#print axioms totalDegree_pairPolynomial_le
#print axioms eval_covariancePolynomial
#print axioms totalDegree_covariancePolynomial_le
#print axioms eval_correlationNumeratorPolynomial
#print axioms eval_correlationDenominatorPolynomial
#print axioms totalDegree_correlationNumeratorPolynomial_le
#print axioms totalDegree_correlationDenominatorPolynomial_le
#print axioms totalDegree_expansionTerm_le
#print axioms totalDegree_correlationTerm_le
#print axioms eval_correlationTerm
#print axioms eval_aucTerm
#print axioms totalDegree_aucTerm_le
#print axioms piLaw_eq_independentLaw
#print axioms definedIndicator_monomialEvent
#print axioms prod_dite_lt
#print axioms expectation_monomialEvent
#print axioms expectation_eval_eq_replicaReadout
#print axioms expectation_correlationTerm_eq_replicaReadout
#print axioms expectation_aucTerm_eq_replicaReadout
#print axioms calledMass_add_clearedMass
#print axioms calledMass_nonneg
#print axioms clearedMass_nonneg
#print axioms calledMass_eq_expectation
#print axioms prevalence_ruleConfusion
#print axioms confusion_rate_bounds
#print axioms expectation_div_eq_tsum
#print axioms expectation_recallRate_eq_tsum
#print axioms expectation_fpr_eq_tsum
#print axioms expectation_precision_eq_tsum
#print axioms binaryCaseMass_snd_eq_sum
#print axioms rates_mem_unit
#print axioms calledMass_thresholdRule_antitone
#print axioms averagePrecision_eq_sum_recall_increment
#print axioms averagePrecision_summand_bounds
#print axioms averagePrecision_numerator_bounds
#print axioms averagePrecision_mem_unit
#print axioms expectation_averagePrecision_eq_tsum
#print axioms expectation_averagePrecisionSummand_eq_tsum
