/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.PortabilityMomentLadderDecisionSharpness

/-! Axiom audit of PortabilityMomentLadderDecisionSharpness. -/

open Descent.Portability.PortabilityMomentLadderDecisionSharpness

#print axioms integral_founderEventLaw_of_stronglyMeasurable
#print axioms sum_resamplingMove_coordinate
#print axioms stronglyMeasurable_positiveQuotient
#print axioms pushforwardMass_resamplingMove_one
#print axioms positiveQuotient_resamplingMove_one
#print axioms expectedPositiveQuotient_founderEventLaw_zero
#print axioms expectedPositiveQuotient_founderEventLaw_one
#print axioms expectedPositiveQuotient_founderEventLaw_ne
#print axioms expectedFrequencies_eq_and_expectedRecall_ne
#print axioms expectedFrequencies_eq_and_expectedPrecision_ne
