/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.FinitePulseExposure

/-! Axiom audit of the finite migration-pulse realisation of an exposure law. -/

open Descent.Portability.FinitePulseExposure

#print axioms Descent.Portability.FinitePulseExposure.cumulativeMass_succ_sub
#print axioms Descent.Portability.FinitePulseExposure.cumulativeMass_le_donor
#print axioms Descent.Portability.FinitePulseExposure.one_sub_cumulativeMass_pos
#print axioms Descent.Portability.FinitePulseExposure.pulseFraction_nonneg
#print axioms Descent.Portability.FinitePulseExposure.pulseFraction_lt_one
#print axioms Descent.Portability.FinitePulseExposure.recipientFraction_eq
#print axioms Descent.Portability.FinitePulseExposure.recipientFraction_total
#print axioms Descent.Portability.FinitePulseExposure.exp_neg_pulseMigration
#print axioms Descent.Portability.FinitePulseExposure.sum_pulseMigration
#print axioms
  Descent.Portability.FinitePulseExposure.recipientFraction_mul_pulseFraction
#print axioms Descent.Portability.FinitePulseExposure.increment_div_donor
#print axioms Descent.Portability.FinitePulseExposure.stepEvent_migration_pulse
#print axioms Descent.Portability.FinitePulseExposure.fst_stepEvent_migration_pulse
#print axioms Descent.Portability.FinitePulseExposure.runEvents_append
#print axioms Descent.Portability.FinitePulseExposure.fst_runEvents_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.fst_runEvents_pulseHistory_total
#print axioms Descent.Portability.FinitePulseExposure.migrationTotal_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.recombinationTotal_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.migrationTotal_pulseHistory_total
#print axioms Descent.Portability.FinitePulseExposure.snd_stepEvent_migration_pulse
#print axioms Descent.Portability.FinitePulseExposure.snd_runEvents_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.snd_runEvents_pulseHistory_total
#print axioms Descent.Portability.FinitePulseExposure.couplingOfState_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.padByZero_val
#print axioms Descent.Portability.FinitePulseExposure.padByZero_self
#print axioms Descent.Portability.FinitePulseExposure.padByZero_mass_nonneg
#print axioms Descent.Portability.FinitePulseExposure.sum_range_padByZero_mass
#print axioms
  Descent.Portability.FinitePulseExposure.couplingOfState_pulseHistory_eq_exposureLaplace
#print axioms Descent.Portability.FinitePulseExposure.pulseMigration_nonneg
#print axioms Descent.Portability.FinitePulseExposure.eventTotals_nonneg_pulseHistory
#print axioms Descent.Portability.FinitePulseExposure.recombinationTotal_supportGaps
#print axioms Descent.Portability.FinitePulseExposure.runEvents_leading_recombination
#print axioms Descent.Portability.FinitePulseExposure.antitone_sortedExposure
#print axioms Descent.Portability.FinitePulseExposure.exposureLaplace_reorderedLaw
#print axioms Descent.Portability.FinitePulseExposure.padByZero_succ_le
#print axioms Descent.Portability.FinitePulseExposure.couplingOfState_realisingHistory
#print axioms Descent.Portability.FinitePulseExposure.fst_runEvents_realisingHistory
#print axioms Descent.Portability.FinitePulseExposure.migrationTotal_realisingHistory
#print axioms Descent.Portability.FinitePulseExposure.recombinationTotal_realisingHistory
#print axioms Descent.Portability.FinitePulseExposure.eventTotals_nonneg_realisingHistory
#print axioms Descent.Portability.FinitePulseExposure.exists_chronology_eq_exposureLaplace
#print axioms Descent.Portability.FinitePulseExposure.measurable_gridIndex
#print axioms Descent.Portability.FinitePulseExposure.gridExposure_mem_Icc
#print axioms Descent.Portability.FinitePulseExposure.gridExposure_gridIndex_le
#print axioms Descent.Portability.FinitePulseExposure.exposureLaplace_quantizedLaw
#print axioms Descent.Portability.FinitePulseExposure.tendsto_exposureLaplace_quantizedLaw
#print axioms
  Descent.Portability.FinitePulseExposure.tendsto_couplingOfState_quantizedHistory
#print axioms Descent.Portability.FinitePulseExposure.eventTotals_nonneg_quantizedHistory
#print axioms Descent.Portability.FinitePulseExposure.expectation_quantizedLaw
#print axioms Descent.Portability.FinitePulseExposure.tendsto_gridExposure_gridIndex
#print axioms
  Descent.Portability.FinitePulseExposure.tendsto_integral_lawMeasure_quantizedLaw
