/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.ConditionalOscillationDuality

/-! Axiom audit of ConditionalOscillationDuality. -/

#print axioms Descent.Portability.ConditionalOscillationDuality.jointLaw_expectation
#print axioms Descent.Portability.ConditionalOscillationDuality.kernel_average_le_sup
#print axioms Descent.Portability.ConditionalOscillationDuality.inf_le_kernel_average
#print axioms Descent.Portability.ConditionalOscillationDuality.combo_expectation
#print axioms Descent.Portability.ConditionalOscillationDuality.kernelGap_le_dual
#print axioms Descent.Portability.ConditionalOscillationDuality.convex_oscNbhd
#print axioms Descent.Portability.ConditionalOscillationDuality.oscNbhd_mem_of_close
#print axioms Descent.Portability.ConditionalOscillationDuality.isOpen_oscNbhd
#print axioms Descent.Portability.ConditionalOscillationDuality.notMem_oscNbhd
#print axioms Descent.Portability.ConditionalOscillationDuality.sum_row_indicator
#print axioms Descent.Portability.ConditionalOscillationDuality.sum_pos_bump
#print axioms Descent.Portability.ConditionalOscillationDuality.sum_feature_combo
#print axioms Descent.Portability.ConditionalOscillationDuality.oscTotal_nonneg
#print axioms Descent.Portability.ConditionalOscillationDuality.kernel_pair_difference
#print axioms Descent.Portability.ConditionalOscillationDuality.le_of_kernelGaps_upperBound
#print axioms Descent.Portability.ConditionalOscillationDuality.conditional_oscillation_duality
#print axioms Descent.Portability.ConditionalOscillationDuality.kernel_report_split
#print axioms Descent.Portability.ConditionalOscillationDuality.oscillation_rule_error
#print axioms Descent.Portability.ConditionalOscillationDuality.kernelGaps_zero_iff
#print axioms Descent.Portability.ConditionalOscillationDuality.featureCombo_combo
#print axioms Descent.Portability.ConditionalOscillationDuality.shrinkRadius_pos
#print axioms Descent.Portability.ConditionalOscillationDuality.shrinkRadius_spec
#print axioms Descent.Portability.ConditionalOscillationDuality.negPart_sum
#print axioms Descent.Portability.ConditionalOscillationDuality.topUp_nonneg
#print axioms Descent.Portability.ConditionalOscillationDuality.topUp_sum
#print axioms Descent.Portability.ConditionalOscillationDuality.extremalKernel_nonneg
#print axioms Descent.Portability.ConditionalOscillationDuality.extremalKernel_sum
#print axioms Descent.Portability.ConditionalOscillationDuality.extremalKernel_diff
