/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.BinomialAggregateEnvelope

/-! Axiom audit of BinomialAggregateEnvelope. -/

#print axioms Descent.Portability.BinomialAggregateEnvelope.binWeight_zero
#print axioms Descent.Portability.BinomialAggregateEnvelope.binWeight_succ_zero
#print axioms Descent.Portability.BinomialAggregateEnvelope.binWeight_succ_succ
#print axioms Descent.Portability.BinomialAggregateEnvelope.binWeight_nonneg
#print axioms Descent.Portability.BinomialAggregateEnvelope.binWeight_eq_zero_of_lt
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_congr
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_add
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_smul
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_succ
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_one
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_id
#print axioms Descent.Portability.BinomialAggregateEnvelope.binMoment_sq
#print axioms Descent.Portability.BinomialAggregateEnvelope.binomialExp_eq_binMoment
#print axioms Descent.Portability.BinomialAggregateEnvelope.countR2_eq_architecture_r2
#print axioms Descent.Portability.BinomialAggregateEnvelope.countMse_eq_architecture_mse
#print axioms Descent.Portability.BinomialAggregateEnvelope.countR2_top
#print axioms Descent.Portability.BinomialAggregateEnvelope.countR2_bot
#print axioms Descent.Portability.BinomialAggregateEnvelope.countMse_top
#print axioms Descent.Portability.BinomialAggregateEnvelope.countMse_bot
#print axioms Descent.Portability.BinomialAggregateEnvelope.binomial_envelope_lower
#print axioms Descent.Portability.BinomialAggregateEnvelope.sync_envelope_upper
#print axioms Descent.Portability.BinomialAggregateEnvelope.binomial_envelope_mse
#print axioms Descent.Portability.BinomialAggregateEnvelope.sync_envelope_mse
#print axioms Descent.Portability.BinomialAggregateEnvelope.mixTwo_apply
#print axioms Descent.Portability.BinomialAggregateEnvelope.envelope_mixture_r2
#print axioms Descent.Portability.BinomialAggregateEnvelope.envelope_mixture_mse
#print axioms Descent.Portability.BinomialAggregateEnvelope.envelope_attains
