/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.GaussianEffectPortabilityLaw

/-!
Kernel axiom audit for Gaussian effect integration and its finite-outcome mixture.
-/

#print axioms Descent.Portability.GaussianEffectPortabilityLaw.caseProbability_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.caseProbability_bounds
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.crossForm_effects_continuous
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.varianceForm_effects_continuous
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.formRatio_observable_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.report_observable_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.report_eq_ratio
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.report_nonneg
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedReport_defined
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedReport_value_bounds
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedReport_value_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.report_defined_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.labelWeight_le_one
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.weighted_clipped_integrable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.weighted_defined_integrable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedExpectation_formula
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedNumerator_eq_sum_integrals
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.reportValue_nonneg
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.reportValue_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.innerValue_nonneg
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.innerValue_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedInner_nonneg
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedInner_measurable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedInner_integrable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedReport_value_eq_min
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedInner_le_innerValue
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.clippedInner_nat_mono
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.innerValue_eq_iSup_clipped
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.ofReal_clippedNumerator
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.extendedNumerator_eq_iSup_clipped
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.integrable_innerValue_iff
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.successProbability_eq_joint_defined
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.successProbability_bounds
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.weighted_report_integrable
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.extendedNumerator_toReal
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.finite_reportedExpectation_formula
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.effectLaw_probability
#print axioms Descent.Portability.GaussianEffectPortabilityLaw.jointLaw_probability
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.branchMeasure_univ
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.jointMeasure_probability
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integrable_branchMeasure
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integral_branchMeasure
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integrable_jointMeasure
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integral_jointMeasure
#print axioms Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integral_constant_kernel
#print axioms
  Descent.Portability.PartialMetricMixture.FiniteOutcomeKernel.integral_deterministic_kernel
#print axioms Descent.Portability.PartialMetricMixture.definedMass_jointMeasure
#print axioms Descent.Portability.PartialMetricMixture.weightedMetric_jointMeasure
#print axioms Descent.Portability.PartialMetricMixture.conditionalMetric_jointMeasure
