/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.EndToEndDiploidCalibration

/-! Axiom audit of EndToEndDiploidCalibration. -/

open Descent.Portability.EndToEndDiploidCalibration

#print axioms expectedDiploidCalibrationSlope_diploidSum
#print axioms expectedDiploidCalibrationPortability_diploidSum
#print axioms expectedDiploidCalibrationIntercept_diploidSum
#print axioms expectedDiploidCalibrationSlope_diploidSum_historyEventKernel
#print axioms expectedDiploidCalibrationPortability_diploidSum_historyEventKernel
#print axioms expectedDiploidCalibrationIntercept_diploidSum_historyEventKernel
#print axioms expectedDiploidCalibrationSlope_diploidSum_rateHistoryKernel
#print axioms expectedDiploidCalibrationPortability_diploidSum_rateHistoryKernel
#print axioms expectedDiploidCalibrationIntercept_diploidSum_rateHistoryKernel
#print axioms polynomialFunction_diploidMeanPolynomial
#print axioms polynomialFunction_diploidCovariancePolynomial
#print axioms polynomialFunction_diploidVariance
#print axioms polynomialFunction_diploidInterceptPolynomial
#print axioms totalDegree_diploidMeanPolynomial_le
#print axioms totalDegree_diploidCovariancePolynomial_le
#print axioms totalDegree_diploidInterceptPolynomial_le
#print axioms expectedDiploidCalibrationSlope_eq_moment
#print axioms expectedDiploidCalibrationPortability_eq_moment
#print axioms expectedDiploidCalibrationIntercept_eq_moment
#print axioms expectedDiploidCalibrationSlope_historyEventKernel
#print axioms expectedDiploidCalibrationPortability_historyEventKernel
#print axioms expectedDiploidCalibrationIntercept_historyEventKernel
#print axioms expectedDiploidCalibrationSlope_rateHistoryKernel
#print axioms expectedDiploidCalibrationPortability_rateHistoryKernel
#print axioms expectedDiploidCalibrationIntercept_rateHistoryKernel
#print axioms expectedDiploidCalibrationSlope_eq_of_moments_eq
#print axioms expectedDiploidCalibrationPortability_eq_of_moments_eq
#print axioms expectedDiploidCalibrationIntercept_eq_of_moments_eq
#print axioms momentDiploidCalibrationSlope_diploidSum_historyEventKernel
#print axioms momentDiploidCalibrationIntercept_diploidSum_historyEventKernel
#print axioms expectation_inbredMating_fairSwitch
#print axioms calibrationSlope_inbredMating_diploidProduct
#print axioms calibrationSlope_fairSwitch_alleleValue
#print axioms diploidProduct_breaks_calibration_transfer
