/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.UniformPenetranceArchitecture

/-! Axiom audit of UniformPenetranceArchitecture. -/

open Descent.Portability.UniformPenetranceArchitecture

#print axioms sum_cells
#print axioms penetrance_nonneg
#print axioms penetrance_le_one
#print axioms penetrance_eq_self
#print axioms penetranceLaw_mass
#print axioms expectation_penetranceLaw
#print axioms expectation_cellScore_penetranceLaw
#print axioms expectation_cellOutcome_penetranceLaw
#print axioms variance_cellScore_penetranceLaw
#print axioms variance_cellOutcome_penetranceLaw
#print axioms covariance_penetranceLaw
#print axioms squaredCorrelation_penetranceLaw
#print axioms squaredCorrelation_penetranceLaw_zero
#print axioms calibrationSlope_penetranceLaw
#print axioms calibrationIntercept_penetranceLaw
#print axioms meanSquaredError_penetranceLaw
#print axioms binaryCaseMass_penetranceLaw
#print axioms binaryAUCNumerator_penetranceLaw
#print axioms binaryAUC_penetranceLaw
#print axioms scoreGroupMass_penetranceLaw_true
#print axioms scoreGroupMass_penetranceLaw_false
#print axioms scoreSuccessMass_penetranceLaw_true
#print axioms scoreSuccessMass_penetranceLaw_false
#print axioms discreteECE_penetranceLaw
#print axioms repairedBrier_penetranceLaw
#print axioms accuracyRate_penetranceLaw
#print axioms repairedLogLoss_penetranceLaw
#print axioms rawLogLoss_penetranceLaw
#print axioms pooledPenetranceLaw_mass
#print axioms expectation_pooledPenetranceLaw
#print axioms squaredCorrelation_pooledPenetranceLaw
#print axioms integral_unit_congr
#print axioms integral_unit_quadratic
#print axioms integral_unit_half_pow
#print axioms intervalIntegrable_unit_ratio
#print axioms integral_unit_ratio
#print axioms integral_unit_auc
#print axioms integral_unit_negMulLog
#print axioms integral_unit_negMulLog_one_sub
#print axioms integral_unit_binEntropy
#print axioms integral_squaredCorrelation_penetranceLaw
#print axioms integral_binaryAUC_penetranceLaw
#print axioms integral_calibrationSlope_penetranceLaw
#print axioms integral_meanSquaredError_penetranceLaw
#print axioms integral_discreteECE_penetranceLaw
#print axioms integral_accuracyRate_penetranceLaw
#print axioms integral_repairedBrier_penetranceLaw
#print axioms integral_repairedLogLoss_penetranceLaw
#print axioms squaredCorrelation_sublevel_eq_Icc
#print axioms volume_squaredCorrelation_sublevel
#print axioms pooledPenetranceLaw_mass_eq_integral
#print axioms replicaRatio_eq_ratio
#print axioms one_sub_replicaDenominator
#print axioms integral_replica_coefficient
#print axioms integral_replica_tail
#print axioms integral_replica_resolved
#print axioms replica_mass_normalization
#print axioms intervalIntegrable_replica_partial
#print axioms integral_replica_partial
#print axioms ratio_eq_partial_add_remainder
#print axioms ratio_mem_unitInterval
#print axioms replica_certificate
