/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.MomentOrderObstruction

/-! Axiom audit of MomentOrderObstruction. -/

#print axioms Descent.Portability.MomentOrderObstruction.abs_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.alternating_annihilates
#print axioms Descent.Portability.MomentOrderObstruction.sum_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.sum_abs_alternatingWeight
#print axioms Descent.Portability.MomentOrderObstruction.parityMass_nonneg
#print axioms Descent.Portability.MomentOrderObstruction.parityMass_sum
#print axioms Descent.Portability.MomentOrderObstruction.parity_gap
#print axioms Descent.Portability.MomentOrderObstruction.parity_moment_match
#print axioms Descent.Portability.MomentOrderObstruction.parity_separates
#print axioms Descent.Portability.MomentOrderObstruction.parity_gap_nodes
#print axioms Descent.Portability.MomentOrderObstruction.dot_smul_right
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_smul
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_self
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.partialR2_line
#print axioms Descent.Portability.MomentOrderObstruction.partial_r2_fourth_order_gap
#print axioms Descent.Portability.MomentOrderObstruction.partial_r2_no_finite_moment_order
#print axioms Descent.Portability.MomentOrderObstruction.binProjection_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.meanProjection_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.explainedSum_closed
#print axioms Descent.Portability.MomentOrderObstruction.centeredSum_closed
#print axioms Descent.Portability.MomentOrderObstruction.lineResidual_orthogonal
#print axioms Descent.Portability.MomentOrderObstruction.lossReport_line
#print axioms Descent.Portability.MomentOrderObstruction.explainedSum_smul
#print axioms Descent.Portability.MomentOrderObstruction.centeredSum_smul
#print axioms Descent.Portability.MomentOrderObstruction.lossReport_smul
#print axioms Descent.Portability.MomentOrderObstruction.loss_report_fourth_order_gap
#print axioms Descent.Portability.MomentOrderObstruction.loss_report_no_finite_moment_order
#print axioms Descent.Portability.MomentOrderObstruction.vec6_apply
#print axioms Descent.Portability.MomentOrderObstruction.vec6_sq
#print axioms Descent.Portability.MomentOrderObstruction.dot_vec6
#print axioms Descent.Portability.MomentOrderObstruction.explainedSum_vec6
#print axioms Descent.Portability.MomentOrderObstruction.centeredSum_vec6
#print axioms Descent.Portability.MomentOrderObstruction.fwdDiff_double_step
#print axioms Descent.Portability.MomentOrderObstruction.abs_fwdDiff_iter_le
#print axioms Descent.Portability.MomentOrderObstruction.fwdDiff_descend
#print axioms Descent.Portability.MomentOrderObstruction.const_of_fwdDiff_iter_eq_zero
#print axioms Descent.Portability.MomentOrderObstruction.exists_fwdDiff_ne_zero
#print axioms Descent.Portability.MomentOrderObstruction.fwdDiff_iter_eq_alternating
#print axioms Descent.Portability.MomentOrderObstruction.bounded_nonconstant_separates
#print axioms Descent.Portability.MomentOrderObstruction.one_le_two_pow_real
#print axioms Descent.Portability.MomentOrderObstruction.partial_r2_parity_separates
#print axioms Descent.Portability.MomentOrderObstruction.loss_report_parity_separates
#print axioms Descent.Portability.MomentOrderObstruction.neg_one_pow_sub
