/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.AttainableChronologyCurve

/-! Axiom audit of the attainable coupling curve at fixed demographic totals. -/

open Descent.Portability.AttainableChronologyCurve

#print axioms Descent.Portability.AttainableChronologyCurve.donorFraction_eq_integral
#print axioms Descent.Portability.AttainableChronologyCurve.cumulativeRate_sub_eq_integral
#print axioms Descent.Portability.AttainableChronologyCurve.normalisedCoupling_le_one
#print axioms Descent.Portability.AttainableChronologyCurve.exp_neg_le_normalisedCoupling
#print axioms Descent.Portability.AttainableChronologyCurve.runEvents_threeBlockHistory
#print axioms Descent.Portability.AttainableChronologyCurve.migrationTotal_threeBlockHistory
#print axioms
  Descent.Portability.AttainableChronologyCurve.recombinationTotal_threeBlockHistory
#print axioms
  Descent.Portability.AttainableChronologyCurve.couplingOfState_threeBlockHistory
#print axioms Descent.Portability.AttainableChronologyCurve.attainable_coupling_range
#print axioms Descent.Portability.AttainableChronologyCurve.reportMetrics_chronologyLaw
#print axioms Descent.Portability.AttainableChronologyCurve.attainable_metric_curve
#print axioms Descent.Portability.AttainableChronologyCurve.exp_neg_log_two
#print axioms Descent.Portability.AttainableChronologyCurve.threeBlock_migration_first
#print axioms Descent.Portability.AttainableChronologyCurve.threeBlock_recombination_first
#print axioms Descent.Portability.AttainableChronologyCurve.reportMetrics_chronologyReportLaw
#print axioms
  Descent.Portability.AttainableChronologyCurve.scaled_normalisedCoupling_eq_measureLaplace
#print axioms Descent.Portability.AttainableChronologyCurve.chronologyExposureLaw_univ
#print axioms
  Descent.Portability.AttainableChronologyCurve.isProbabilityMeasure_chronologyExposureLaw
#print axioms Descent.Portability.AttainableChronologyCurve.chronologyExposureLaw_ae_mem_Icc
#print axioms Descent.Portability.AttainableChronologyCurve.one_sub_fst_runEvents
#print axioms Descent.Portability.AttainableChronologyCurve.runEvents_linkage_bounds
#print axioms Descent.Portability.AttainableChronologyCurve.couplingOfState_runEvents_mem_Icc
#print axioms Descent.Portability.AttainableChronologyCurve.attainable_coupling_range_events
#print axioms Descent.Portability.AttainableChronologyCurve.attainable_metric_curve_events
#print axioms Descent.Portability.AttainableChronologyCurve.continuous_unitPulse
#print axioms Descent.Portability.AttainableChronologyCurve.unitPulse_nonneg
#print axioms Descent.Portability.AttainableChronologyCurve.unitPulse_eq_zero
#print axioms Descent.Portability.AttainableChronologyCurve.integral_unitPulse_eq_zero
#print axioms Descent.Portability.AttainableChronologyCurve.integral_unitPulse_unit
#print axioms Descent.Portability.AttainableChronologyCurve.integral_unitPulse_eq_one
#print axioms Descent.Portability.AttainableChronologyCurve.continuous_unitPulse_sub
#print axioms Descent.Portability.AttainableChronologyCurve.continuous_pulseMigrationRate
#print axioms Descent.Portability.AttainableChronologyCurve.continuous_pulseRecombinationRate
#print axioms Descent.Portability.AttainableChronologyCurve.pulseMigrationRate_nonneg
#print axioms Descent.Portability.AttainableChronologyCurve.pulseRecombinationRate_nonneg
#print axioms Descent.Portability.AttainableChronologyCurve.pulseMigrationRate_eq_zero
#print axioms Descent.Portability.AttainableChronologyCurve.cumulativeRate_pulseMigrationRate
#print axioms Descent.Portability.AttainableChronologyCurve.integral_pulseRecombinationRate
#print axioms
  Descent.Portability.AttainableChronologyCurve.cumulativeRate_pulseRecombinationRate
#print axioms Descent.Portability.AttainableChronologyCurve.remaining_pulseRecombinationRate
#print axioms Descent.Portability.AttainableChronologyCurve.normalisedCoupling_pulseHistory
#print axioms
  Descent.Portability.AttainableChronologyCurve.exists_continuous_chronology_of_mem_Icc
#print axioms
  Descent.Portability.AttainableChronologyCurve.exists_continuous_chronology_at_horizon
#print axioms
  Descent.Portability.AttainableChronologyCurve.attainable_coupling_range_continuous
#print axioms
  Descent.Portability.AttainableChronologyCurve.attainable_metric_curve_continuous
