/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.TurnoverArchitectureMetrics

/-! Axiom audit of TurnoverArchitectureMetrics. -/

#print axioms Descent.Portability.TurnoverArchitectureMetrics.signValue_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.signValue_not
#print axioms Descent.Portability.TurnoverArchitectureMetrics.flipCoord_self
#print axioms Descent.Portability.TurnoverArchitectureMetrics.flipCoord_ne
#print axioms Descent.Portability.TurnoverArchitectureMetrics.flipCoord_invol
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_flip_eq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_odd_vanishes
#print axioms Descent.Portability.TurnoverArchitectureMetrics.blockScore_insert
#print axioms Descent.Portability.TurnoverArchitectureMetrics.blockScore_flip
#print axioms Descent.Portability.TurnoverArchitectureMetrics.blockScore_sub
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_blockScore_mean
#print axioms Descent.Portability.TurnoverArchitectureMetrics.card_config
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_blockScore_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_blockScore_cube
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_blockScore_quartic
#print axioms Descent.Portability.TurnoverArchitectureMetrics.eval_comb3
#print axioms Descent.Portability.TurnoverArchitectureMetrics.eval_comb5
#print axioms Descent.Portability.TurnoverArchitectureMetrics.uniform_geno_eq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_geno
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_mul
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_lin_noise_mean
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_lin_noise_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_lin_noise_quartic
#print axioms Descent.Portability.TurnoverArchitectureMetrics.reversedWeightSq_eq_filter
#print axioms Descent.Portability.TurnoverArchitectureMetrics.residualCoeff_sq_sum
#print axioms Descent.Portability.TurnoverArchitectureMetrics.residualCoeff_quartic_sum
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_effect_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.blockScore_add
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_blockScore_cross
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_blockScore_mean
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_blockScore_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.exp_blockScore_cross
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecturePop_exp
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecturePop_score
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecturePop_phenotype
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecturePop_residual
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_score_variance
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_outcome_variance
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_predictive_covariance
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_r2
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_mse
#print axioms Descent.Portability.TurnoverArchitectureMetrics.architecture_loss_variance
#print axioms Descent.Portability.TurnoverArchitectureMetrics.noise_var_nonneg
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_signValue_eq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.sum_signValue_reversed
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equalWeights_sq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equalWeights_norm
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equalWeights_alignment
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equalWeights_reversedWeightSq
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equal_weight_r2
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equal_weight_mse
#print axioms Descent.Portability.TurnoverArchitectureMetrics.equal_weight_loss_variance
#print axioms Descent.Portability.TurnoverArchitectureMetrics.aggregation_gap
#print axioms Descent.Portability.TurnoverArchitectureMetrics.pathwise_distance_variance_decomposition
#print axioms Descent.Portability.TurnoverArchitectureMetrics.pathwise_distance_explainability
