/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.EndToEndSensitivityDecision

/-! Axiom audit of EndToEndSensitivityDecision. -/

open Descent.Portability.EndToEndSensitivityDecision

#print axioms hasDerivAt_of_hasSum_dotProduct_segmentHistory
#print axioms hasDerivAt_of_hasSum_dotProduct_rateSegment
#print axioms hasSum_expectedEntropy_historyEventKernel
#print axioms hasSum_expectedEntropy_rateHistoryKernel
#print axioms hasDerivAt_expectedEntropy_segmentHistory
#print axioms hasDerivAt_expectedEntropy_rateSegment
#print axioms hasSum_expectedConditionalEntropy_historyEventKernel
#print axioms hasSum_expectedConditionalEntropy_rateHistoryKernel
#print axioms hasSum_expectedMutualInformation_historyEventKernel
#print axioms hasSum_expectedMutualInformation_rateHistoryKernel
#print axioms hasDerivAt_expectedConditionalEntropy_segmentHistory
#print axioms hasDerivAt_expectedConditionalEntropy_rateSegment
#print axioms hasDerivAt_expectedMutualInformation_segmentHistory
#print axioms hasDerivAt_expectedMutualInformation_rateSegment
#print axioms hasDerivAt_expectedForecastLogLoss_segmentHistory
#print axioms hasDerivAt_expectedForecastLogLoss_rateSegment
#print axioms hasDerivAt_expectedConfusion_segmentHistory
#print axioms hasDerivAt_expectedConfusion_rateSegment
#print axioms hasDerivAt_expectedNetBenefit_segmentHistory
#print axioms hasDerivAt_expectedNetBenefit_rateSegment
#print axioms integral_prevalence_historyEventKernel
#print axioms integral_prevalence_rateHistoryKernel
#print axioms hasDerivAt_integral_prevalence_segmentHistory
#print axioms hasDerivAt_integral_prevalence_rateSegment
#print axioms hasDerivAt_integral_calledFraction_segmentHistory
#print axioms hasDerivAt_integral_calledFraction_rateSegment
#print axioms cellRatio
#print axioms tableSensitivity_eq_cellRatio
#print axioms tableSpecificity_eq_cellRatio
#print axioms tablePPV_eq_cellRatio
#print axioms tableNPV_eq_cellRatio
#print axioms expectedMetricPortability_cellRatio
#print axioms hasDerivAt_expectedMetricPortability_cellRatio_segmentHistory
#print axioms hasDerivAt_expectedMetricPortability_cellRatio_rateSegment
#print axioms deriv_expectedMetricPortability_cellRatio_segmentHistory_neg_iff
#print axioms deriv_expectedMetricPortability_cellRatio_rateSegment_neg_iff
