"""Battery 15: the drift-variance family, selection recurrences, OLS variance.

The drift-variance family is four definitions of nearly the same quantity:

  pgsDriftVariance_one_pop   fst * V_A
  pgsDiffVariance_two_pop    2 * pgsDriftVariance_one_pop
  expectedPGSDiffVariance    V_A * 2 * fst
  Var_Delta_Mu               2 * fst * V_A        (already validated, one branch)

The last three are the same number and the first is half of it, so at most one
of the two values is right for any given reading of `fst`. One simulation of a
drifting population settles it, because the variance of a single population's
mean score and the variance of the difference between two are both measurable on
the same run.

`equilibriumEffectVariance = v_mutation / s` is the fixed point of
`effectVarianceRecurrence`, so iterating that recurrence tests the algebra of the
fixed point exactly as the mutation-selection balances were tested.

`olsEffectEstimationVariance = sigma2 / (n * varX)` is the textbook sampling
variance of a regression coefficient, and the oracle is the observed scatter of
that coefficient over replicate studies -- a quantity generated by the
regression, not by the formula, so this is not a generative self-test.
"""
import json
import math

import numpy as np

from battery_core import RESULTS, record


def drift_one_branch(Ne, t, n_loci=600, reps=4000, seed=1):
    """One deme drifts from a fixed ancestral state; the other is held there."""
    rng = np.random.default_rng(seed)
    p0 = rng.uniform(0.05, 0.95, n_loci)
    beta = rng.normal(0, 1, n_loci)
    two_n = int(2 * Ne)
    p1 = np.tile(p0, (reps, 1))
    p2 = np.tile(p0, (reps, 1))
    for _ in range(t):
        p1 = rng.binomial(two_n, p1) / two_n
        p2 = rng.binomial(two_n, p2) / two_n
    mu1 = (2 * p1 * beta).sum(axis=1)
    mu2 = (2 * p2 * beta).sum(axis=1)
    mu_anc = float((2 * p0 * beta).sum())
    V_A = float((2 * p0 * (1 - p0) * beta ** 2).sum())
    F = 1 - (1 - 1.0 / (2 * Ne)) ** t
    return dict(one_pop_var=float(np.var(mu1 - mu_anc, ddof=1)),
                two_pop_var=float(np.var(mu1 - mu2, ddof=1)),
                V_A=V_A, F=F, reps=reps)


def test_drift_variance_family():
    cells_one, cells_two, cells_exp = [], [], []
    cells_one_corrected, cells_two_corrected, cells_exp_corrected = [], [], []
    ctrl_V_A = ctrl_V_A_measured = ctrl_sem = 0.0
    for Ne, t in ((200, 30), (200, 100), (200, 250)):
        r = drift_one_branch(Ne, t, seed=12001 + t)
        s1 = r["one_pop_var"] * math.sqrt(2.0 / (r["reps"] - 1))
        s2 = r["two_pop_var"] * math.sqrt(2.0 / (r["reps"] - 1))
        lab = "Ne=%d t=%d (F=%.3f)" % (Ne, t, r["F"])
        cells_one.append(dict(design=lab, lean=r["F"] * r["V_A"],
                              truth=r["one_pop_var"], sem=s1))
        cells_two.append(dict(design=lab, lean=2 * r["F"] * r["V_A"],
                              truth=r["two_pop_var"], sem=s2))
        cells_exp.append(dict(design=lab, lean=r["V_A"] * 2 * r["F"],
                              truth=r["two_pop_var"], sem=s2))
        cells_one_corrected.append(dict(design=lab, lean=2 * r["F"] * r["V_A"],
                                        truth=r["one_pop_var"], sem=s1))
        cells_two_corrected.append(dict(design=lab, lean=4 * r["F"] * r["V_A"],
                                        truth=r["two_pop_var"], sem=s2))
        cells_exp_corrected.append(dict(design=lab, lean=r["V_A"] * 4 * r["F"],
                                        truth=r["two_pop_var"], sem=s2))
        # CONTROL: the ancestral additive variance, which is what both bodies
        # are a multiple of. It is computed from the ancestral frequencies and
        # measured as the drift variance extrapolated to F = 1 through the
        # corrected law, so it fails if the drift index or the effect scale is
        # wrong and passes when the only thing left is the factor.
        if t == 250:
            ctrl_V_A = r["V_A"]
            ctrl_V_A_measured = r["one_pop_var"] / (2 * r["F"])
            ctrl_sem = s1 / (2 * r["F"])
    # THE CORPUS ROWS ARE THE CORRECTED BODIES, and the superseded ones are
    # carried as named competitors.  This block used to transcribe `fst * V_A`
    # and `2 * fst * V_A` as the corpus rows -- the bodies BEFORE the ploidy
    # correction -- so the ledger carried three FALSIFIED rows against three
    # names whose Lean bodies had since doubled, with an empty note, and a
    # reader who greps for the name and not for the `source` field reached the
    # opposite conclusion about all three.  That is the same defect `bulk22`
    # carried on `taggedEffect` and was repaired for: the corpus took the
    # challenger and the labels stayed.
    #
    # `pgsDriftVariance_one_pop`'s own docstring records the measurement that
    # moved it -- the superseded body 50.7 percent low at 22.7 sems in every
    # cell -- so the numbers here are not new; what is new is that the ledger
    # now says the same thing the Lean does.
    # `realised_inputs=True`: F comes from the drift recurrence
    # `1 - (1 - 1/(2Ne))^t` and V_A from the ancestral frequencies, both exact
    # constants of the design rather than estimates taken off the same
    # replicates the variance is measured on -- so there is no nominal/realised
    # gap for the 22.7-sem rejection to be confused with. Undeclared, that
    # rejection is downgraded to a LEAD and the superseded bodies keep looking
    # uncompeted, which is the state this battery was already in.
    MODEL = dict(realised_inputs=True)
    reg_one = ("variance of ONE population's mean score about the ancestral "
               "mean, fst read as the per-branch drift index")
    reg_two = ("variance of the difference between two independently drifted "
               "populations, same runs")
    control = dict(design="V_A from the ancestral frequencies "
                          "[sum 2 p (1-p) beta^2]",
                   lean=ctrl_V_A, truth=ctrl_V_A_measured, sem=ctrl_sem)
    record("pgsDriftVariance_one_pop", "PolygenicAdaptation.lean",
           "2 * fst * V_A", cells_one_corrected, regime=reg_one,
           control=control, **MODEL)
    record("pgsDriftVariance_one_pop [superseded, missing the ploidy factor "
           "(fst * V_A)]", "PolygenicAdaptation.lean",
           "fst * V_A", cells_one, regime=reg_one, control=control, **MODEL)
    record("pgsDiffVariance_two_pop", "PolygenicAdaptation.lean",
           "4 * fst * V_A", cells_two_corrected, regime=reg_two,
           control=control, **MODEL)
    record("pgsDiffVariance_two_pop [superseded, inherited the missing ploidy "
           "factor (2 * fst * V_A)]", "PolygenicAdaptation.lean",
           "2 * fst * V_A", cells_two, regime=reg_two, control=control,
           **MODEL)
    record("expectedPGSDiffVariance", "PolygenicAdaptation.lean",
           "V_A * 4 * fst", cells_exp_corrected,
           regime="same quantity, same runs", control=control, **MODEL)
    record("expectedPGSDiffVariance [superseded, inherited the missing ploidy "
           "factor (V_A * 2 * fst)]", "PolygenicAdaptation.lean",
           "V_A * 2 * fst", cells_exp, regime="same quantity, same runs",
           control=control, **MODEL)


def test_effect_variance_recurrence():
    """equilibriumEffectVariance as the fixed point of effectVarianceRecurrence."""
    cells_fp, cells_step = [], []
    for v_mut, s in ((0.01, 0.05), (0.02, 0.2), (0.005, 0.01)):
        V = 5.0
        for _ in range(200000):
            V = (1 - s) * V + v_mut
        cells_fp.append(dict(design="v_mut=%.3f s=%.2f" % (v_mut, s),
                             lean=v_mut / s, truth=float(V),
                             sem=abs(float(V)) * 1e-9))
    record("equilibriumEffectVariance", "SelectionArchitecture.lean",
           "v_mutation / s", cells_fp,
           regime="fixed point of effectVarianceRecurrence, iterated from "
                  "V = 5.0, far above every equilibrium in the design")


def test_ols_variance():
    """olsEffectEstimationVariance against the scatter of a real regression."""
    rng = np.random.default_rng(12101)
    cells = []
    for n, sigma2, p in ((2000, 1.0, 0.3), (8000, 1.0, 0.3), (2000, 4.0, 0.1)):
        reps = 4000
        bs = []
        for _ in range(reps):
            g = rng.binomial(2, p, n).astype(float)
            y = 0.05 * g + rng.normal(0, math.sqrt(sigma2), n)
            gc = g - g.mean()
            bs.append(float(gc @ (y - y.mean()) / (gc @ gc)))
        obs = float(np.var(bs, ddof=1))
        varX = 2 * p * (1 - p)
        cells.append(dict(design="n=%d s2=%.1f p=%.1f" % (n, sigma2, p),
                          lean=sigma2 / (n * varX), truth=obs,
                          sem=obs * math.sqrt(2.0 / (reps - 1))))
    record("olsEffectEstimationVariance", "GeneticArchitectureDiscovery.lean",
           "sigma2 / (n * varX)", cells,
           regime="observed scatter of a single-SNP regression coefficient over "
                  "4000 replicate studies")


def test_gwas_ncp_fork():
    """gwasNCP = n b^2 2p(1-p): the same body as AncestrySpecificPower.ncp."""
    rng = np.random.default_rng(12201)
    cells = []
    for n, p, beta in ((4000, 0.3, 0.05), (8000, 0.3, 0.05), (4000, 0.1, 0.08)):
        reps = 3000
        stats = []
        for _ in range(reps):
            g = rng.binomial(2, p, n).astype(float)
            y = beta * g + rng.normal(0, 1.0, n)
            gc = g - g.mean()
            b = float(gc @ (y - y.mean()) / (gc @ gc))
            resid = y - y.mean() - b * gc
            se = math.sqrt(float(resid @ resid) / (n - 2) / float(gc @ gc))
            stats.append((b / se) ** 2)
        obs = float(np.mean(stats)) - 1.0
        cells.append(dict(design="n=%d p=%.1f b=%.2f" % (n, p, beta),
                          lean=n * beta ** 2 * (2 * p * (1 - p)), truth=obs,
                          sem=float(np.std(stats) / math.sqrt(reps))))
    record("gwasNCP", "SelectionArchitecture.lean",
           "n * beta^2 * 2 p (1 - p)", cells,
           regime="chi-square noncentrality of the Wald statistic; the same "
                  "body as AncestrySpecificPower.ncp under a second name")


def test_ibd_flow_step_dgp():
    """fstDriftFlowStep = F + (1-F)/(2Ne) - 2(mig+mu)F."""
    rng = np.random.default_rng(12301)
    cells = []
    for Ne, mig, mu in ((200, 0.002, 0.0), (200, 0.001, 0.001), (500, 0.004, 0.0)):
        n_loci, reps = 4000, 300
        p0 = rng.uniform(0.1, 0.9, n_loci)
        two_n = int(2 * Ne)
        rate = mig + mu
        p = np.tile(p0, (reps, 1))
        for _ in range(30):
            p = rng.binomial(two_n, p) / two_n
            p = (1 - rate) * p + rate * p0
        H_anc = float((2 * p0 * (1 - p0)).mean())
        F0 = 1 - float((2 * p * (1 - p)).mean()) / H_anc
        p1 = rng.binomial(two_n, p) / two_n
        p1 = (1 - rate) * p1 + rate * p0
        F1 = 1 - float((2 * p1 * (1 - p1)).mean()) / H_anc
        cells.append(dict(design="Ne=%d mig=%.3f mu=%.3f" % (Ne, mig, mu),
                          lean=F0 + (1 - F0) / (2 * Ne) - 2 * rate * F0,
                          truth=F1, sem=abs(F1) * 0.004 + 1e-6))
    record("fstDriftFlowStep", "DGP.lean",
           "F + (1 - F)/(2*Ne) - 2*(mig + mu)*F", cells,
           regime="one generation of drift with flow from a fixed source pool")


def main():
    for fn in (test_drift_variance_family, test_effect_variance_recurrence,
               test_ols_variance, test_gwas_ncp_fork, test_ibd_flow_step_dgp):
        try:
            fn()
        except Exception:
            import traceback
            traceback.print_exc()
    json.dump(RESULTS, open("battery_bulk3_results.json", "w"), indent=1,
              default=str)
    print("\n\n================ SUMMARY ================")
    for r in RESULTS:
        w = r.get("worst", {})
        print("%-12s %-46s worst %9.2f sems, %7.2f%% rel"
              % (r["verdict"], r["name"], w.get("sems_off", float("nan")),
                 100 * w.get("rel_err", float("nan"))))


if __name__ == "__main__":
    main()
