/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.BanachEulerExponential
import Descent.Portability.ConvexOrderCoupling
import Mathlib.Analysis.Matrix
import Mathlib.Analysis.Normed.Module.FiniteDimension

assert_below Descent.Decision Descent.Program

/-!
# Towards the continuous-time form of the dynamic convex-order theorem

Two of the three ingredients of the continuous-time form of DC Theorem 3.1 / PL Theorem 5.3
for Markov admissible generators.

`exp_mulVec_le_of_euler` is the limit bridge: matrix evaluation against a fixed vector at a
fixed coordinate is linear, hence continuous in finite dimension, so an inequality between
the Euler approximants of two finite-state generators passes to the semigroups they
generate, via the Euler limit of `Descent.Portability.BanachEulerExponential`.

`nearestDriftMatrix` realizes the nearest-drift generator `L_*` of DC (3.4) / PL (5.8) as a
matrix on the count grid `{0, …, n}`, and `nearestDriftMatrix_mulVec_le` is DC Lemma 3.4 for
Markov generators: among all finite-state generators with nonnegative off-diagonal rates,
rows summing to zero, and the count drift forced by the coordinate-rate constraints,
`L_*` acts most negatively on every grid-convex report.

`exp_nearestDriftMatrix_mulVec_le` is the continuous-time theorem itself: for every `t ≥ 0`
the semigroup generated by `L_*` reports no more than the semigroup generated by any
admissible `L`, on every grid-convex report. The route is the one the skeleton supplies --
grid convexity survives one Euler step of `L_*` (`gridEmbed_step_gridConvex`, transported
from `ConvexOrderCoupling.driftStep_gridConvex`), a short Euler step of `L` is entrywise
nonnegative hence monotone, so the Euler approximants are ordered at every `m`
(`euler_iterate_le`), and the bridge passes that order to the limit at `τ = t/m`.

**Scope.** This covers MARKOV admissible generators. History-dependent couplings are not
matrices and are not covered; for those the corpus statement remains the discrete skeleton
`ConvexOrderCoupling.pathExp_nearestDrift_le`, which is proved for kernels indexed by the
entire past. The closed forms of DC Corollary 3.5 and DC (4.6) as rows of `exp (t L_*)` are
not proved here either; they need uniqueness of the linear ODE solution.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.ContinuousTurnoverSemigroup

open scoped Matrix.Norms.Operator

noncomputable section

/-- Evaluating a matrix against a fixed vector at a fixed coordinate is linear. -/
def mulVecEntry (N : ℕ) (v : Fin N → ℝ) (j : Fin N) :
    Matrix (Fin N) (Fin N) ℝ →ₗ[ℝ] ℝ where
  toFun M := M.mulVec v j
  map_add' M M' := by simp [Matrix.add_mulVec]
  map_smul' c M := by simp [Matrix.smul_mulVec_assoc]

/-- **Euler limits transfer a pointwise inequality to the generated semigroups.** -/
theorem exp_mulVec_le_of_euler {N : ℕ} (A B : Matrix (Fin N) (Fin N) ℝ) (v : Fin N → ℝ)
    (j : Fin N)
    (h : ∀ᶠ m : ℕ in Filter.atTop, ((1 + (m : ℝ)⁻¹ • A) ^ m).mulVec v j
      ≤ ((1 + (m : ℝ)⁻¹ • B) ^ m).mulVec v j) :
    (NormedSpace.exp ℝ A).mulVec v j ≤ (NormedSpace.exp ℝ B).mulVec v j := by
  have hcont : Continuous (mulVecEntry N v j) :=
    (mulVecEntry N v j).continuous_of_finiteDimensional
  have hA := (hcont.tendsto (NormedSpace.exp ℝ A)).comp
    (BanachEulerExponential.euler_tends_exp A)
  have hB := (hcont.tendsto (NormedSpace.exp ℝ B)).comp
    (BanachEulerExponential.euler_tends_exp B)
  exact le_of_tendsto_of_tendsto hA hB h


/-! ## The nearest-drift generator as a finite matrix -/

/-- A count vector embedded in `ℤ → ℝ` by clamping outside the grid.  The clamped values
are always multiplied by a vanishing rate, so the choice of extension is immaterial. -/
def gridEmbed (n : ℕ) (v : Fin (n + 1) → ℝ) : ℤ → ℝ :=
  fun k ↦ v ⟨min k.toNat n, by omega⟩

/-- The clamped successor on the count grid. -/
def gridSucc (n : ℕ) (k : Fin (n + 1)) : Fin (n + 1) := ⟨min ((k : ℕ) + 1) n, by omega⟩

/-- The truncated predecessor on the count grid. -/
def gridPred (n : ℕ) (k : Fin (n + 1)) : Fin (n + 1) :=
  ⟨(k : ℕ) - 1, by have := k.isLt; omega⟩

/-- The embedding restores the vector on the grid. -/
theorem gridEmbed_coe (n : ℕ) (v : Fin (n + 1) → ℝ) (k : Fin (n + 1)) :
    gridEmbed n v ((k : ℕ) : ℤ) = v k := by
  have hk := k.isLt
  have h : (⟨min (((k : ℕ) : ℤ)).toNat n, by omega⟩ : Fin (n + 1)) = k := by
    apply Fin.ext
    simp only [Int.toNat_natCast]
    omega
  simp only [gridEmbed]
  rw [h]

/-- The embedding one step up the grid. -/
theorem gridEmbed_succ (n : ℕ) (v : Fin (n + 1) → ℝ) (k : Fin (n + 1)) :
    gridEmbed n v (((k : ℕ) : ℤ) + 1) = v (gridSucc n k) := by
  have hk := k.isLt
  have h : (⟨min ((((k : ℕ) : ℤ) + 1)).toNat n, by omega⟩ : Fin (n + 1)) = gridSucc n k := by
    apply Fin.ext
    simp only [gridSucc]
    omega
  simp only [gridEmbed]
  rw [h]

/-- The embedding one step down the grid. -/
theorem gridEmbed_pred (n : ℕ) (v : Fin (n + 1) → ℝ) (k : Fin (n + 1)) :
    gridEmbed n v (((k : ℕ) : ℤ) - 1) = v (gridPred n k) := by
  have hk := k.isLt
  have h : (⟨min ((((k : ℕ) : ℤ) - 1)).toNat n, by omega⟩ : Fin (n + 1)) = gridPred n k := by
    apply Fin.ext
    simp only [gridPred]
    omega
  simp only [gridEmbed]
  rw [h]

/-- The nearest-drift generator `L_*` of DC (3.4) / PL (5.8) as a matrix on the count grid.
The clamped successor and predecessor are harmless because the outward rate vanishes at
each endpoint. -/
def nearestDriftMatrix (n : ℕ) (α β : ℝ) : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
  Matrix.of fun k j ↦
    ConvexOrderCoupling.upRate n α β ((k : ℕ) : ℤ)
        * ((if j = gridSucc n k then (1 : ℝ) else 0) - (if j = k then (1 : ℝ) else 0))
      + ConvexOrderCoupling.downRate n α β ((k : ℕ) : ℤ)
        * ((if j = gridPred n k then (1 : ℝ) else 0) - (if j = k then (1 : ℝ) else 0))

/-- The matrix acts on count vectors exactly as the nearest-drift generator acts on their
embeddings. -/
theorem nearestDriftMatrix_mulVec (n : ℕ) (α β : ℝ) (v : Fin (n + 1) → ℝ) (k : Fin (n + 1)) :
    (nearestDriftMatrix n α β).mulVec v k
      = ConvexOrderCoupling.nearestDriftGen n α β (gridEmbed n v) ((k : ℕ) : ℤ) := by
  have hsum : ∀ c : Fin (n + 1),
      ∑ j : Fin (n + 1), (if j = c then (1 : ℝ) else 0) * v j = v c := by
    intro c
    simp only [ite_mul, one_mul, zero_mul]
    rw [Finset.sum_ite_eq' Finset.univ c v, if_pos (Finset.mem_univ c)]
  have hpt : ∀ j : Fin (n + 1), nearestDriftMatrix n α β k j * v j
      = ConvexOrderCoupling.upRate n α β ((k : ℕ) : ℤ)
          * ((if j = gridSucc n k then (1 : ℝ) else 0) * v j
            - (if j = k then (1 : ℝ) else 0) * v j)
        + ConvexOrderCoupling.downRate n α β ((k : ℕ) : ℤ)
          * ((if j = gridPred n k then (1 : ℝ) else 0) * v j
            - (if j = k then (1 : ℝ) else 0) * v j) := by
    intro j
    simp only [nearestDriftMatrix, Matrix.of_apply]
    ring
  show ∑ j : Fin (n + 1), nearestDriftMatrix n α β k j * v j = _
  rw [Finset.sum_congr rfl fun j _ ↦ hpt j, Finset.sum_add_distrib, ← Finset.mul_sum,
    ← Finset.mul_sum, Finset.sum_sub_distrib, Finset.sum_sub_distrib]
  simp only [hsum]
  simp only [ConvexOrderCoupling.nearestDriftGen, gridEmbed_succ, gridEmbed_pred, gridEmbed_coe]

/-- **DC Lemma 3.4 for Markov generators.**  Among all finite-state generators whose
off-diagonal rates are nonnegative, whose rows sum to zero, and whose count drift is the one
forced by the coordinate-rate constraints DC (3.2) / PL (5.7), the nearest-drift generator
acts most negatively on every grid-convex report.  No structure of the jumps is assumed. -/
theorem nearestDriftMatrix_mulVec_le (n : ℕ) (α β : ℝ) (hα : 0 ≤ α) (hβ : 0 ≤ β)
    (L : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ) (hoff : ∀ k j, j ≠ k → 0 ≤ L k j)
    (hrow : ∀ k, ∑ j, L k j = 0)
    (hdrift : ∀ k : Fin (n + 1), ∑ j, L k j * (((j : ℕ) : ℝ) - ((k : ℕ) : ℝ))
      = ConvexOrderCoupling.countDrift n α β ((k : ℕ) : ℤ))
    (v : Fin (n + 1) → ℝ)
    (hv : ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n v (j - 1) - 2 * gridEmbed n v j + gridEmbed n v (j + 1))
    (k : Fin (n + 1)) :
    (nearestDriftMatrix n α β).mulVec v k ≤ L.mulVec v k := by
  have hk := k.isLt
  have hgen := ConvexOrderCoupling.nearestDrift_generator_le n α β 1 hα hβ (gridEmbed n v) hv
    ((k : ℕ) : ℤ) (by positivity) (by omega)
    (fun j : Fin (n + 1) ↦ if j = k then (0 : ℝ) else L k j)
    (fun j ↦ by
      show (0 : ℝ) ≤ if j = k then (0 : ℝ) else L k j
      by_cases h : j = k
      · simp [h]
      · rw [if_neg h]
        exact hoff k j h)
    (fun j : Fin (n + 1) ↦ ((j : ℕ) : ℤ) - ((k : ℕ) : ℤ))
    (fun j ↦ by
      have := j.isLt
      show (0 : ℤ) ≤ ((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ))
      omega)
    (fun j ↦ by
      have := j.isLt
      show ((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ)) ≤ (n : ℤ)
      omega)
    (by
      have hall : ∀ j : Fin (n + 1),
          (if j = k then (0 : ℝ) else L k j)
              * (((((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ)) : ℤ) : ℝ)
                - (((k : ℕ) : ℤ) : ℝ))
            = L k j * (((j : ℕ) : ℝ) - ((k : ℕ) : ℝ)) := by
        intro j
        by_cases h : j = k
        · rw [if_pos h, h]
          push_cast
          ring
        · rw [if_neg h]
          push_cast
          ring
      rw [Finset.sum_congr rfl fun j _ ↦ hall j, hdrift k]
      ring)
  have hrhs : ∑ j : Fin (n + 1), (if j = k then (0 : ℝ) else L k j)
        * (gridEmbed n v (((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ)))
          - gridEmbed n v ((k : ℕ) : ℤ))
      = L.mulVec v k := by
    have hpt : ∀ j : Fin (n + 1), (if j = k then (0 : ℝ) else L k j)
          * (gridEmbed n v (((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ)))
            - gridEmbed n v ((k : ℕ) : ℤ))
        = L k j * v j - L k j * v k := by
      intro j
      have hidx : ((k : ℕ) : ℤ) + (((j : ℕ) : ℤ) - ((k : ℕ) : ℤ)) = ((j : ℕ) : ℤ) := by ring
      rw [hidx, gridEmbed_coe, gridEmbed_coe]
      by_cases h : j = k
      · rw [if_pos h, h]
        ring
      · rw [if_neg h]
        ring
    rw [Finset.sum_congr rfl fun j _ ↦ hpt j, Finset.sum_sub_distrib, ← Finset.sum_mul, hrow k]
    show (∑ j : Fin (n + 1), L k j * v j) - 0 * v k = ∑ j : Fin (n + 1), L k j * v j
    ring
  rw [nearestDriftMatrix_mulVec, ← hrhs]
  linarith [hgen]

/-! ## The Euler step and its iterates -/

/-- One Euler step acts as the identity plus `τ` times the generator. -/
theorem step_mulVec_eq (n : ℕ) (τ : ℝ) (M : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ)
    (u : Fin (n + 1) → ℝ) (k : Fin (n + 1)) :
    (1 + τ • M).mulVec u k = u k + τ * M.mulVec u k := by
  rw [Matrix.add_mulVec, Matrix.one_mulVec, Matrix.smul_mulVec]
  simp

/-- The Euler step of the nearest-drift matrix is the skeleton step of
`Descent.Portability.ConvexOrderCoupling` on the embedded vector. -/
theorem gridEmbed_step (n : ℕ) (α β τ : ℝ) (v : Fin (n + 1) → ℝ) (j : ℤ)
    (hj0 : 0 ≤ j) (hjn : j ≤ (n : ℤ)) :
    gridEmbed n ((1 + τ • nearestDriftMatrix n α β).mulVec v) j
      = ConvexOrderCoupling.driftStep n α β τ (gridEmbed n v) j := by
  obtain ⟨k, hk⟩ : ∃ k : Fin (n + 1), ((k : ℕ) : ℤ) = j :=
    ⟨⟨j.toNat, by omega⟩, by
      show ((j.toNat : ℕ) : ℤ) = j
      omega⟩
  subst hk
  rw [gridEmbed_coe, step_mulVec_eq, nearestDriftMatrix_mulVec,
    ConvexOrderCoupling.driftStep, gridEmbed_coe]

/-- Grid convexity survives one Euler step of the nearest-drift matrix. -/
theorem gridEmbed_step_gridConvex (n : ℕ) (α β τ : ℝ) (hα : 0 ≤ α) (hβ : 0 ≤ β) (hτ : 0 ≤ τ)
    (hshort : τ * (2 * (n : ℝ) * (α + β)) ≤ 1) (v : Fin (n + 1) → ℝ)
    (hv : ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n v (j - 1) - 2 * gridEmbed n v j + gridEmbed n v (j + 1))
    (j : ℤ) (hj1 : 1 ≤ j) (hjn : j + 1 ≤ (n : ℤ)) :
    0 ≤ gridEmbed n ((1 + τ • nearestDriftMatrix n α β).mulVec v) (j - 1)
      - 2 * gridEmbed n ((1 + τ • nearestDriftMatrix n α β).mulVec v) j
      + gridEmbed n ((1 + τ • nearestDriftMatrix n α β).mulVec v) (j + 1) := by
  rw [gridEmbed_step n α β τ v (j - 1) (by omega) (by omega),
    gridEmbed_step n α β τ v j (by omega) (by omega),
    gridEmbed_step n α β τ v (j + 1) (by omega) (by omega)]
  exact ConvexOrderCoupling.driftStep_gridConvex n α β τ hα hβ hτ hshort (gridEmbed n v) hv j
    hj1 hjn

/-- A matrix power acts by iterating the matrix. -/
theorem pow_mulVec_succ {N : ℕ} (A : Matrix (Fin N) (Fin N) ℝ) (v : Fin N → ℝ) (m : ℕ) :
    (A ^ (m + 1)).mulVec v = A.mulVec ((A ^ m).mulVec v) := by
  rw [pow_succ']
  simp [Matrix.mulVec_mulVec]

/-- Every iterate of the Euler step of the nearest-drift matrix stays grid convex. -/
theorem gridEmbed_pow_gridConvex (n : ℕ) (α β τ : ℝ) (hα : 0 ≤ α) (hβ : 0 ≤ β) (hτ : 0 ≤ τ)
    (hshort : τ * (2 * (n : ℝ) * (α + β)) ≤ 1) (v : Fin (n + 1) → ℝ)
    (hv : ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n v (j - 1) - 2 * gridEmbed n v j + gridEmbed n v (j + 1)) (m : ℕ) :
    ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v) (j - 1)
        - 2 * gridEmbed n (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v) j
        + gridEmbed n (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v) (j + 1) := by
  induction m with
  | zero => simpa using hv
  | succ m ih =>
    intro j hj1 hjn
    rw [pow_mulVec_succ]
    exact gridEmbed_step_gridConvex n α β τ hα hβ hτ hshort _ ih j hj1 hjn

/-- A short Euler step of an admissible generator has nonnegative entries, so it is
monotone on vectors. -/
theorem step_mulVec_mono (n : ℕ) (τ : ℝ) (hτ : 0 ≤ τ)
    (L : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ) (hoff : ∀ k j, j ≠ k → 0 ≤ L k j)
    (hdiag : ∀ k, 0 ≤ 1 + τ * L k k) (u w : Fin (n + 1) → ℝ) (huw : ∀ j, u j ≤ w j)
    (k : Fin (n + 1)) :
    (1 + τ • L).mulVec u k ≤ (1 + τ • L).mulVec w k := by
  have hentry : ∀ j, 0 ≤ (1 + τ • L) k j := by
    intro j
    have h1 : (1 + τ • L) k j = (if k = j then (1 : ℝ) else 0) + τ * L k j := by
      simp [Matrix.one_apply]
    rw [h1]
    by_cases h : k = j
    · rw [if_pos h, ← h]
      exact hdiag k
    · rw [if_neg h, zero_add]
      exact mul_nonneg hτ (hoff k j fun hc ↦ h hc.symm)
  show ∑ j, (1 + τ • L) k j * u j ≤ ∑ j, (1 + τ • L) k j * w j
  exact Finset.sum_le_sum fun j _ ↦ mul_le_mul_of_nonneg_left (huw j) (hentry j)

/-- **The Euler approximants are ordered.**  For a short step, every iterate of the
nearest-drift Euler step is below the corresponding iterate for any admissible generator. -/
theorem euler_iterate_le (n : ℕ) (α β τ : ℝ) (hα : 0 ≤ α) (hβ : 0 ≤ β) (hτ : 0 ≤ τ)
    (hshort : τ * (2 * (n : ℝ) * (α + β)) ≤ 1)
    (L : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ) (hoff : ∀ k j, j ≠ k → 0 ≤ L k j)
    (hrow : ∀ k, ∑ j, L k j = 0)
    (hdrift : ∀ k : Fin (n + 1), ∑ j, L k j * (((j : ℕ) : ℝ) - ((k : ℕ) : ℝ))
      = ConvexOrderCoupling.countDrift n α β ((k : ℕ) : ℤ))
    (hdiag : ∀ k, 0 ≤ 1 + τ * L k k) (v : Fin (n + 1) → ℝ)
    (hv : ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n v (j - 1) - 2 * gridEmbed n v j + gridEmbed n v (j + 1)) (m : ℕ) :
    ∀ k : Fin (n + 1), ((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v k
      ≤ ((1 + τ • L) ^ m).mulVec v k := by
  induction m with
  | zero => intro k; simp
  | succ m ih =>
    intro k
    rw [pow_mulVec_succ, pow_mulVec_succ]
    have hstar : (1 + τ • nearestDriftMatrix n α β).mulVec
          (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v) k
        ≤ (1 + τ • L).mulVec (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v) k := by
      have hgen := nearestDriftMatrix_mulVec_le n α β hα hβ L hoff hrow hdrift
        (((1 + τ • nearestDriftMatrix n α β) ^ m).mulVec v)
        (gridEmbed_pow_gridConvex n α β τ hα hβ hτ hshort v hv m) k
      have hscaled := mul_le_mul_of_nonneg_left hgen hτ
      rw [step_mulVec_eq, step_mulVec_eq]
      linarith
    exact le_trans hstar (step_mulVec_mono n τ hτ L hoff hdiag _ _ ih k)

/-! ## The continuous-time comparison -/

/-- An admissible generator has nonpositive diagonal, so short Euler steps are
substochastic. -/
theorem diag_nonpos (n : ℕ) (L : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ)
    (hoff : ∀ k j, j ≠ k → 0 ≤ L k j) (hrow : ∀ k, ∑ j, L k j = 0) (k : Fin (n + 1)) :
    L k k ≤ 0 := by
  have hsplit : L k k + ∑ j ∈ Finset.univ.erase k, L k j = ∑ j, L k j :=
    Finset.add_sum_erase Finset.univ (fun j ↦ L k j) (Finset.mem_univ k)
  have hnn : 0 ≤ ∑ j ∈ Finset.univ.erase k, L k j :=
    Finset.sum_nonneg fun j hj ↦ hoff k j (Finset.ne_of_mem_erase hj)
  rw [hrow k] at hsplit
  linarith

/-- **The continuous-time dynamic convex-order theorem for Markov admissible generators**,
DC Theorem 3.1 / PL Theorem 5.3.

For every finite-state generator `L` on the count grid with nonnegative off-diagonal rates,
rows summing to zero, and the count drift forced by the coordinate-rate constraints
DC (3.2) / PL (5.7), and for every grid-convex report, the semigroup generated by the
nearest-drift generator reports no more than the semigroup generated by `L`, at every
horizon `t ≥ 0`.

The proof is the Euler route: for a short step the skeleton comparison of
`Descent.Portability.ConvexOrderCoupling` orders the two Euler approximants, and
`exp_mulVec_le_of_euler` passes the order to the limit.  History-dependent couplings are
not covered here; for those the corpus statement remains the discrete skeleton
`ConvexOrderCoupling.pathExp_nearestDrift_le`. -/
theorem exp_nearestDriftMatrix_mulVec_le (n : ℕ) (α β t : ℝ) (hα : 0 ≤ α) (hβ : 0 ≤ β)
    (ht : 0 ≤ t) (L : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ)
    (hoff : ∀ k j, j ≠ k → 0 ≤ L k j) (hrow : ∀ k, ∑ j, L k j = 0)
    (hdrift : ∀ k : Fin (n + 1), ∑ j, L k j * (((j : ℕ) : ℝ) - ((k : ℕ) : ℝ))
      = ConvexOrderCoupling.countDrift n α β ((k : ℕ) : ℤ))
    (v : Fin (n + 1) → ℝ)
    (hv : ∀ j : ℤ, 1 ≤ j → j + 1 ≤ (n : ℤ) →
      0 ≤ gridEmbed n v (j - 1) - 2 * gridEmbed n v j + gridEmbed n v (j + 1))
    (k : Fin (n + 1)) :
    (NormedSpace.exp ℝ (t • nearestDriftMatrix n α β)).mulVec v k
      ≤ (NormedSpace.exp ℝ (t • L)).mulVec v k := by
  refine exp_mulVec_le_of_euler (t • nearestDriftMatrix n α β) (t • L) v k ?_
  rw [Filter.eventually_atTop]
  have hC0 : (0 : ℝ) ≤ 2 * (n : ℝ) * (α + β) :=
    mul_nonneg (by positivity) (by linarith)
  have hSnn : ∀ k' : Fin (n + 1), (0 : ℝ) ≤ -(L k' k') := by
    intro k'
    have := diag_nonpos n L hoff hrow k'
    linarith
  have hS0 : (0 : ℝ) ≤ ∑ k' : Fin (n + 1), -(L k' k') :=
    Finset.sum_nonneg fun k' _ ↦ hSnn k'
  obtain ⟨M, hM⟩ := exists_nat_gt
    (max (t * (2 * (n : ℝ) * (α + β))) (t * ∑ k' : Fin (n + 1), -(L k' k')))
  refine ⟨M, fun m hm ↦ ?_⟩
  have hmR : max (t * (2 * (n : ℝ) * (α + β))) (t * ∑ k' : Fin (n + 1), -(L k' k'))
      < (m : ℝ) := lt_of_lt_of_le hM (by exact_mod_cast hm)
  have hmax0 : (0 : ℝ)
      ≤ max (t * (2 * (n : ℝ) * (α + β))) (t * ∑ k' : Fin (n + 1), -(L k' k')) :=
    le_max_of_le_left (mul_nonneg ht hC0)
  have hm0 : (0 : ℝ) < (m : ℝ) := lt_of_le_of_lt hmax0 hmR
  have hτ0 : (0 : ℝ) ≤ (m : ℝ)⁻¹ * t := mul_nonneg (by positivity) ht
  have hsmulS : (m : ℝ)⁻¹ • (t • nearestDriftMatrix n α β)
      = ((m : ℝ)⁻¹ * t) • nearestDriftMatrix n α β := smul_smul _ _ _
  have hsmulL : (m : ℝ)⁻¹ • (t • L) = ((m : ℝ)⁻¹ * t) • L := smul_smul _ _ _
  rw [hsmulS, hsmulL]
  refine euler_iterate_le n α β ((m : ℝ)⁻¹ * t) hα hβ hτ0 ?_ L hoff hrow hdrift ?_ v hv m k
  · have hlt : t * (2 * (n : ℝ) * (α + β)) < (m : ℝ) :=
      lt_of_le_of_lt (le_max_left _ _) hmR
    have heq : (m : ℝ)⁻¹ * t * (2 * (n : ℝ) * (α + β))
        = (t * (2 * (n : ℝ) * (α + β))) / (m : ℝ) := by
      rw [div_eq_inv_mul]
      ring
    rw [heq, div_le_one hm0]
    linarith
  · intro k'
    have hle : -(L k' k') ≤ ∑ k'' : Fin (n + 1), -(L k'' k'') :=
      Finset.single_le_sum (f := fun k'' ↦ -(L k'' k'')) (fun k'' _ ↦ hSnn k'')
        (Finset.mem_univ k')
    have hlt : t * (∑ k'' : Fin (n + 1), -(L k'' k'')) < (m : ℝ) :=
      lt_of_le_of_lt (le_max_right _ _) hmR
    have hstep : (m : ℝ)⁻¹ * t * (-(L k' k'))
        ≤ (t * (∑ k'' : Fin (n + 1), -(L k'' k''))) / (m : ℝ) := by
      rw [div_eq_inv_mul]
      have h2 := mul_le_mul_of_nonneg_left hle hτ0
      linarith
    have hfin : (t * (∑ k'' : Fin (n + 1), -(L k'' k''))) / (m : ℝ) < 1 :=
      (div_lt_one hm0).mpr hlt
    have hkey : (m : ℝ)⁻¹ * t * (-(L k' k')) < 1 := lt_of_le_of_lt hstep hfin
    linarith

/-! ## Eigenvectors of a generator are eigenvectors of its semigroup -/

/-- Scaling commutes with a matrix acting on a vector. -/
theorem mulVec_smul_comm {N : ℕ} (M : Matrix (Fin N) (Fin N) ℝ) (r : ℝ) (u : Fin N → ℝ) :
    M.mulVec (r • u) = r • M.mulVec u := by
  funext i
  simp only [Matrix.mulVec, dotProduct, Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
  exact Finset.sum_congr rfl fun l _ ↦ by ring

/-- Euler approximants act on an eigenvector by the scalar Euler approximant. -/
theorem euler_pow_mulVec_eigen {N : ℕ} (A : Matrix (Fin N) (Fin N) ℝ) (w : Fin N → ℝ)
    (c τ : ℝ) (hAw : A.mulVec w = c • w) (m : ℕ) :
    ((1 + τ • A) ^ m).mulVec w = ((1 + τ * c) ^ m) • w := by
  induction m with
  | zero => simp
  | succ m ih =>
    have h2 : (1 + τ • A).mulVec w = (1 + τ * c) • w := by
      rw [Matrix.add_mulVec, Matrix.one_mulVec, Matrix.smul_mulVec, hAw, smul_smul, add_smul,
        one_smul]
    rw [pow_mulVec_succ, ih, mulVec_smul_comm, h2, smul_smul, pow_succ]

/-- **An eigenvector of a generator is an eigenvector of the semigroup it generates**, with
eigenvalue exponentiated.  Proved through the Euler limit, not through an ODE. -/
theorem exp_mulVec_eigen {N : ℕ} (A : Matrix (Fin N) (Fin N) ℝ) (w : Fin N → ℝ) (c t : ℝ)
    (hAw : A.mulVec w = c • w) (j : Fin N) :
    (NormedSpace.exp ℝ (t • A)).mulVec w j = NormedSpace.exp ℝ (t * c) * w j := by
  have hcont : Continuous (mulVecEntry N w j) :=
    (mulVecEntry N w j).continuous_of_finiteDimensional
  have hA := (hcont.tendsto (NormedSpace.exp ℝ (t • A))).comp
    (BanachEulerExponential.euler_tends_exp (t • A))
  have hB : Filter.Tendsto (fun m : ℕ ↦ ((1 + (m : ℝ)⁻¹ • (t * c)) ^ m) * w j) Filter.atTop
      (nhds (NormedSpace.exp ℝ (t * c) * w j)) :=
    (BanachEulerExponential.euler_tends_exp (t * c)).mul_const (w j)
  have heq : ∀ m : ℕ, (mulVecEntry N w j) ((1 + (m : ℝ)⁻¹ • (t • A)) ^ m)
      = ((1 + (m : ℝ)⁻¹ • (t * c)) ^ m) * w j := by
    intro m
    show (((1 + (m : ℝ)⁻¹ • (t • A)) ^ m).mulVec w) j = _
    rw [show (m : ℝ)⁻¹ • (t • A) = ((m : ℝ)⁻¹ * t) • A from smul_smul _ _ _,
      euler_pow_mulVec_eigen A w c ((m : ℝ)⁻¹ * t) hAw]
    simp only [Pi.smul_apply, smul_eq_mul]
    ring
  exact tendsto_nhds_unique (Filter.Tendsto.congr heq hA) hB

/-! ## The linear pure-death chain of DC Corollary 3.5 -/

/-- The linear pure-death generator of DC Corollary 3.5: from `j` surviving coordinates the
count falls to `j - 1` at rate `γ j`, and `0` is absorbing. -/
def linearDeathMatrix (m : ℕ) (gamma : ℝ) : Matrix (Fin (m + 1)) (Fin (m + 1)) ℝ :=
  Matrix.of fun j i ↦ gamma * ((j : ℕ) : ℝ)
    * ((if i = gridPred m j then (1 : ℝ) else 0) - (if i = j then (1 : ℝ) else 0))

/-- The pure-death generator acts by the scaled down-difference. -/
theorem linearDeathMatrix_mulVec (m : ℕ) (gamma : ℝ) (v : Fin (m + 1) → ℝ)
    (j : Fin (m + 1)) :
    (linearDeathMatrix m gamma).mulVec v j
      = gamma * ((j : ℕ) : ℝ) * (v (gridPred m j) - v j) := by
  have hsum : ∀ c : Fin (m + 1),
      ∑ i : Fin (m + 1), (if i = c then (1 : ℝ) else 0) * v i = v c := by
    intro c
    simp only [ite_mul, one_mul, zero_mul]
    rw [Finset.sum_ite_eq' Finset.univ c v, if_pos (Finset.mem_univ c)]
  have hpt : ∀ i : Fin (m + 1), linearDeathMatrix m gamma j i * v i
      = gamma * ((j : ℕ) : ℝ) * ((if i = gridPred m j then (1 : ℝ) else 0) * v i
        - (if i = j then (1 : ℝ) else 0) * v i) := by
    intro i
    simp only [linearDeathMatrix, Matrix.of_apply]
    ring
  show ∑ i : Fin (m + 1), linearDeathMatrix m gamma j i * v i = _
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, ← Finset.mul_sum, Finset.sum_sub_distrib]
  simp only [hsum]

/-- The count itself is an eigenvector of the pure-death generator, eigenvalue `-γ`. -/
theorem linearDeathMatrix_eigen_id (m : ℕ) (gamma : ℝ) :
    (linearDeathMatrix m gamma).mulVec (fun j ↦ ((j : ℕ) : ℝ))
      = (-gamma) • (fun j : Fin (m + 1) ↦ ((j : ℕ) : ℝ)) := by
  funext j
  rw [linearDeathMatrix_mulVec]
  simp only [Pi.smul_apply, smul_eq_mul]
  rcases Nat.eq_zero_or_pos (j : ℕ) with h | h
  · rw [h]
    simp
  · have hc : (((gridPred m j : Fin (m + 1)) : ℕ) : ℝ) = ((j : ℕ) : ℝ) - 1 := by
      show (((j : ℕ) - 1 : ℕ) : ℝ) = ((j : ℕ) : ℝ) - 1
      rw [Nat.cast_sub h]
      norm_num
    rw [hc]
    ring

/-- The falling square is an eigenvector of the pure-death generator, eigenvalue `-2γ`. -/
theorem linearDeathMatrix_eigen_quad (m : ℕ) (gamma : ℝ) :
    (linearDeathMatrix m gamma).mulVec (fun j ↦ ((j : ℕ) : ℝ) ^ 2 - ((j : ℕ) : ℝ))
      = (-(2 * gamma)) • (fun j : Fin (m + 1) ↦ ((j : ℕ) : ℝ) ^ 2 - ((j : ℕ) : ℝ)) := by
  funext j
  rw [linearDeathMatrix_mulVec]
  simp only [Pi.smul_apply, smul_eq_mul]
  rcases Nat.eq_zero_or_pos (j : ℕ) with h | h
  · rw [h]
    simp
  · have hc : (((gridPred m j : Fin (m + 1)) : ℕ) : ℝ) = ((j : ℕ) : ℝ) - 1 := by
      show (((j : ℕ) - 1 : ℕ) : ℝ) = ((j : ℕ) : ℝ) - 1
      rw [Nat.cast_sub h]
      norm_num
    rw [hc]
    ring

/-- **DC Corollary 3.5's report, in continuous time and in closed form.**  The exact value
of the squared count under the pure-death semigroup, from any starting state. -/
theorem exp_linearDeath_sq (m : ℕ) (gamma t : ℝ) (j : Fin (m + 1)) :
    (NormedSpace.exp ℝ (t • linearDeathMatrix m gamma)).mulVec
        (fun i ↦ ((i : ℕ) : ℝ) ^ 2) j
      = NormedSpace.exp ℝ (t * (-(2 * gamma))) * (((j : ℕ) : ℝ) ^ 2 - ((j : ℕ) : ℝ))
        + NormedSpace.exp ℝ (t * (-gamma)) * ((j : ℕ) : ℝ) := by
  have hsplit : (fun i : Fin (m + 1) ↦ ((i : ℕ) : ℝ) ^ 2)
      = (fun i : Fin (m + 1) ↦ ((i : ℕ) : ℝ) ^ 2 - ((i : ℕ) : ℝ))
        + (fun i : Fin (m + 1) ↦ ((i : ℕ) : ℝ)) := by
    funext i
    simp only [Pi.add_apply]
    ring
  rw [hsplit, Matrix.mulVec_add]
  simp only [Pi.add_apply]
  rw [exp_mulVec_eigen (linearDeathMatrix m gamma) _ _ t (linearDeathMatrix_eigen_quad m gamma) j,
    exp_mulVec_eigen (linearDeathMatrix m gamma) _ _ t (linearDeathMatrix_eigen_id m gamma) j]

/-- **PL (5.13) / DC (4.4), lower endpoint, in continuous time.**  Starting from the top
state `m`, the pure-death semigroup's normalized squared count is exactly
`(1 - 2/n) p² + (2/n) p` with `n = 2m` and `p = e^{-γt}` -- the same closed form that
`Descent.Portability.BinomialAggregateEnvelope.binomial_envelope_lower` evaluates on the
explicit binomial law, now as a value of the semigroup itself. -/
theorem exp_linearDeath_lower_endpoint (m : ℕ) (hm : 0 < m) (gamma t ν : ℝ) (hν : 0 ≤ ν) :
    (NormedSpace.exp ℝ (t • linearDeathMatrix m gamma)).mulVec
          (fun i ↦ ((i : ℕ) : ℝ) ^ 2) ⟨m, Nat.lt_succ_self m⟩ / ((m : ℝ) ^ 2 * (1 + ν))
      = ((1 - 2 / (2 * (m : ℝ))) * NormedSpace.exp ℝ (t * (-gamma)) ^ 2
          + (2 / (2 * (m : ℝ))) * NormedSpace.exp ℝ (t * (-gamma))) / (1 + ν) := by
  have hmne : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hm.ne'
  have hcne : (1 + ν) ≠ 0 := by
    intro h
    linarith
  have hsq : NormedSpace.exp ℝ (t * (-(2 * gamma)))
      = NormedSpace.exp ℝ (t * (-gamma)) ^ 2 := by
    rw [show t * (-(2 * gamma)) = t * (-gamma) + t * (-gamma) from by ring,
      NormedSpace.exp_add]
    ring
  have hval : (((⟨m, Nat.lt_succ_self m⟩ : Fin (m + 1)) : ℕ) : ℝ) = (m : ℝ) := rfl
  rw [exp_linearDeath_sq m gamma t ⟨m, Nat.lt_succ_self m⟩, hsq, hval]
  field_simp

end

end Descent.Portability.ContinuousTurnoverSemigroup
