/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.EndToEndScoreLaw
import Descent.Portability.PopulationAUC
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic

assert_below Descent.Decision Descent.Program

namespace Descent.Portability

open MeasureTheory

/-!
# Discrimination laws: within-deme, pooled, and administratively censored survival

The input is the per-deme score law produced by the demographic and P+T layers.  The pooled
law keeps the case and control mixture weights distinct: a high-prevalence deme contributes
more cases and a low-prevalence deme contributes more controls.  Its off-diagonal terms are
therefore genuine cross-deme comparisons, not averages of within-deme AUCs.
-/

/-! ## E1. Within-deme liability AUC -/

/-- The validated liability-threshold AUC chart evaluated at a deme's own explained variance
and prevalence.  In particular, a phenoB law supplies the prevalence generated by its upstream
liability mean rather than a prevalence entered at this stage. -/
noncomputable def DemeScoreLaw.withinAUC (law : DemeScoreLaw) : ℝ :=
  liabilityThresholdAUCFromExplainedR2 law.r2True law.prevalence

/-! ## E2. Pooled AUC as a case/control mixture -/

/-- Mean of the raw deployed score among cases in a deme.  The liability moments are for a
standardised score, hence the explicit rescaling by the marginal score standard deviation. -/
noncomputable def DemeScoreLaw.caseScoreMean (law : DemeScoreLaw) : ℝ :=
  law.scoreMean + Real.sqrt law.moments.scoreVariance * Real.sqrt law.r2True *
    liabilityCaseMean law.prevalence

/-- Mean of the raw deployed score among controls in a deme. -/
noncomputable def DemeScoreLaw.controlScoreMean (law : DemeScoreLaw) : ℝ :=
  law.scoreMean + Real.sqrt law.moments.scoreVariance * Real.sqrt law.r2True *
    liabilityControlMean law.prevalence

/-- Conditional raw-score variance among cases. -/
noncomputable def DemeScoreLaw.caseScoreVariance (law : DemeScoreLaw) : ℝ :=
  law.moments.scoreVariance * liabilityCaseVariance law.r2True law.prevalence

/-- Conditional raw-score variance among controls. -/
noncomputable def DemeScoreLaw.controlScoreVariance (law : DemeScoreLaw) : ℝ :=
  law.moments.scoreVariance * liabilityControlVariance law.r2True law.prevalence

/-- Off-diagonal Gaussian exceedance term: a case drawn from deme `caseDeme` outranks a
control drawn from deme `controlDeme`.  It includes differences in score location, scale,
explained variance, and liability threshold. -/
noncomputable def crossDemeCaseControlAUC
    (caseDeme controlDeme : DemeScoreLaw) : ℝ :=
  Foundations.Phi
    ((caseDeme.caseScoreMean - controlDeme.controlScoreMean) /
      Real.sqrt (caseDeme.caseScoreVariance + controlDeme.controlScoreVariance))

/-- The off-diagonal formula reduces to the established within-deme chart when a deme's raw
score is already standardised.  These are coordinate conditions, not biological assumptions. -/
theorem crossDemeCaseControlAUC_diagonal_standardized (law : DemeScoreLaw)
    (hmean : law.scoreMean = 0) (hvar : law.moments.scoreVariance = 1) :
    crossDemeCaseControlAUC law law = law.withinAUC := by
  simp only [crossDemeCaseControlAUC, DemeScoreLaw.caseScoreMean,
    DemeScoreLaw.controlScoreMean, DemeScoreLaw.caseScoreVariance,
    DemeScoreLaw.controlScoreVariance, DemeScoreLaw.withinAUC, hmean, hvar]
  norm_num
  ring_nf

/-- A finite population mixture.  `populationWeight` is the unconditional deme mass; its
normalisation is carried by the type so a pooled AUC cannot silently use cell counts. -/
structure DemeMixture (D : ℕ) where
  law : Fin D → DemeScoreLaw
  populationWeight : Fin D → ℝ
  weight_nonneg : ∀ d, 0 ≤ populationWeight d
  weight_sum_one : ∑ d, populationWeight d = 1

/-- Total case mass before conditioning on case status. -/
noncomputable def DemeMixture.caseMass {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ d, mix.populationWeight d * (mix.law d).prevalence

/-- Total control mass before conditioning on control status. -/
noncomputable def DemeMixture.controlMass {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ d, mix.populationWeight d * (1 - (mix.law d).prevalence)

/-- Deme weight conditional on drawing a case. -/
noncomputable def DemeMixture.caseWeight {D : ℕ} (mix : DemeMixture D) (d : Fin D) : ℝ :=
  mix.populationWeight d * (mix.law d).prevalence / mix.caseMass

/-- Deme weight conditional on drawing a control. -/
noncomputable def DemeMixture.controlWeight {D : ℕ} (mix : DemeMixture D) (d : Fin D) : ℝ :=
  mix.populationWeight d * (1 - (mix.law d).prevalence) / mix.controlMass

/-- E2: pooled population AUC.  Diagonal summands are E1; every off-diagonal summand is the
closed Gaussian case-control exceedance between two different demes. -/
noncomputable def DemeMixture.pooledAUC {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ i, ∑ j, mix.caseWeight i * mix.controlWeight j *
    crossDemeCaseControlAUC (mix.law i) (mix.law j)

/-- The pooled formula exposes its diagonal and off-diagonal pieces exactly. -/
theorem DemeMixture.pooledAUC_diagonal_offDiagonal {D : ℕ} (mix : DemeMixture D) :
    mix.pooledAUC =
      (∑ i, mix.caseWeight i * mix.controlWeight i *
        crossDemeCaseControlAUC (mix.law i) (mix.law i)) +
      ∑ i, ∑ j, if i = j then 0 else
        mix.caseWeight i * mix.controlWeight j *
          crossDemeCaseControlAUC (mix.law i) (mix.law j) := by
  classical
  unfold DemeMixture.pooledAUC
  rw [Finset.sum_add_distrib]
  congr 1
  · simp
  · apply Finset.sum_congr rfl
    intro i _
    rw [← Finset.sum_ite_irrel i]
    simp [Finset.sum_ite]

/-! ## E3. Harrell C under an administrative horizon -/

/-- The simulation-relevant proportional-hazards generator.  The baseline rate, score log
hazard ratio, and administrative horizon are explicit; no unrecorded censoring distribution
is introduced. -/
structure AdministrativePHGenerator where
  baselineRate : ℝ
  logHazardRatio : ℝ
  horizon : ℝ

/-- Individual event rate under the generator. -/
noncomputable def AdministrativePHGenerator.eventRate
    (g : AdministrativePHGenerator) (score : ℝ) : ℝ :=
  g.baselineRate * Real.exp (g.logHazardRatio * score)

/-- Exact probability that individual 1 fails before individual 2 and before the
administrative horizon, conditional on their scores.  It is the integral of
`lambda1 exp(-(lambda1+lambda2)t)` from zero to the horizon. -/
noncomputable def AdministrativePHGenerator.firstObserved
    (g : AdministrativePHGenerator) (score1 score2 : ℝ) : ℝ :=
  let lambda1 := g.eventRate score1
  let lambda2 := g.eventRate score2
  lambda1 / (lambda1 + lambda2) *
    (1 - Real.exp (-(lambda1 + lambda2) * g.horizon))

/-- A Gaussian marginal score law for the survival chart. -/
structure SurvivalScoreLaw where
  mean : ℝ
  variance : ℝ

/-- Gaussian score density in the raw score coordinate. -/
noncomputable def SurvivalScoreLaw.density (law : SurvivalScoreLaw) (score : ℝ) : ℝ :=
  Real.exp (-((score - law.mean) ^ 2) / (2 * law.variance)) /
    Real.sqrt (2 * Real.pi * law.variance)

/-- Comparable-pair mass under administrative censoring. -/
noncomputable def administrativeComparableMass
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : ℝ :=
  ∫ s1, ∫ s2,
    (g.firstObserved s1 s2 + g.firstObserved s2 s1) *
      law.density s1 * law.density s2

/-- Concordant comparable-pair mass.  Ties receive one half, matching population AUC and
Harrell's convention. -/
noncomputable def administrativeConcordantMass
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : ℝ :=
  ∫ s1, ∫ s2,
    ((if s1 > s2 then g.firstObserved s1 s2 else
       if s1 = s2 then (1 / 2) * g.firstObserved s1 s2 else 0) +
     (if s2 > s1 then g.firstObserved s2 s1 else
       if s2 = s1 then (1 / 2) * g.firstObserved s2 s1 else 0)) *
      law.density s1 * law.density s2

/-- E3: population Harrell C for the simulator's administrative-horizon construction. -/
noncomputable def administrativeHarrellC
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : ℝ :=
  administrativeConcordantMass g law / administrativeComparableMass g law

/-- At horizon zero there are no comparable event pairs; the zero returned by the ratio is
the named empty-comparison branch, not a chance-level C-index. -/
theorem AdministrativePHGenerator.firstObserved_zero_horizon
    (g : AdministrativePHGenerator) (s1 s2 : ℝ) (h : g.horizon = 0) :
    g.firstObserved s1 s2 = 0 := by
  simp [AdministrativePHGenerator.firstObserved, h]

/-- The conditional first-event law is invariant to a common shift of the scores when the
baseline rate is transformed by the reciprocal hazard multiplier.  This is an exact analytic
check of the survival chart, independent of simulation. -/
theorem firstObserved_common_shift (g : AdministrativePHGenerator) (c s1 s2 : ℝ) :
    ({ g with baselineRate := g.baselineRate * Real.exp (-g.logHazardRatio * c) }).firstObserved
        (s1 + c) (s2 + c) = g.firstObserved s1 s2 := by
  unfold AdministrativePHGenerator.firstObserved AdministrativePHGenerator.eventRate
  simp only [neg_mul, add_mul, Real.exp_add, Real.exp_neg]
  field_simp
  ring

end Descent.Portability
