/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.EndToEndScoreLaw
import Descent.Portability.PopulationAUC
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic

assert_below Descent.Decision Descent.Program

namespace Descent.Portability

open MeasureTheory

/-!
# Discrimination laws: within-deme, pooled, and administratively censored survival

The input is the per-deme score law produced by the demographic and P+T layers.  The pooled
law keeps the case and control mixture weights distinct: a high-prevalence deme contributes
more cases and a low-prevalence deme contributes more controls.  Its off-diagonal terms are
therefore genuine cross-deme comparisons, not averages of within-deme AUCs.
-/

/-! ## E1. Within-deme liability AUC -/

/-- The validated liability-threshold AUC chart evaluated at a deme's own explained variance
and prevalence.  In particular, a phenoB law supplies the prevalence generated by its upstream
liability mean rather than a prevalence entered at this stage. -/
noncomputable def DemeScoreLaw.liabilityWithinAUC (law : DemeScoreLaw) : ℝ :=
  liabilityThresholdAUCFromExplainedR2 law.r2True law.prevalence

/-! ## E2. Pooled AUC as a case/control mixture -/

/-- Mean of the raw deployed score among cases in a deme.  The liability moments are for a
standardised score, hence the explicit rescaling by the marginal score standard deviation. -/
noncomputable def DemeScoreLaw.caseScoreMean (law : DemeScoreLaw) : ℝ :=
  law.scoreMean + Real.sqrt law.moments.scoreVariance * Real.sqrt law.r2True *
    liabilityCaseMean law.prevalence

/-- Mean of the raw deployed score among controls in a deme. -/
noncomputable def DemeScoreLaw.controlScoreMean (law : DemeScoreLaw) : ℝ :=
  law.scoreMean + Real.sqrt law.moments.scoreVariance * Real.sqrt law.r2True *
    liabilityControlMean law.prevalence

/-- Conditional raw-score variance among cases. -/
noncomputable def DemeScoreLaw.caseScoreVariance (law : DemeScoreLaw) : ℝ :=
  law.moments.scoreVariance * liabilityCaseVariance law.r2True law.prevalence

/-- Conditional raw-score variance among controls. -/
noncomputable def DemeScoreLaw.controlScoreVariance (law : DemeScoreLaw) : ℝ :=
  law.moments.scoreVariance * liabilityControlVariance law.r2True law.prevalence

/-- Domain on which both conditional Gaussian score laws have positive variance. -/
structure LiabilityDiscriminationDomain (law : DemeScoreLaw) : Prop where
  caseVariance_pos : 0 < liabilityCaseVariance law.r2True law.prevalence
  controlVariance_pos : 0 < liabilityControlVariance law.r2True law.prevalence

/-- E1 on its typed domain. -/
noncomputable def DemeScoreLaw.withinAUC
    (law : DemeScoreLaw) (_ : LiabilityDiscriminationDomain law) : ℝ :=
  law.liabilityWithinAUC

/-- Off-diagonal Gaussian exceedance term: a case drawn from deme `caseDeme` outranks a
control drawn from deme `controlDeme`.  It includes differences in score location, scale,
explained variance, and liability threshold. -/
noncomputable def crossDemeCaseControlAUC
    (caseDeme controlDeme : DemeScoreLaw) : ℝ :=
  Foundations.Phi
    ((caseDeme.caseScoreMean - controlDeme.controlScoreMean) /
      Real.sqrt (caseDeme.caseScoreVariance + controlDeme.controlScoreVariance))

/-- Off-diagonal comparison on its typed conditional-variance domain. -/
noncomputable def crossDemeCaseControlAUCOn
    (caseDeme controlDeme : DemeScoreLaw)
    (_ : LiabilityDiscriminationDomain caseDeme)
    (_ : LiabilityDiscriminationDomain controlDeme) : ℝ :=
  crossDemeCaseControlAUC caseDeme controlDeme

/-- The off-diagonal formula reduces to the established within-deme chart when a deme's raw
score is already standardised.  These are coordinate conditions, not biological assumptions. -/
theorem crossDemeCaseControlAUC_diagonal (law : DemeScoreLaw)
    (domain : LiabilityDiscriminationDomain law) :
    crossDemeCaseControlAUCOn law law domain domain = law.withinAUC domain := by
  unfold crossDemeCaseControlAUCOn crossDemeCaseControlAUC DemeScoreLaw.withinAUC
    DemeScoreLaw.liabilityWithinAUC DemeScoreLaw.caseScoreMean
    DemeScoreLaw.controlScoreMean DemeScoreLaw.caseScoreVariance
    DemeScoreLaw.controlScoreVariance liabilityThresholdAUCFromExplainedR2
  have hV : 0 ≤ law.moments.scoreVariance := law.moments_admissible.scoreVariance_pos.le
  have hsum : 0 ≤ liabilityCaseVariance law.r2True law.prevalence +
      liabilityControlVariance law.r2True law.prevalence :=
    add_nonneg domain.caseVariance_pos.le domain.controlVariance_pos.le
  rw [show law.moments.scoreVariance * liabilityCaseVariance law.r2True law.prevalence +
      law.moments.scoreVariance * liabilityControlVariance law.r2True law.prevalence =
      law.moments.scoreVariance * (liabilityCaseVariance law.r2True law.prevalence +
        liabilityControlVariance law.r2True law.prevalence) by ring,
    Real.sqrt_mul hV]
  have hsqrt : Real.sqrt law.moments.scoreVariance ≠ 0 :=
    ne_of_gt (Real.sqrt_pos.2 law.moments_admissible.scoreVariance_pos)
  congr 1
  field_simp [hsqrt]
  ring

/-- A finite population mixture.  `populationWeight` is the unconditional deme mass; its
normalisation is carried by the type so a pooled AUC cannot silently use cell counts. -/
structure DemeMixture (D : ℕ) where
  law : Fin D → DemeScoreLaw
  discriminationDomain : ∀ d, LiabilityDiscriminationDomain (law d)
  populationWeight : Fin D → ℝ
  weight_nonneg : ∀ d, 0 ≤ populationWeight d
  weight_sum_one : ∑ d, populationWeight d = 1
  caseMass_pos : 0 < ∑ d, populationWeight d * (law d).prevalence
  controlMass_pos : 0 < ∑ d, populationWeight d * (1 - (law d).prevalence)

/-- Total case mass before conditioning on case status. -/
noncomputable def DemeMixture.caseMass {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ d, mix.populationWeight d * (mix.law d).prevalence

/-- Total control mass before conditioning on control status. -/
noncomputable def DemeMixture.controlMass {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ d, mix.populationWeight d * (1 - (mix.law d).prevalence)

/-- Deme weight conditional on drawing a case. -/
noncomputable def DemeMixture.caseWeight {D : ℕ} (mix : DemeMixture D) (d : Fin D) : ℝ :=
  mix.populationWeight d * (mix.law d).prevalence / mix.caseMass

/-- Deme weight conditional on drawing a control. -/
noncomputable def DemeMixture.controlWeight {D : ℕ} (mix : DemeMixture D) (d : Fin D) : ℝ :=
  mix.populationWeight d * (1 - (mix.law d).prevalence) / mix.controlMass

/-- Conditional case weights normalize exactly. -/
theorem DemeMixture.caseWeight_sum_one {D : ℕ} (mix : DemeMixture D) :
    ∑ d, mix.caseWeight d = 1 := by
  unfold DemeMixture.caseWeight DemeMixture.caseMass
  rw [← Finset.sum_div]
  exact div_self (ne_of_gt mix.caseMass_pos)

/-- Conditional control weights normalize exactly. -/
theorem DemeMixture.controlWeight_sum_one {D : ℕ} (mix : DemeMixture D) :
    ∑ d, mix.controlWeight d = 1 := by
  unfold DemeMixture.controlWeight DemeMixture.controlMass
  rw [← Finset.sum_div]
  exact div_self (ne_of_gt mix.controlMass_pos)

/-- E2: pooled population AUC.  Diagonal summands are E1; every off-diagonal summand is the
closed Gaussian case-control exceedance between two different demes. -/
noncomputable def DemeMixture.pooledAUC {D : ℕ} (mix : DemeMixture D) : ℝ :=
  ∑ i, ∑ j, mix.caseWeight i * mix.controlWeight j *
    crossDemeCaseControlAUCOn (mix.law i) (mix.law j)
      (mix.discriminationDomain i) (mix.discriminationDomain j)

/-- The pooled formula exposes its diagonal and off-diagonal pieces exactly. -/
theorem DemeMixture.pooledAUC_diagonal_offDiagonal {D : ℕ} (mix : DemeMixture D) :
    mix.pooledAUC =
      (∑ i, ∑ j, if i = j then
        mix.caseWeight i * mix.controlWeight j *
          crossDemeCaseControlAUCOn (mix.law i) (mix.law j)
            (mix.discriminationDomain i) (mix.discriminationDomain j) else 0) +
      (∑ i, ∑ j, if i = j then 0 else
        mix.caseWeight i * mix.controlWeight j *
          crossDemeCaseControlAUCOn (mix.law i) (mix.law j)
            (mix.discriminationDomain i) (mix.discriminationDomain j)) := by
  classical
  unfold DemeMixture.pooledAUC
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro i _
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro j _
  by_cases h : i = j <;> simp [h]

/-! ## E3. Harrell C under an administrative horizon -/

/-- Shifting the score origin by `shift` and scaling the baseline hazard by the reciprocal
hazard multiplier leaves every individual hazard unchanged. -/
theorem proportionalHazard_score_origin_invariant
    (baseline logHazardRatio score shift : ℝ) :
    baseline * Real.exp (-logHazardRatio * shift) *
        Real.exp (logHazardRatio * (score + shift)) =
      baseline * Real.exp (logHazardRatio * score) := by
  rw [mul_assoc, ← Real.exp_add]
  congr 1
  ring

/-- The same origin shift preserves every pairwise prognostic-index contrast. -/
theorem prognosticIndex_difference_shift_invariant
    (logHazardRatio score1 score2 shift : ℝ) :
    logHazardRatio * (score1 + shift) - logHazardRatio * (score2 + shift) =
      logHazardRatio * score1 - logHazardRatio * score2 := by
  ring

/-- A proportional-hazards generator with an arbitrary baseline hazard and administrative
horizon.  The cumulative-hazard identity is carried by the type; constant, piecewise,
spline, and generator-native baselines are instances of this same law. -/
structure AdministrativePHGenerator where
  baselineHazard : ℝ → ℝ
  baselineCumulativeHazard : ℝ → ℝ
  logHazardRatio : ℝ
  horizon : ℝ
  baselineHazard_nonneg : ∀ t, 0 ≤ baselineHazard t
  horizon_nonneg : 0 ≤ horizon
  cumulative_zero : baselineCumulativeHazard 0 = 0
  cumulative_spec : ∀ t, 0 ≤ t →
    baselineCumulativeHazard t = ∫ u in (0 : ℝ)..t, baselineHazard u

/-- Individual event hazard at a time and score. -/
noncomputable def AdministrativePHGenerator.eventHazard
    (g : AdministrativePHGenerator) (time score : ℝ) : ℝ :=
  g.baselineHazard time * Real.exp (g.logHazardRatio * score)

/-- Individual cumulative hazard. -/
noncomputable def AdministrativePHGenerator.eventCumulativeHazard
    (g : AdministrativePHGenerator) (time score : ℝ) : ℝ :=
  g.baselineCumulativeHazard time * Real.exp (g.logHazardRatio * score)

/-- Individual survival probability through a time. -/
noncomputable def AdministrativePHGenerator.eventSurvival
    (g : AdministrativePHGenerator) (time score : ℝ) : ℝ :=
  Real.exp (-g.eventCumulativeHazard time score)

/-- Exact probability that individual 1 fails before individual 2 and before the
administrative horizon, conditional on their scores. -/
noncomputable def AdministrativePHGenerator.firstObserved
    (g : AdministrativePHGenerator) (score1 score2 : ℝ) : ℝ :=
  ∫ time in (0 : ℝ)..g.horizon,
    g.eventHazard time score1 * g.eventSurvival time score1 *
      g.eventSurvival time score2

/-- A Gaussian marginal score law for the survival chart. -/
structure SurvivalScoreLaw where
  mean : ℝ
  variance : ℝ
  variance_pos : 0 < variance

/-- Gaussian score density in the raw score coordinate. -/
noncomputable def SurvivalScoreLaw.density (law : SurvivalScoreLaw) (score : ℝ) : ℝ :=
  Real.exp (-((score - law.mean) ^ 2) / (2 * law.variance)) /
    Real.sqrt (2 * Real.pi * law.variance)

/-- Comparable-pair mass under administrative censoring. -/
noncomputable def administrativeComparableMass
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : ℝ :=
  ∫ s1, ∫ s2,
    (g.firstObserved s1 s2 + g.firstObserved s2 s1) *
      law.density s1 * law.density s2

/-- The prognostic index whose order Harrell C evaluates. -/
noncomputable def AdministrativePHGenerator.prognosticIndex
    (g : AdministrativePHGenerator) (score : ℝ) : ℝ :=
  g.logHazardRatio * score

/-- Concordant comparable-pair mass.  Ties receive one half, matching population AUC and
Harrell's convention. -/
noncomputable def administrativeConcordantMass
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : ℝ :=
  ∫ s1, ∫ s2,
    ((if g.prognosticIndex s1 > g.prognosticIndex s2 then g.firstObserved s1 s2 else
       if g.prognosticIndex s1 = g.prognosticIndex s2 then
         (1 / 2) * g.firstObserved s1 s2 else 0) +
     (if g.prognosticIndex s2 > g.prognosticIndex s1 then g.firstObserved s2 s1 else
       if g.prognosticIndex s2 = g.prognosticIndex s1 then
         (1 / 2) * g.firstObserved s2 s1 else 0)) *
      law.density s1 * law.density s2

/-- Domain on which Harrell C has at least one comparable pair in population measure. -/
structure AdministrativeHarrellDomain
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) : Prop where
  comparableMass_pos : 0 < administrativeComparableMass g law

/-- E3: population Harrell C for an administrative-horizon construction. -/
noncomputable def administrativeHarrellC
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw)
    (_ : AdministrativeHarrellDomain g law) : ℝ :=
  administrativeConcordantMass g law / administrativeComparableMass g law

/-- At horizon zero there are no comparable event pairs; the zero returned by the ratio is
the named empty-comparison branch, not a chance-level C-index. -/
theorem AdministrativePHGenerator.firstObserved_zero_horizon
    (g : AdministrativePHGenerator) (s1 s2 : ℝ) (h : g.horizon = 0) :
    g.firstObserved s1 s2 = 0 := by
  simp [AdministrativePHGenerator.firstObserved, h]

/-- A zero administrative horizon admits no Harrell-C domain: comparable mass is exactly
zero, so the metric remains undefined rather than being filled with chance. -/
theorem noAdministrativeHarrellDomain_at_zero_horizon
    (g : AdministrativePHGenerator) (law : SurvivalScoreLaw) (h : g.horizon = 0) :
    ¬ AdministrativeHarrellDomain g law := by
  intro domain
  have hmass : administrativeComparableMass g law = 0 := by
    unfold administrativeComparableMass
    simp [AdministrativePHGenerator.firstObserved, h]
  linarith [domain.comparableMass_pos]

/-- First-observed probabilities depend only on the two individual hazard and survival
curves.  This pins the chart independently of how a generator represents its baseline. -/
theorem firstObserved_ext (g₁ g₂ : AdministrativePHGenerator) (s1 s2 : ℝ)
    (hhazard : ∀ t, g₁.eventHazard t s1 = g₂.eventHazard t s1)
    (hsurv1 : ∀ t, g₁.eventSurvival t s1 = g₂.eventSurvival t s1)
    (hsurv2 : ∀ t, g₁.eventSurvival t s2 = g₂.eventSurvival t s2)
    (hhorizon : g₁.horizon = g₂.horizon) :
    g₁.firstObserved s1 s2 = g₂.firstObserved s1 s2 := by
  unfold AdministrativePHGenerator.firstObserved
  rw [hhorizon]
  apply intervalIntegral.integral_congr
  intro t _
  simp only [hhazard, hsurv1, hsurv2]

/-! ## Inhabitation

A theorem quantified over an uninhabited structure is true and empty, so the survival classes
carry exhibited inhabitants.  The values sit off the boundaries their own hypotheses exclude:
a zero log hazard ratio would make the hazard score-independent and every discrimination
statement below it trivially true, which inhabits the class while testing nothing. -/

/-- Inhabitation for the Gaussian marginal score law, standardized. -/
noncomputable def SurvivalScoreLaw.witness : SurvivalScoreLaw where
  mean := 0
  variance := 1
  variance_pos := by norm_num

/-- Inhabitation for the administrative proportional-hazards generator, at the EXPONENTIAL
baseline: constant unit hazard, whose cumulative hazard is the identity.  This is the one
baseline for which `cumulative_spec` is an integral the corpus can discharge outright rather
than assume, so the witness proves the cumulative-hazard identity instead of carrying it. -/
noncomputable def AdministrativePHGenerator.witness : AdministrativePHGenerator where
  baselineHazard := fun _ ↦ 1
  baselineCumulativeHazard := fun t ↦ t
  logHazardRatio := 1 / 2
  horizon := 1
  baselineHazard_nonneg := by intro t; norm_num
  horizon_nonneg := by norm_num
  cumulative_zero := rfl
  cumulative_spec := by intro t _; simp

end Descent.Portability
