/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.NeutralFellerGenerator

assert_below Descent.Decision Descent.Program

/-!
# The neutral generator is tangent to the frequency states

This module proves the well-definedness step of NOTE1 §4.2a: the neutral diffusion generator of
`PartialHaplotypeDualGenerator` maps polynomials that vanish on the frequency states to
polynomials that vanish on the frequency states. Configuration moments are linearly dependent
as functions of the state, and this is the fact that lets the dual semigroup act on polynomial
functions of the state rather than only on formal polynomials.

The mass defects. `massDefect i` is `Σ_h x_i[h] − 1`; it vanishes on every state
(`eval_massDefect`). The generator of the total mass of a deme vanishes on states
(`eval_neutralGenerator_massDefect`): migration exchanges mass between demes that all carry
mass one, a crossover recombines two halves whose marginal masses are one, and mutation at a
locus that the empty assignment does not retain cancels over relabelled pairs. Half of the
carré du champ with a mass defect vanishes on states in either argument
(`eval_halfCovariance_massDefect_right`, `eval_halfCovariance_massDefect_left`), because the
Wright–Fisher covariance row of a deme sums to `x_g (1 − Σ_k x_k)`. With the Leibniz rule
`neutralGenerator_mul`, the generator of every multiple `g · massDefect i` vanishes on states
(`eval_neutralGenerator_mul_massDefect`).

The ideal of the states. A polynomial vanishing on every state lies in the ideal generated by
the mass defects (`mem_span_massDefect_of_vanishing`): substituting
`x_i[h₀] ↦ 1 − Σ_{h ≠ h₀} x_i[h]` changes a polynomial by an element of that ideal, and the
substituted polynomial vanishes on a box with infinite sides, hence is zero by
`MvPolynomial.funext_set`. Combining the two gives `eval_neutralGenerator_of_vanishing`: if `p`
vanishes on every state, so does `neutralGenerator rates p`. `neutralGeneratorAddHom` records
that the generator is additive.

Scope. A distinguished haplotype `h₀` is an explicit argument: when some locus has no allele
there are no haplotypes and no states, and the ideal statement fails. Only tangency at the level
of polynomial identities is proved here; the semigroup itself is assembled downstream.

## Empirical status

None. The bodies here are algebra: identities between polynomials in a supplied frequency
vector and the vanishing of their values on per-deme probability vectors, so no measurement on
any population could bear on one.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.NeutralStateTangency

open MvPolynomial PartialHaplotypeCarrier PartialHaplotypeDualGenerator NeutralFellerGenerator

noncomputable section

variable {Deme Locus : Type*} {Allele : Locus → Type*}
variable [Fintype Deme] [DecidableEq Deme] [Fintype Locus] [DecidableEq Locus]
  [∀ ℓ, Fintype (Allele ℓ)] [∀ ℓ, DecidableEq (Allele ℓ)]

/-- The neutral generator as an additive map on frequency polynomials. -/
def neutralGeneratorAddHom (rates : NeutralRates Deme Locus Allele) :
    FrequencyPolynomial Deme Locus Allele →+ FrequencyPolynomial Deme Locus Allele where
  toFun := neutralGenerator rates
  map_zero' := by simp [neutralGenerator, demeSecondOrder]
  map_add' f g := by
    unfold neutralGenerator demeSecondOrder
    simp only [map_add, mul_add, mul_sub, Finset.sum_add_distrib, Finset.sum_sub_distrib]
    ring

/-- The additive generator map applies the neutral generator. -/
theorem neutralGeneratorAddHom_apply (rates : NeutralRates Deme Locus Allele)
    (p : FrequencyPolynomial Deme Locus Allele) :
    neutralGeneratorAddHom rates p = neutralGenerator rates p :=
  rfl

/-- The mass defect `Σ_h x_i[h] − 1` of deme `i`. -/
def massDefect (i : Deme) : FrequencyPolynomial Deme Locus Allele :=
  ∑ hap, X (i, hap) - 1

/-- The marginal polynomial of the empty assignment is the total mass of the deme. -/
theorem assignmentPolynomial_none (i : Deme) :
    assignmentPolynomial i (fun ℓ ↦ (none : Option (Allele ℓ)))
      = ∑ hap, (X (i, hap) : FrequencyPolynomial Deme Locus Allele) := by
  rw [assignmentPolynomial, Finset.filter_true_of_mem fun _ _ _ ↦ Or.inl rfl]

/-- Every mass defect vanishes on the frequency states. -/
theorem eval_massDefect (x : FrequencyState Deme Locus Allele) (i : Deme) :
    eval x.1 (massDefect i) = 0 := by
  simp only [massDefect, map_sub, map_sum, eval_X, map_one, x.2.2 i, sub_self]

/-- The partial derivatives of a mass defect: one along the frequencies of its own deme. -/
theorem pderiv_massDefect (d : Deme) (g : FullHaplotype Locus Allele) (i : Deme) :
    pderiv (d, g) (massDefect (Locus := Locus) (Allele := Allele) i)
      = if d = i then 1 else 0 := by
  rw [massDefect, map_sub, pderiv_one, sub_zero, ← assignmentPolynomial_none,
    pderiv_assignmentPolynomial]
  exact if_congr (and_iff_left fun _ ↦ Or.inl rfl) rfl rfl

/-- The generator of a deme's total mass vanishes on the frequency states: migration, crossover
and mutation all preserve total mass. -/
theorem eval_neutralGenerator_massDefect (rates : NeutralRates Deme Locus Allele)
    (x : FrequencyState Deme Locus Allele) (i : Deme) :
    eval x.1 (neutralGenerator rates (massDefect i)) = 0 := by
  have hsimplex : ∀ d, ∑ hap, x.1 (d, hap) = 1 := x.2.2
  have hrestrict : ∀ selector : Locus → Bool,
      restrictAssignment (fun ℓ ↦ (none : Option (Allele ℓ))) selector = fun _ ↦ none :=
    fun selector ↦ funext fun ℓ ↦ by simp [restrictAssignment]
  have hmig : ∑ j, rates.migration i j
      * (eval x.1 (assignmentPolynomial j fun ℓ ↦ (none : Option (Allele ℓ)))
        - eval x.1 (assignmentPolynomial i fun ℓ ↦ (none : Option (Allele ℓ)))) = 0 := by
    simp only [eval_assignmentPolynomial, sum_satisfies_none x.1 hsimplex, sub_self, mul_zero,
      Finset.sum_const_zero]
  have hrec : ∑ hap ∈ Finset.univ.filter (Satisfies fun ℓ ↦ (none : Option (Allele ℓ))),
      ∑ selector : Locus → Bool, rates.recombination selector *
        (eval x.1 (assignmentPolynomial i
            (restrictAssignment (fun ℓ ↦ some (hap ℓ)) selector))
          * eval x.1 (assignmentPolynomial i
            (restrictAssignment (fun ℓ ↦ some (hap ℓ)) fun ℓ ↦ !selector ℓ))
          - x.1 (i, hap)) = 0 := by
    rw [Finset.sum_comm]
    refine Finset.sum_eq_zero fun selector _ ↦ ?_
    rw [← Finset.mul_sum, Finset.sum_sub_distrib]
    simp only [eval_assignmentPolynomial]
    rw [sum_recombinantProduct, hrestrict, hrestrict, sum_satisfies_none x.1 hsimplex]
    ring
  have hmut : ∑ hap ∈ Finset.univ.filter (Satisfies fun ℓ ↦ (none : Option (Allele ℓ))),
      ∑ ℓ, ∑ b : Allele ℓ, (rates.mutation ℓ b (hap ℓ) * x.1 (i, Function.update hap ℓ b)
        - rates.mutation ℓ (hap ℓ) b * x.1 (i, hap)) = 0 := by
    rw [Finset.sum_comm]
    exact Finset.sum_eq_zero fun ℓ _ ↦ mutationDrift_unassigned rates x.1 i _ ℓ rfl
  rw [massDefect, ← assignmentPolynomial_none, ← neutralGeneratorAddHom_apply, map_sub,
    neutralGeneratorAddHom_apply, neutralGeneratorAddHom_apply, neutralGenerator_one, sub_zero,
    neutralGenerator_assignmentPolynomial, map_sum]
  simp only [driftPolynomial, map_add, map_sum, map_sub, map_mul, eval_C, eval_X]
  rw [Finset.sum_add_distrib, Finset.sum_add_distrib, sum_migrationDrift, hmig, hrec, hmut]
  ring

/-- Half of the carré du champ against a mass defect vanishes on the frequency states: the
Wright–Fisher covariance row of a deme sums to `x_g (1 − Σ_k x_k)`. -/
theorem eval_halfCovariance_massDefect_right (rates : NeutralRates Deme Locus Allele)
    (f : FrequencyPolynomial Deme Locus Allele) (x : FrequencyState Deme Locus Allele)
    (i : Deme) : eval x.1 (halfCovariance rates f (massDefect i)) = 0 := by
  simp only [halfCovariance, map_sum]
  refine Finset.sum_eq_zero fun d _ ↦ ?_
  by_cases hd : d = i
  · subst hd
    simp only [demeCovarianceForm, pderiv_massDefect, if_pos rfl, mul_one, map_mul, map_sub,
      map_sum, eval_X, eval_C]
    have hsum : ∑ k, x.1 (d, k) = 1 := x.2.2 d
    refine mul_eq_zero_of_right _ (sub_eq_zero.mpr (Finset.sum_congr rfl fun g _ ↦ ?_))
    rw [← Finset.sum_mul, ← Finset.mul_sum, hsum, mul_one]
  · simp only [demeCovarianceForm, pderiv_massDefect, if_neg hd, mul_zero,
      Finset.sum_const_zero, sub_self, map_zero]

/-- Half of the carré du champ of a mass defect against any polynomial vanishes on the
frequency states. -/
theorem eval_halfCovariance_massDefect_left (rates : NeutralRates Deme Locus Allele)
    (f : FrequencyPolynomial Deme Locus Allele) (x : FrequencyState Deme Locus Allele)
    (i : Deme) : eval x.1 (halfCovariance rates (massDefect i) f) = 0 := by
  simp only [halfCovariance, map_sum]
  refine Finset.sum_eq_zero fun d _ ↦ ?_
  by_cases hd : d = i
  · subst hd
    simp only [demeCovarianceForm, pderiv_massDefect, if_pos rfl, one_mul, map_mul, map_sub,
      map_sum, eval_X, eval_C]
    have hsum : ∑ g, x.1 (d, g) = 1 := x.2.2 d
    refine mul_eq_zero_of_right _ (sub_eq_zero.mpr ?_)
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun k _ ↦ ?_
    rw [← Finset.sum_mul, ← Finset.sum_mul, hsum, one_mul]
  · simp only [demeCovarianceForm, pderiv_massDefect, if_neg hd, zero_mul, mul_zero,
      Finset.sum_const_zero, sub_self, map_zero]

/-- The generator of any multiple of a mass defect vanishes on the frequency states. -/
theorem eval_neutralGenerator_mul_massDefect (rates : NeutralRates Deme Locus Allele)
    (g : FrequencyPolynomial Deme Locus Allele) (x : FrequencyState Deme Locus Allele)
    (i : Deme) : eval x.1 (neutralGenerator rates (g * massDefect i)) = 0 := by
  rw [neutralGenerator_mul, map_add, map_add, map_add, map_mul, map_mul, eval_massDefect,
    eval_neutralGenerator_massDefect, eval_halfCovariance_massDefect_right,
    eval_halfCovariance_massDefect_left]
  ring

/-- **The ideal of the frequency states.** A polynomial vanishing on every state lies in the
ideal generated by the mass defects. -/
theorem mem_span_massDefect_of_vanishing (hap₀ : FullHaplotype Locus Allele)
    (p : FrequencyPolynomial Deme Locus Allele)
    (hp : ∀ x : FrequencyState Deme Locus Allele, eval x.1 p = 0) :
    p ∈ Ideal.span
      (Set.range fun i : Deme ↦ massDefect (Locus := Locus) (Allele := Allele) i) := by
  set I := Ideal.span
    (Set.range fun i : Deme ↦ massDefect (Locus := Locus) (Allele := Allele) i) with hI
  let substitution : FrequencyVariable Deme Locus Allele → FrequencyPolynomial Deme Locus Allele :=
    fun c ↦ if c.2 = hap₀ then 1 - ∑ h ∈ Finset.univ.erase hap₀, X (c.1, h) else X c
  have hmem : p - bind₁ substitution p ∈ I := by
    have hext : (Ideal.Quotient.mk I).comp (bind₁ substitution).toRingHom
        = Ideal.Quotient.mk I := by
      refine MvPolynomial.ringHom_ext (fun r ↦ ?_) fun c ↦ ?_
      · show Ideal.Quotient.mk I (bind₁ substitution (C r)) = Ideal.Quotient.mk I (C r)
        rw [bind₁_C_right]
      · show Ideal.Quotient.mk I (bind₁ substitution (X c)) = Ideal.Quotient.mk I (X c)
        rw [bind₁_X_right]
        refine Ideal.Quotient.eq.mpr ?_
        obtain ⟨i, h⟩ := c
        by_cases hh : h = hap₀
        · have hdef : substitution (i, h) - X (i, h) = -massDefect i := by
            simp only [substitution, hh, eq_self_iff_true, if_true, massDefect]
            rw [← Finset.add_sum_erase Finset.univ
              (fun hap ↦ (X (i, hap) : FrequencyPolynomial Deme Locus Allele))
              (Finset.mem_univ hap₀)]
            ring
          rw [hdef]
          exact I.neg_mem (Ideal.subset_span ⟨i, rfl⟩)
        · have hdef : substitution (i, h) - X (i, h) = 0 := by
            simp only [substitution, if_neg hh, sub_self]
          rw [hdef]
          exact I.zero_mem
    have happ := congrArg
      (fun φ : FrequencyPolynomial Deme Locus Allele →+* _ ⧸ I ↦ φ p) hext
    exact Ideal.Quotient.eq.mp happ.symm
  have hzero : bind₁ substitution p = 0 := by
    set ε : ℝ := 1 / (Fintype.card (FullHaplotype Locus Allele) + 1) with hε_def
    have hε : 0 < ε := by positivity
    have hcard : (Fintype.card (FullHaplotype Locus Allele) : ℝ) * ε ≤ 1 := by
      rw [hε_def, mul_one_div, div_le_one (by positivity)]
      linarith
    refine MvPolynomial.funext_set
      (fun c ↦ if c.2 = hap₀ then Set.univ else Set.Ioo (0 : ℝ) ε) (fun c ↦ ?_) fun y hy ↦ ?_
    · dsimp only
      split_ifs
      · exact Set.infinite_univ
      · exact Set.Ioo_infinite hε
    · have hsmall : ∀ c : FrequencyVariable Deme Locus Allele, c.2 ≠ hap₀ →
          0 < y c ∧ y c < ε := by
        intro c hc
        have hyc := hy c (Set.mem_univ c)
        simpa only [if_neg hc, Set.mem_Ioo] using hyc
      have hbound : ∀ i : Deme, ∑ h ∈ Finset.univ.erase hap₀, y (i, h) ≤ 1 := by
        intro i
        calc ∑ h ∈ Finset.univ.erase hap₀, y (i, h) ≤ ∑ _h ∈ Finset.univ.erase hap₀, ε :=
              Finset.sum_le_sum fun h hh ↦ (hsmall (i, h) (Finset.ne_of_mem_erase hh)).2.le
          _ ≤ (Fintype.card (FullHaplotype Locus Allele) : ℝ) * ε := by
              rw [Finset.sum_const, nsmul_eq_mul]
              exact mul_le_mul_of_nonneg_right (by exact_mod_cast Finset.card_le_univ _) hε.le
          _ ≤ 1 := hcard
      have hstate : (fun c ↦ eval y (substitution c)) ∈ frequencySimplex Deme Locus Allele := by
        refine ⟨fun c ↦ ?_, fun i ↦ ?_⟩
        · obtain ⟨i, h⟩ := c
          by_cases hh : h = hap₀
          · simp only [substitution, hh, eq_self_iff_true, if_true, map_sub, map_one, map_sum,
              eval_X]
            linarith [hbound i]
          · simp only [substitution, if_neg hh, eval_X]
            exact (hsmall (i, h) hh).1.le
        · show ∑ h, eval y (substitution (i, h)) = 1
          rw [← Finset.add_sum_erase Finset.univ _ (Finset.mem_univ hap₀)]
          have hrest : ∑ h ∈ Finset.univ.erase hap₀, eval y (substitution (i, h))
              = ∑ h ∈ Finset.univ.erase hap₀, y (i, h) :=
            Finset.sum_congr rfl fun h hh ↦ by
              simp only [substitution, if_neg (Finset.ne_of_mem_erase hh), eval_X]
          rw [hrest]
          simp only [substitution, eq_self_iff_true, if_true, map_sub, map_one, map_sum, eval_X]
          ring
      rw [map_zero]
      exact (eval₂Hom_bind₁ (RingHom.id ℝ) y substitution p).trans (hp ⟨_, hstate⟩)
  rw [hzero, sub_zero] at hmem
  exact hmem

/-- **Tangency of the neutral generator.** If a polynomial vanishes on every frequency state,
so does its neutral generator. -/
theorem eval_neutralGenerator_of_vanishing (rates : NeutralRates Deme Locus Allele)
    (hap₀ : FullHaplotype Locus Allele) (p : FrequencyPolynomial Deme Locus Allele)
    (hp : ∀ x : FrequencyState Deme Locus Allele, eval x.1 p = 0)
    (x : FrequencyState Deme Locus Allele) : eval x.1 (neutralGenerator rates p) = 0 := by
  obtain ⟨c, hc⟩ :=
    (Submodule.mem_span_range_iff_exists_fun _).mp (mem_span_massDefect_of_vanishing hap₀ p hp)
  rw [← hc, ← neutralGeneratorAddHom_apply, map_sum, map_sum]
  exact Finset.sum_eq_zero fun i _ ↦ eval_neutralGenerator_mul_massDefect rates (c i) x i

end

end Descent.Portability.NeutralStateTangency
