/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.AuditRayleighGeometry
import Descent.Portability.FiniteAuditDesignConvexity

assert_below Descent.Decision Descent.Program

/-!
Decision-Directed Portability, Theorem 14: convexity and actual attainment of
the spectral shared-audit allocation problem. The objective is the largest
eigenvalue of the covariance operator generated by the design probabilities.
Positive probability floors ensure continuity on the compact feasible set.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.SpectralAuditDesign

open AuditCovarianceSpectrum AuditRayleighGeometry FiniteAuditDesign FiniteAuditDesignConvexity
open scoped BigOperators

variable {ι E : Type*} [Fintype ι]
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]

/-- Worst-direction covariance variance, with normalization included in the fixed row vectors. -/
noncomputable def objective (κ : ι → ℝ) (u : ι → E) (p : ι → ℝ) : ℝ :=
  largest (fun i ↦ κ i / p i) u

/-- A valid variance envelope and positive sampling probabilities give a nonnegative objective. -/
theorem objective_nonneg (κ : ι → ℝ) (u : ι → E) (p : ι → ℝ)
    (hκ : ∀ i, 0 ≤ κ i) (hp : ∀ i, 0 < p i) : 0 ≤ objective κ u p :=
  largest_nonneg _ u (fun i ↦ div_nonneg (hκ i) (hp i).le)

/-- Every unit-ball repair direction is bounded by the actual spectral objective. -/
theorem direction_le (κ : ι → ℝ) (u : ι → E) (p : ι → ℝ)
    (hκ : ∀ i, 0 ≤ κ i) (hp : ∀ i, 0 < p i) (a : E) (ha : ‖a‖ ≤ 1) :
    (∑ i, κ i / p i * (inner ℝ a (u i)) ^ 2) ≤ objective κ u p :=
  unit_quadratic_le _ u (fun i ↦ div_nonneg (hκ i) (hp i).le) a ha

/-- The spectral criterion is convex in the design probabilities. -/
theorem objective_convex (κ floor c : ι → ℝ) (u : ι → E) (B : ℝ)
    (hκ : ∀ i, 0 ≤ κ i) (hf : ∀ i, 0 < floor i) :
    ConvexOn ℝ {p | Feasible floor c B p} (objective κ u) := by
  refine ⟨feasible_convex floor c B, ?_⟩
  intro p hp q hq α β hα hβ hsum
  have hp' (i : ι) := (hf i).trans_le (hp.1 i).1
  have hq' (i : ι) := (hf i).trans_le (hq.1 i).1
  have hm := feasible_convex floor c B hp hq hα hβ hsum
  have hm' (i : ι) := (hf i).trans_le (hm.1 i).1
  apply (largest_le_iff _ u (fun i ↦ div_nonneg (hκ i) (hm' i).le) _).mpr
  intro a ha
  have hj : (∑ i, κ i / (α * p i + β * q i) * (inner ℝ a (u i)) ^ 2) ≤
      α * (∑ i, κ i / p i * (inner ℝ a (u i)) ^ 2) +
      β * (∑ i, κ i / q i * (inner ℝ a (u i)) ^ 2) := by
    rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
    apply Finset.sum_le_sum
    intro i _
    have hh := reciprocal_jensen (κ i * (inner ℝ a (u i)) ^ 2) (p i) (q i) α β
      (mul_nonneg (hκ i) (sq_nonneg _)) (hp' i) (hq' i) hα hβ hsum
    convert hh using 1 <;> ring
  have hl := add_le_add (mul_le_mul_of_nonneg_left (direction_le κ u p hκ hp' a ha) hα)
    (mul_le_mul_of_nonneg_left (direction_le κ u q hκ hq' a ha) hβ)
  exact hj.trans hl

/-- The actual eigenvalue objective is continuous on the positive-floor design set. -/
theorem objective_continuous (κ floor c : ι → ℝ) (u : ι → E) (B : ℝ)
    (hκ : ∀ i, 0 ≤ κ i) (hf : ∀ i, 0 < floor i) :
    ContinuousOn (objective κ u) {p | Feasible floor c B p} := by
  apply largest_continuousOn _ (fun p i ↦ κ i / p i) u
  · intro p hp i
    exact div_nonneg (hκ i) ((hf i).trans_le (hp.1 i).1).le
  · intro i
    exact continuousOn_const.div (continuous_apply i).continuousOn
      (fun p hp ↦ ((hf i).trans_le (hp.1 i).1).ne')

/-- Every nonempty feasible spectral audit problem has an attained optimizer. -/
theorem optimum_exists (κ floor c : ι → ℝ) (u : ι → E) (B : ℝ)
    (hκ : ∀ i, 0 ≤ κ i) (hf : ∀ i, 0 < floor i)
    (hne : {p | Feasible floor c B p}.Nonempty) :
    ∃ p, Feasible floor c B p ∧ IsMinOn (objective κ u) {q | Feasible floor c B q} p :=
  (feasible_compact floor c B).exists_isMinOn hne (objective_continuous κ floor c u B hκ hf)

end Descent.Portability.SpectralAuditDesign
