/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.ConvexOrderCoupling
import Descent.Portability.IndividualLossMoments

assert_below Descent.Decision Descent.Program

/-!
# One architecture, three exact report laws

This module formalizes DC Theorem 4.1 / PL Theorem 5.1: the exact conditional squared
correlation, mean squared error and individual-loss variance generated by one realized
effect architecture, under the manuscript's explicit genotype and noise law.

The population is built, not assumed: `architecturePop` is a `DeploymentPopulation`
whose expectation is the product of the uniform law on `n` independent fair signs with an
arbitrary finite-support environmental noise law, whose scored and causal codings are the
`±1` genotypes, and whose causal effects are `aᵢσᵢ`. The reports are then the corpus's own
`r2`, `deployedMse` and `variance`, not redefinitions of them.

The Rademacher moment lemmas (`sum_blockScore_mean` … `sum_blockScore_quartic`) are proved
from scratch by induction on the locus set, using only the coordinate-flip involution; no
independence hypothesis is assumed anywhere, because the law is exhibited.

Domain conditions used: `∑ aᵢ² = 1` (unit genetic variance, the manuscript's
normalization) and `E ε = 0` (centered noise). Nothing assumes a Gaussian law, a value for
`E ε³`, or any of the identities proved.

Built on `Descent.Portability.PortabilityMasterTheorem` (`DeploymentPopulation`,
`weightedExp`, `uniformExp`), `Descent.Portability.IndividualLossMoments` (`mixture`), and
`Descent.Portability.ConvexOrderCoupling` (`occupiedCount`, for the equal-weight
specialization DC (4.2)).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.TurnoverArchitectureMetrics

open Foundations IndividualLossMoments

noncomputable section

/-! ## Fair signs and the coordinate-flip involution -/

/-- The `±1` genotype coding of a Boolean coordinate. -/
def signValue (b : Bool) : ℝ := if b then 1 else -1

/-- A sign squares to one. -/
@[simp] theorem signValue_sq (b : Bool) : signValue b ^ 2 = 1 := by
  cases b <;> norm_num [signValue]

/-- Negating a coordinate negates its sign. -/
@[simp] theorem signValue_not (b : Bool) : signValue (!b) = -signValue b := by
  cases b <;> norm_num [signValue]

/-- Flip one coordinate of a configuration. -/
def flipCoord {n : ℕ} (j : Fin n) (s : Fin n → Bool) : Fin n → Bool :=
  Function.update s j (!s j)

/-- A flip changes the flipped coordinate. -/
@[simp] theorem flipCoord_self {n : ℕ} (j : Fin n) (s : Fin n → Bool) :
    flipCoord j s j = !s j := by
  simp [flipCoord]

/-- A flip leaves every other coordinate alone. -/
theorem flipCoord_ne {n : ℕ} (j : Fin n) {i : Fin n} (hij : i ≠ j) (s : Fin n → Bool) :
    flipCoord j s i = s i := by
  simp [flipCoord, hij]

/-- A flip is an involution. -/
theorem flipCoord_invol {n : ℕ} (j : Fin n) (s : Fin n → Bool) :
    flipCoord j (flipCoord j s) = s := by
  funext i
  by_cases h : i = j
  · subst h
    simp [flipCoord]
  · rw [flipCoord_ne j h, flipCoord_ne j h]

/-- Flipping one coordinate is a bijection of the configuration space. -/
def flipEquiv {n : ℕ} (j : Fin n) : (Fin n → Bool) ≃ (Fin n → Bool) where
  toFun := flipCoord j
  invFun := flipCoord j
  left_inv := flipCoord_invol j
  right_inv := flipCoord_invol j

/-- Summing over configurations is invariant under a coordinate flip. -/
theorem sum_flip_eq {n : ℕ} (j : Fin n) (F : (Fin n → Bool) → ℝ) :
    ∑ s : Fin n → Bool, F (flipCoord j s) = ∑ s : Fin n → Bool, F s :=
  Equiv.sum_comp (flipEquiv j) F

/-- **Odd terms average to zero.** A weight that does not see coordinate `j`, multiplied by
the sign of coordinate `j`, sums to zero over all configurations.  This single fact drives
every Rademacher moment below; it replaces an assumed independence hypothesis. -/
theorem sum_odd_vanishes {n : ℕ} (j : Fin n) (P : (Fin n → Bool) → ℝ)
    (hP : ∀ s, P (flipCoord j s) = P s) :
    ∑ s : Fin n → Bool, P s * signValue (s j) = 0 := by
  have h := sum_flip_eq j (fun s ↦ P s * signValue (s j))
  have hpt : ∀ s : Fin n → Bool,
      P (flipCoord j s) * signValue (flipCoord j s j) = -(P s * signValue (s j)) := by
    intro s
    rw [hP s, flipCoord_self]
    simp
  rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_neg_distrib] at h
  linarith

/-! ## Rademacher moments of a linear genotype score -/

/-- The linear score `∑_{i ∈ t} dᵢ Gᵢ` carried by a set `t` of loci. -/
def blockScore {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) (s : Fin n → Bool) : ℝ :=
  ∑ i ∈ t, d i * signValue (s i)

/-- Adding one locus to the block. -/
theorem blockScore_insert {n : ℕ} (d : Fin n → ℝ) {t : Finset (Fin n)} {j : Fin n}
    (hj : j ∉ t) (s : Fin n → Bool) :
    blockScore d (insert j t) s = blockScore d t s + d j * signValue (s j) := by
  simp only [blockScore, Finset.sum_insert hj]
  ring

/-- A block score does not see a locus outside its block. -/
theorem blockScore_flip {n : ℕ} (d : Fin n → ℝ) {t : Finset (Fin n)} {j : Fin n}
    (hj : j ∉ t) (s : Fin n → Bool) :
    blockScore d t (flipCoord j s) = blockScore d t s := by
  simp only [blockScore]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  have hij : i ≠ j := fun h ↦ hj (h ▸ hi)
  rw [flipCoord_ne j hij]

/-- Block scores are additive in their coefficient vectors. -/
theorem blockScore_sub {n : ℕ} (d1 d2 : Fin n → ℝ) (t : Finset (Fin n)) (s : Fin n → Bool) :
    blockScore d1 t s - blockScore d2 t s = blockScore (fun i ↦ d1 i - d2 i) t s := by
  simp only [blockScore, ← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl fun i _ ↦ by ring

/-- First Rademacher moment: a linear score has mean zero. -/
theorem sum_blockScore_mean {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s = 0 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s
          = blockScore d t s + d j * ((fun _ : Fin n → Bool ↦ (1 : ℝ)) s * signValue (s j)) := by
      intro s
      rw [blockScore_insert d hj s]
      ring
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, ← Finset.mul_sum, ih,
      sum_odd_vanishes j (fun _ ↦ (1 : ℝ)) (fun _ ↦ rfl)]
    ring

/-- There are `2ⁿ` configurations of `n` coordinates. -/
theorem card_config (n : ℕ) :
    (((Finset.univ : Finset (Fin n → Bool)).card : ℕ) : ℝ) = (2 : ℝ) ^ n := by
  rw [Finset.card_univ]
  simp

/-- Second Rademacher moment: `E(∑ dᵢGᵢ)² = ∑ dᵢ²`. -/
theorem sum_blockScore_sq {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 2
      = ((2 : ℝ) ^ n) * ∑ i ∈ t, d i ^ 2 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 2
          = blockScore d t s ^ 2 + d j ^ 2
            + 2 * d j * (blockScore d t s * signValue (s j)) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination (d j ^ 2) * hs
    have hinv : ∀ s : Fin n → Bool,
        blockScore d t (flipCoord j s) = blockScore d t s := fun s ↦ blockScore_flip d hj s
    have hodd : ∑ s : Fin n → Bool, blockScore d t s * signValue (s j) = 0 :=
      sum_odd_vanishes j (fun s ↦ blockScore d t s) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      ← Finset.mul_sum, ih, hodd, Finset.sum_const, nsmul_eq_mul, card_config n]
    simp only [Finset.sum_insert hj]
    ring

/-- Third Rademacher moment: a linear score has zero third moment. -/
theorem sum_blockScore_cube {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 3 = 0 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 3
          = blockScore d t s ^ 3 + 3 * d j ^ 2 * blockScore d t s
            + (3 * d j * blockScore d t s ^ 2 + d j ^ 3) * signValue (s j) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination
        (3 * blockScore d t s * d j ^ 2 + d j ^ 3 * signValue (s j)) * hs
    have hinv : ∀ s : Fin n → Bool,
        3 * d j * blockScore d t (flipCoord j s) ^ 2 + d j ^ 3
          = 3 * d j * blockScore d t s ^ 2 + d j ^ 3 := by
      intro s
      rw [blockScore_flip d hj s]
    have hodd : ∑ s : Fin n → Bool,
        (3 * d j * blockScore d t s ^ 2 + d j ^ 3) * signValue (s j) = 0 :=
      sum_odd_vanishes j (fun s ↦ 3 * d j * blockScore d t s ^ 2 + d j ^ 3) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      ← Finset.mul_sum, ih, sum_blockScore_mean d t, hodd]
    ring

/-- **Fourth Rademacher moment**, the combinatorial core of PL Theorem 5.1:
`E(∑ dᵢGᵢ)⁴ = 3(∑ dᵢ²)² - 2∑ dᵢ⁴`. -/
theorem sum_blockScore_quartic {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 4
      = ((2 : ℝ) ^ n) * (3 * (∑ i ∈ t, d i ^ 2) ^ 2 - 2 * ∑ i ∈ t, d i ^ 4) := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 4
          = blockScore d t s ^ 4 + 6 * d j ^ 2 * blockScore d t s ^ 2 + d j ^ 4
            + (4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s)
              * signValue (s j) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination
        (6 * blockScore d t s ^ 2 * d j ^ 2
          + 4 * blockScore d t s * d j ^ 3 * signValue (s j)
          + d j ^ 4 * (signValue (s j) ^ 2 + 1)) * hs
    have hinv : ∀ s : Fin n → Bool,
        4 * d j * blockScore d t (flipCoord j s) ^ 3
            + 4 * d j ^ 3 * blockScore d t (flipCoord j s)
          = 4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s := by
      intro s
      rw [blockScore_flip d hj s]
    have hodd : ∑ s : Fin n → Bool,
        (4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s)
          * signValue (s j) = 0 :=
      sum_odd_vanishes j
        (fun s ↦ 4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      Finset.sum_add_distrib, ← Finset.mul_sum, ih, sum_blockScore_sq d t, hodd,
      Finset.sum_const, nsmul_eq_mul, card_config n]
    simp only [Finset.sum_insert hj]
    ring

/-! ## The genotype-and-noise law -/

/-- The law of PL (5.1) / DC (4.1): `n` independent fair signs, independent of an
arbitrary finite-support environmental noise law.  Independence is the product structure
of `mixture`, not a hypothesis. -/
def genotypeNoiseExp (n : ℕ) {V : Type*} [Fintype V] (noise : ExpFunctional V) :
    ExpFunctional ((Fin n → Bool) × V) :=
  mixture (uniformExp (Fin n → Bool)) (fun _ ↦ noise)

/-- Linearity over a three-term combination. -/
theorem eval_comb3 {Ω : Type*} (Ex : ExpFunctional Ω) (c0 c1 c2 : ℝ) (g1 g2 : Ω → ℝ) :
    Ex (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω) = c0 + c1 * Ex g1 + c2 * Ex g2 := by
  have h : (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω)
      = ((fun _ : Ω ↦ c0) + c1 • g1) + c2 • g2 := by
    funext ω
    simp
  rw [h, Ex.add_eval, Ex.add_eval, Ex.smul_eval, Ex.smul_eval, Ex.eval_const]

/-- Linearity over a five-term combination. -/
theorem eval_comb5 {Ω : Type*} (Ex : ExpFunctional Ω) (c0 c1 c2 c3 c4 : ℝ)
    (g1 g2 g3 g4 : Ω → ℝ) :
    Ex (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω + c3 * g3 ω + c4 * g4 ω)
      = c0 + c1 * Ex g1 + c2 * Ex g2 + c3 * Ex g3 + c4 * Ex g4 := by
  have h : (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω + c3 * g3 ω + c4 * g4 ω)
      = (((fun _ : Ω ↦ c0) + c1 • g1) + c2 • g2 + c3 • g3) + c4 • g4 := by
    funext ω
    simp
  rw [h, Ex.add_eval, Ex.add_eval, Ex.add_eval, Ex.add_eval, Ex.smul_eval, Ex.smul_eval,
    Ex.smul_eval, Ex.smul_eval, Ex.eval_const]

/-- Uniform expectation over configurations is the normalized sum. -/
theorem uniform_geno_eq (n : ℕ) (F : (Fin n → Bool) → ℝ) :
    uniformExp (Fin n → Bool) F = ((2 : ℝ) ^ n)⁻¹ * ∑ s : Fin n → Bool, F s := by
  rw [uniformExp_apply, ← Finset.mul_sum]
  congr 1
  simp

/-- A genotype-only observable has its genotype expectation. -/
theorem exp_geno {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (F : (Fin n → Bool) → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ F p.1) = uniformExp (Fin n → Bool) F := by
  show uniformExp (Fin n → Bool) (fun s ↦ noise (fun _ ↦ F s)) = uniformExp (Fin n → Bool) F
  simp

/-- Genotype and noise observables factorize. -/
theorem exp_mul {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (F : (Fin n → Bool) → ℝ) (H : V → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ F p.1 * H p.2)
      = uniformExp (Fin n → Bool) F * noise H := by
  show uniformExp (Fin n → Bool) (fun s ↦ noise (fun e ↦ F s * H e)) = _
  have h1 : ∀ s : Fin n → Bool, noise (fun e ↦ F s * H e) = F s * noise H := by
    intro s
    have h2 : (fun e ↦ F s * H e) = (F s) • H := by
      funext e
      simp
    rw [h2, noise.smul_eval]
  simp only [h1]
  have h3 : (fun s ↦ F s * noise H) = (noise H) • F := by
    funext s
    simp [mul_comm]
  rw [h3, (uniformExp (Fin n → Bool)).smul_eval]
  ring

/-- Mean of a genotype-linear score plus independent noise. -/
theorem exp_lin_noise_mean {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) :
    genotypeNoiseExp n noise
        (fun p ↦ blockScore d Finset.univ p.1 + ξ p.2) = noise ξ := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ blockScore d Finset.univ s + ξ e)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ blockScore d Finset.univ s + ξ e)
        = blockScore d Finset.univ s + noise ξ := by
    intro s
    have hx : (fun e ↦ blockScore d Finset.univ s + ξ e)
        = fun e ↦ blockScore d Finset.univ s + 1 * ξ e := by
      funext e
      ring
    rw [hx, eval_affine]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s + noise ξ)
      = fun s ↦ noise ξ + 1 * blockScore d Finset.univ s := by
    funext s
    ring
  rw [hx, eval_affine, uniform_geno_eq, sum_blockScore_mean]
  ring

/-- Second moment of a genotype-linear score plus independent noise. -/
theorem exp_lin_noise_sq {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) (hmean : noise ξ = 0) :
    genotypeNoiseExp n noise
        (fun p ↦ (blockScore d Finset.univ p.1 + ξ p.2) ^ 2)
      = (∑ i, d i ^ 2) + noise (fun e ↦ ξ e ^ 2) := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)
        = blockScore d Finset.univ s ^ 2 + noise (fun e ↦ ξ e ^ 2) := by
    intro s
    have hx : (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)
        = fun e ↦ blockScore d Finset.univ s ^ 2
          + (2 * blockScore d Finset.univ s) * ξ e + 1 * ξ e ^ 2 := by
      funext e
      ring
    rw [hx, eval_comb3, hmean]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s ^ 2 + noise (fun e ↦ ξ e ^ 2))
      = fun s ↦ noise (fun e ↦ ξ e ^ 2) + 1 * blockScore d Finset.univ s ^ 2 := by
    funext s
    ring
  rw [hx, eval_affine, uniform_geno_eq, sum_blockScore_sq]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp
  ring

/-- **Fourth moment of a genotype-linear score plus independent noise**, PL Theorem 5.1.
The third noise moment appears multiplied by the vanishing first genotype moment, so it
never enters -- no hypothesis about it is needed. -/
theorem exp_lin_noise_quartic {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) (hmean : noise ξ = 0) :
    genotypeNoiseExp n noise
        (fun p ↦ (blockScore d Finset.univ p.1 + ξ p.2) ^ 4)
      = 3 * (∑ i, d i ^ 2) ^ 2 - 2 * (∑ i, d i ^ 4)
        + 6 * (∑ i, d i ^ 2) * noise (fun e ↦ ξ e ^ 2) + noise (fun e ↦ ξ e ^ 4) := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)
        = blockScore d Finset.univ s ^ 4
          + 6 * blockScore d Finset.univ s ^ 2 * noise (fun e ↦ ξ e ^ 2)
          + 4 * blockScore d Finset.univ s * noise (fun e ↦ ξ e ^ 3)
          + noise (fun e ↦ ξ e ^ 4) := by
    intro s
    have hx : (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)
        = fun e ↦ blockScore d Finset.univ s ^ 4
          + (4 * blockScore d Finset.univ s ^ 3) * ξ e
          + (6 * blockScore d Finset.univ s ^ 2) * ξ e ^ 2
          + (4 * blockScore d Finset.univ s) * ξ e ^ 3 + 1 * ξ e ^ 4 := by
      funext e
      ring
    rw [hx, eval_comb5, hmean]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s ^ 4
        + 6 * blockScore d Finset.univ s ^ 2 * noise (fun e ↦ ξ e ^ 2)
        + 4 * blockScore d Finset.univ s * noise (fun e ↦ ξ e ^ 3)
        + noise (fun e ↦ ξ e ^ 4))
      = fun s ↦ noise (fun e ↦ ξ e ^ 4) + 1 * blockScore d Finset.univ s ^ 4
        + (6 * noise (fun e ↦ ξ e ^ 2)) * blockScore d Finset.univ s ^ 2
        + (4 * noise (fun e ↦ ξ e ^ 3)) * blockScore d Finset.univ s
        + 0 * (fun _ : Fin n → Bool ↦ (0 : ℝ)) s := by
    funext s
    ring
  rw [hx, eval_comb5, uniform_geno_eq, uniform_geno_eq, uniform_geno_eq,
    sum_blockScore_quartic, sum_blockScore_sq, sum_blockScore_mean]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp
  ring

end

end Descent.Portability.TurnoverArchitectureMetrics
