/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.ConvexOrderCoupling
import Descent.Portability.IndividualLossMoments
import Descent.Portability.TraitPortabilityRange

assert_below Descent.Decision Descent.Program

/-!
# One architecture, three exact report laws

This module formalizes DC Theorem 4.1 / PL Theorem 5.1: the exact conditional squared
correlation, mean squared error and individual-loss variance generated by one realized
effect architecture, under the manuscript's explicit genotype and noise law.

The population is built, not assumed: `architecturePop` is a `DeploymentPopulation`
whose expectation is the product of the uniform law on `n` independent fair signs with an
arbitrary finite-support environmental noise law, whose scored and causal codings are the
`±1` genotypes, and whose causal effects are `aᵢσᵢ`. The reports are then the corpus's own
`r2`, `deployedMse` and `variance`, not redefinitions of them.

The Rademacher moment lemmas (`sum_blockScore_mean` … `sum_blockScore_quartic`) are proved
from scratch by induction on the locus set, using only the coordinate-flip involution; no
independence hypothesis is assumed anywhere, because the law is exhibited.

Domain conditions used: `∑ aᵢ² = 1` (unit genetic variance, the manuscript's
normalization) and `E ε = 0` (centered noise). Nothing assumes a Gaussian law, a value for
`E ε³`, or any of the identities proved.

Built on `Descent.Portability.PortabilityMasterTheorem` (`DeploymentPopulation`,
`weightedExp`, `uniformExp`), `Descent.Portability.IndividualLossMoments` (`mixture`),
`Descent.Portability.ConvexOrderCoupling` (`occupiedCount`, for the equal-weight
specialization DC (4.2)), and `Descent.Portability.TraitPortabilityRange`, whose `sign` is
the same `±1` coding as `signValue` here.

## Empirical status

None. The bodies here are algebra: `genotypeNoiseExp` is an exhibited product law, not an
estimate of any population's genotype or noise distribution, and the report formulas are
identities of that exhibited law. A claim that these compute something measured would live
in a subsystem module with its own regime and its own ledger row.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.TurnoverArchitectureMetrics

open Foundations IndividualLossMoments

noncomputable section

/-! ## Fair signs and the coordinate-flip involution -/

/-- The `±1` genotype coding of a Boolean coordinate.  This is literally the coding of
`Descent.Portability.TraitPortabilityRange.sign`, called rather than restated. -/
def signValue (b : Bool) : ℝ := TraitPortabilityRange.sign b

/-- A sign squares to one. -/
@[simp] theorem signValue_sq (b : Bool) : signValue b ^ 2 = 1 := by
  cases b <;> norm_num [signValue, TraitPortabilityRange.sign]

/-- The `±1` coding here is the one already carried by
`Descent.Portability.TraitPortabilityRange.sign`: the two names denote one function. -/
theorem signValue_eq_sign : signValue = TraitPortabilityRange.sign := rfl

/-- Flip one coordinate of a configuration. -/
def flipCoord {n : ℕ} (j : Fin n) (s : Fin n → Bool) : Fin n → Bool :=
  Function.update s j (!s j)

/-- A flip changes the flipped coordinate. -/
@[simp] theorem flipCoord_self {n : ℕ} (j : Fin n) (s : Fin n → Bool) :
    flipCoord j s j = !s j := by
  simp [flipCoord]

/-- A flip leaves every other coordinate alone. -/
theorem flipCoord_ne {n : ℕ} (j : Fin n) {i : Fin n} (hij : i ≠ j) (s : Fin n → Bool) :
    flipCoord j s i = s i := by
  simp [flipCoord, hij]

/-- A flip is an involution. -/
theorem flipCoord_invol {n : ℕ} (j : Fin n) (s : Fin n → Bool) :
    flipCoord j (flipCoord j s) = s := by
  funext i
  by_cases h : i = j
  · subst h
    simp [flipCoord]
  · rw [flipCoord_ne j h, flipCoord_ne j h]

/-- Flipping one coordinate is a bijection of the configuration space. -/
def flipEquiv {n : ℕ} (j : Fin n) : (Fin n → Bool) ≃ (Fin n → Bool) where
  toFun := flipCoord j
  invFun := flipCoord j
  left_inv := flipCoord_invol j
  right_inv := flipCoord_invol j

/-- Summing over configurations is invariant under a coordinate flip. -/
theorem sum_flip_eq {n : ℕ} (j : Fin n) (F : (Fin n → Bool) → ℝ) :
    ∑ s : Fin n → Bool, F (flipCoord j s) = ∑ s : Fin n → Bool, F s :=
  Equiv.sum_comp (flipEquiv j) F

/-- **Odd terms average to zero.** A weight that does not see coordinate `j`, multiplied by
the sign of coordinate `j`, sums to zero over all configurations.  This single fact drives
every Rademacher moment below; it replaces an assumed independence hypothesis. -/
theorem sum_odd_vanishes {n : ℕ} (j : Fin n) (P : (Fin n → Bool) → ℝ)
    (hP : ∀ s, P (flipCoord j s) = P s) :
    ∑ s : Fin n → Bool, P s * signValue (s j) = 0 := by
  have h := sum_flip_eq j (fun s ↦ P s * signValue (s j))
  have hpt : ∀ s : Fin n → Bool,
      P (flipCoord j s) * signValue (flipCoord j s j) = -(P s * signValue (s j)) := by
    intro s
    rw [hP s, flipCoord_self]
    rcases Bool.eq_false_or_eq_true (s j) with hb | hb <;>
      simp [hb, signValue, TraitPortabilityRange.sign]
  rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_neg_distrib] at h
  linarith

/-! ## Rademacher moments of a linear genotype score -/

/-- The linear score `∑_{i ∈ t} dᵢ Gᵢ` carried by a set `t` of loci. -/
def blockScore {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) (s : Fin n → Bool) : ℝ :=
  ∑ i ∈ t, d i * signValue (s i)

/-- Adding one locus to the block. -/
theorem blockScore_insert {n : ℕ} (d : Fin n → ℝ) {t : Finset (Fin n)} {j : Fin n}
    (hj : j ∉ t) (s : Fin n → Bool) :
    blockScore d (insert j t) s = blockScore d t s + d j * signValue (s j) := by
  simp only [blockScore, Finset.sum_insert hj]
  ring

/-- A block score does not see a locus outside its block. -/
theorem blockScore_flip {n : ℕ} (d : Fin n → ℝ) {t : Finset (Fin n)} {j : Fin n}
    (hj : j ∉ t) (s : Fin n → Bool) :
    blockScore d t (flipCoord j s) = blockScore d t s := by
  simp only [blockScore]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  have hij : i ≠ j := fun h ↦ hj (h ▸ hi)
  rw [flipCoord_ne j hij]

/-- Block scores are additive in their coefficient vectors. -/
theorem blockScore_sub {n : ℕ} (d1 d2 : Fin n → ℝ) (t : Finset (Fin n)) (s : Fin n → Bool) :
    blockScore d1 t s - blockScore d2 t s = blockScore (fun i ↦ d1 i - d2 i) t s := by
  simp only [blockScore, ← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl fun i _ ↦ by ring

/-- First Rademacher moment: a linear score has mean zero. -/
theorem sum_blockScore_mean {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s = 0 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s
          = blockScore d t s + d j * ((fun _ : Fin n → Bool ↦ (1 : ℝ)) s * signValue (s j)) := by
      intro s
      rw [blockScore_insert d hj s]
      ring
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, ← Finset.mul_sum, ih,
      sum_odd_vanishes j (fun _ ↦ (1 : ℝ)) (fun _ ↦ rfl)]
    ring

/-- There are `2ⁿ` configurations of `n` coordinates. -/
theorem card_config (n : ℕ) :
    (((Finset.univ : Finset (Fin n → Bool)).card : ℕ) : ℝ) = (2 : ℝ) ^ n := by
  rw [Finset.card_univ]
  simp

/-- Second Rademacher moment: `E(∑ dᵢGᵢ)² = ∑ dᵢ²`. -/
theorem sum_blockScore_sq {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 2
      = ((2 : ℝ) ^ n) * ∑ i ∈ t, d i ^ 2 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 2
          = blockScore d t s ^ 2 + d j ^ 2
            + 2 * d j * (blockScore d t s * signValue (s j)) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination (d j ^ 2) * hs
    have hinv : ∀ s : Fin n → Bool,
        blockScore d t (flipCoord j s) = blockScore d t s := fun s ↦ blockScore_flip d hj s
    have hodd : ∑ s : Fin n → Bool, blockScore d t s * signValue (s j) = 0 :=
      sum_odd_vanishes j (fun s ↦ blockScore d t s) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      ← Finset.mul_sum, ih, hodd, Finset.sum_const, nsmul_eq_mul, card_config n]
    simp only [Finset.sum_insert hj]
    ring

/-- Third Rademacher moment: a linear score has zero third moment. -/
theorem sum_blockScore_cube {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 3 = 0 := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 3
          = blockScore d t s ^ 3 + 3 * d j ^ 2 * blockScore d t s
            + (3 * d j * blockScore d t s ^ 2 + d j ^ 3) * signValue (s j) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination
        (3 * blockScore d t s * d j ^ 2 + d j ^ 3 * signValue (s j)) * hs
    have hinv : ∀ s : Fin n → Bool,
        3 * d j * blockScore d t (flipCoord j s) ^ 2 + d j ^ 3
          = 3 * d j * blockScore d t s ^ 2 + d j ^ 3 := by
      intro s
      rw [blockScore_flip d hj s]
    have hodd : ∑ s : Fin n → Bool,
        (3 * d j * blockScore d t s ^ 2 + d j ^ 3) * signValue (s j) = 0 :=
      sum_odd_vanishes j (fun s ↦ 3 * d j * blockScore d t s ^ 2 + d j ^ 3) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      ← Finset.mul_sum, ih, sum_blockScore_mean d t, hodd]
    ring

/-- **Fourth Rademacher moment**, the combinatorial core of PL Theorem 5.1:
`E(∑ dᵢGᵢ)⁴ = 3(∑ dᵢ²)² - 2∑ dᵢ⁴`. -/
theorem sum_blockScore_quartic {n : ℕ} (d : Fin n → ℝ) (t : Finset (Fin n)) :
    ∑ s : Fin n → Bool, blockScore d t s ^ 4
      = ((2 : ℝ) ^ n) * (3 * (∑ i ∈ t, d i ^ 2) ^ 2 - 2 * ∑ i ∈ t, d i ^ 4) := by
  induction t using Finset.induction_on with
  | empty => simp [blockScore]
  | @insert j t hj ih =>
    have hpt : ∀ s : Fin n → Bool,
        blockScore d (insert j t) s ^ 4
          = blockScore d t s ^ 4 + 6 * d j ^ 2 * blockScore d t s ^ 2 + d j ^ 4
            + (4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s)
              * signValue (s j) := by
      intro s
      rw [blockScore_insert d hj s]
      have hs : signValue (s j) ^ 2 = 1 := signValue_sq _
      linear_combination
        (6 * blockScore d t s ^ 2 * d j ^ 2
          + 4 * blockScore d t s * d j ^ 3 * signValue (s j)
          + d j ^ 4 * (signValue (s j) ^ 2 + 1)) * hs
    have hinv : ∀ s : Fin n → Bool,
        4 * d j * blockScore d t (flipCoord j s) ^ 3
            + 4 * d j ^ 3 * blockScore d t (flipCoord j s)
          = 4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s := by
      intro s
      rw [blockScore_flip d hj s]
    have hodd : ∑ s : Fin n → Bool,
        (4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s)
          * signValue (s j) = 0 :=
      sum_odd_vanishes j
        (fun s ↦ 4 * d j * blockScore d t s ^ 3 + 4 * d j ^ 3 * blockScore d t s) hinv
    rw [Finset.sum_congr rfl fun s _ ↦ hpt s, Finset.sum_add_distrib, Finset.sum_add_distrib,
      Finset.sum_add_distrib, ← Finset.mul_sum, ih, sum_blockScore_sq d t, hodd,
      Finset.sum_const, nsmul_eq_mul, card_config n]
    simp only [Finset.sum_insert hj]
    ring

/-! ## The genotype-and-noise law -/

/-- The law of PL (5.1) / DC (4.1): `n` independent fair signs, independent of an
arbitrary finite-support environmental noise law.  Independence is the product structure
of `mixture`, not a hypothesis. -/
def genotypeNoiseExp (n : ℕ) {V : Type*} [Fintype V] (noise : ExpFunctional V) :
    ExpFunctional ((Fin n → Bool) × V) :=
  mixture (uniformExp (Fin n → Bool)) (fun _ ↦ noise)

/-- Linearity over a three-term combination. -/
theorem eval_comb3 {Ω : Type*} (Ex : ExpFunctional Ω) (c0 c1 c2 : ℝ) (g1 g2 : Ω → ℝ) :
    Ex (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω) = c0 + c1 * Ex g1 + c2 * Ex g2 := by
  have h : (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω)
      = ((fun _ : Ω ↦ c0) + c1 • g1) + c2 • g2 := by
    funext ω
    simp
  rw [h, Ex.add_eval, Ex.add_eval, Ex.smul_eval, Ex.smul_eval, Ex.eval_const]

/-- Linearity over a five-term combination. -/
theorem eval_comb5 {Ω : Type*} (Ex : ExpFunctional Ω) (c0 c1 c2 c3 c4 : ℝ)
    (g1 g2 g3 g4 : Ω → ℝ) :
    Ex (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω + c3 * g3 ω + c4 * g4 ω)
      = c0 + c1 * Ex g1 + c2 * Ex g2 + c3 * Ex g3 + c4 * Ex g4 := by
  have h : (fun ω ↦ c0 + c1 * g1 ω + c2 * g2 ω + c3 * g3 ω + c4 * g4 ω)
      = (((fun _ : Ω ↦ c0) + c1 • g1) + c2 • g2 + c3 • g3) + c4 • g4 := by
    funext ω
    simp
  rw [h, Ex.add_eval, Ex.add_eval, Ex.add_eval, Ex.add_eval, Ex.smul_eval, Ex.smul_eval,
    Ex.smul_eval, Ex.smul_eval, Ex.eval_const]

/-- Uniform expectation over configurations is the normalized sum. -/
theorem uniform_geno_eq (n : ℕ) (F : (Fin n → Bool) → ℝ) :
    uniformExp (Fin n → Bool) F = ((2 : ℝ) ^ n)⁻¹ * ∑ s : Fin n → Bool, F s := by
  rw [uniformExp_apply, ← Finset.mul_sum]
  congr 1
  simp

/-- A genotype-only observable has its genotype expectation. -/
theorem exp_geno {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (F : (Fin n → Bool) → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ F p.1) = uniformExp (Fin n → Bool) F := by
  show uniformExp (Fin n → Bool) (fun s ↦ noise (fun _ ↦ F s)) = uniformExp (Fin n → Bool) F
  simp

/-- Genotype and noise observables factorize. -/
theorem exp_mul {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (F : (Fin n → Bool) → ℝ) (H : V → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ F p.1 * H p.2)
      = uniformExp (Fin n → Bool) F * noise H := by
  show uniformExp (Fin n → Bool) (fun s ↦ noise (fun e ↦ F s * H e)) = _
  have h1 : ∀ s : Fin n → Bool, noise (fun e ↦ F s * H e) = F s * noise H := by
    intro s
    have h2 : (fun e ↦ F s * H e) = (F s) • H := by
      funext e
      simp
    rw [h2, noise.smul_eval]
  simp only [h1]
  have h3 : (fun s ↦ F s * noise H) = (noise H) • F := by
    funext s
    simp [mul_comm]
  rw [h3, (uniformExp (Fin n → Bool)).smul_eval]
  ring

/-- Mean of a genotype-linear score plus independent noise. -/
theorem exp_lin_noise_mean {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) :
    genotypeNoiseExp n noise
        (fun p ↦ blockScore d Finset.univ p.1 + ξ p.2) = noise ξ := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ blockScore d Finset.univ s + ξ e)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ blockScore d Finset.univ s + ξ e)
        = blockScore d Finset.univ s + noise ξ := by
    intro s
    have hx : (fun e ↦ blockScore d Finset.univ s + ξ e)
        = fun e ↦ blockScore d Finset.univ s + 1 * ξ e := by
      funext e
      ring
    rw [hx, eval_affine]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s + noise ξ)
      = fun s ↦ noise ξ + 1 * blockScore d Finset.univ s := by
    funext s
    ring
  rw [hx, eval_affine, uniform_geno_eq, sum_blockScore_mean]
  ring

/-- Second moment of a genotype-linear score plus independent noise. -/
theorem exp_lin_noise_sq {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) (hmean : noise ξ = 0) :
    genotypeNoiseExp n noise
        (fun p ↦ (blockScore d Finset.univ p.1 + ξ p.2) ^ 2)
      = (∑ i, d i ^ 2) + noise (fun e ↦ ξ e ^ 2) := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)
        = blockScore d Finset.univ s ^ 2 + noise (fun e ↦ ξ e ^ 2) := by
    intro s
    have hx : (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 2)
        = fun e ↦ blockScore d Finset.univ s ^ 2
          + (2 * blockScore d Finset.univ s) * ξ e + 1 * ξ e ^ 2 := by
      funext e
      ring
    rw [hx, eval_comb3, hmean]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s ^ 2 + noise (fun e ↦ ξ e ^ 2))
      = fun s ↦ noise (fun e ↦ ξ e ^ 2) + 1 * blockScore d Finset.univ s ^ 2 := by
    funext s
    ring
  rw [hx, eval_affine, uniform_geno_eq, sum_blockScore_sq]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp
  ring

/-- **Fourth moment of a genotype-linear score plus independent noise**, PL Theorem 5.1.
The third noise moment appears multiplied by the vanishing first genotype moment, so it
never enters -- no hypothesis about it is needed. -/
theorem exp_lin_noise_quartic {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) (ξ : V → ℝ) (hmean : noise ξ = 0) :
    genotypeNoiseExp n noise
        (fun p ↦ (blockScore d Finset.univ p.1 + ξ p.2) ^ 4)
      = 3 * (∑ i, d i ^ 2) ^ 2 - 2 * (∑ i, d i ^ 4)
        + 6 * (∑ i, d i ^ 2) * noise (fun e ↦ ξ e ^ 2) + noise (fun e ↦ ξ e ^ 4) := by
  show uniformExp (Fin n → Bool)
      (fun s ↦ noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)) = _
  have hin : ∀ s : Fin n → Bool,
      noise (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)
        = blockScore d Finset.univ s ^ 4
          + 6 * blockScore d Finset.univ s ^ 2 * noise (fun e ↦ ξ e ^ 2)
          + 4 * blockScore d Finset.univ s * noise (fun e ↦ ξ e ^ 3)
          + noise (fun e ↦ ξ e ^ 4) := by
    intro s
    have hx : (fun e ↦ (blockScore d Finset.univ s + ξ e) ^ 4)
        = fun e ↦ blockScore d Finset.univ s ^ 4
          + (4 * blockScore d Finset.univ s ^ 3) * ξ e
          + (6 * blockScore d Finset.univ s ^ 2) * ξ e ^ 2
          + (4 * blockScore d Finset.univ s) * ξ e ^ 3 + 1 * ξ e ^ 4 := by
      funext e
      ring
    rw [hx, eval_comb5, hmean]
    ring
  simp only [hin]
  have hx : (fun s : Fin n → Bool ↦ blockScore d Finset.univ s ^ 4
        + 6 * blockScore d Finset.univ s ^ 2 * noise (fun e ↦ ξ e ^ 2)
        + 4 * blockScore d Finset.univ s * noise (fun e ↦ ξ e ^ 3)
        + noise (fun e ↦ ξ e ^ 4))
      = fun s ↦ noise (fun e ↦ ξ e ^ 4) + 1 * blockScore d Finset.univ s ^ 4
        + (6 * noise (fun e ↦ ξ e ^ 2)) * blockScore d Finset.univ s ^ 2
        + (4 * noise (fun e ↦ ξ e ^ 3)) * blockScore d Finset.univ s
        + 0 * (fun _ : Fin n → Bool ↦ (0 : ℝ)) s := by
    funext s
    ring
  rw [hx, eval_comb5, uniform_geno_eq, uniform_geno_eq, uniform_geno_eq,
    sum_blockScore_quartic, sum_blockScore_sq, sum_blockScore_mean]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp
  ring


/-! ## The realized architecture and its three report laws -/

/-- `A_σ = ∑ᵢ wᵢσᵢ` with `wᵢ = aᵢ²`, the weighted alignment of the deployed architecture
with the source architecture (PL (5.1)). -/
def alignment {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) : ℝ :=
  ∑ i, a i ^ 2 * signValue (σ i)

/-- `∑_{σᵢ = -1} wᵢ²`, the reversed-effect weight concentration of PL (5.3), written with
the `(1 - σᵢ)/2` indicator of a reversed locus. -/
def reversedWeightSq {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) : ℝ :=
  ∑ i, (a i ^ 2) ^ 2 * ((1 - signValue (σ i)) / 2)

/-- The reversed-effect weight concentration is the sum over the reversed loci. -/
theorem reversedWeightSq_eq_filter {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) :
    reversedWeightSq a σ
      = ∑ i ∈ Finset.univ.filter (fun i ↦ σ i = false), (a i ^ 2) ^ 2 := by
  rw [Finset.sum_filter]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  cases h : σ i
  · simp [signValue, TraitPortabilityRange.sign]
  · simp [signValue, TraitPortabilityRange.sign]

/-- The residual coefficient vector `dᵢ = aᵢ(σᵢ - 1)` of PL Theorem 5.1. -/
def residualCoeff {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) : Fin n → ℝ :=
  fun i ↦ a i * signValue (σ i) - a i

/-- `∑ dᵢ² = 2(∑ aᵢ² - A_σ)`: the genetic residual variance `v_g` of PL Theorem 5.1. -/
theorem residualCoeff_sq_sum {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) :
    ∑ i, residualCoeff a σ i ^ 2 = 2 * (∑ i, a i ^ 2) - 2 * alignment a σ := by
  have hpt : ∀ i : Fin n,
      residualCoeff a σ i ^ 2 = 2 * a i ^ 2 - 2 * (a i ^ 2 * signValue (σ i)) := by
    intro i
    have hs : signValue (σ i) ^ 2 = 1 := signValue_sq _
    simp only [residualCoeff]
    linear_combination (a i ^ 2) * hs
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, Finset.sum_sub_distrib, ← Finset.mul_sum,
    ← Finset.mul_sum]
  rfl

/-- `∑ dᵢ⁴ = 16 ∑_{σᵢ = -1} wᵢ²`, the correction term of PL (5.3). -/
theorem residualCoeff_quartic_sum {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) :
    ∑ i, residualCoeff a σ i ^ 4 = 16 * reversedWeightSq a σ := by
  have hpt : ∀ i : Fin n,
      residualCoeff a σ i ^ 4 = 16 * ((a i ^ 2) ^ 2 * ((1 - signValue (σ i)) / 2)) := by
    intro i
    have hs : signValue (σ i) ^ 2 = 1 := signValue_sq _
    simp only [residualCoeff]
    linear_combination
      (a i ^ 4 * (signValue (σ i) ^ 2 - 4 * signValue (σ i) + 7)) * hs
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, ← Finset.mul_sum]
  rfl

/-- Reversing effect signs does not change the genetic variance. -/
theorem sum_effect_sq {n : ℕ} (a : Fin n → ℝ) (σ : Fin n → Bool) :
    ∑ i, (a i * signValue (σ i)) ^ 2 = ∑ i, a i ^ 2 := by
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  have hs : signValue (σ i) ^ 2 = 1 := signValue_sq _
  linear_combination (a i ^ 2) * hs

/-- Block scores are additive in their coefficient vectors. -/
theorem blockScore_add {n : ℕ} (d1 d2 : Fin n → ℝ) (t : Finset (Fin n)) (s : Fin n → Bool) :
    blockScore d1 t s + blockScore d2 t s = blockScore (fun i ↦ d1 i + d2 i) t s := by
  simp only [blockScore, ← Finset.sum_add_distrib]
  exact Finset.sum_congr rfl fun i _ ↦ by ring

/-- Polarization: the cross moment of two linear genotype scores. -/
theorem sum_blockScore_cross {n : ℕ} (d1 d2 : Fin n → ℝ) :
    ∑ s : Fin n → Bool, blockScore d1 Finset.univ s * blockScore d2 Finset.univ s
      = ((2 : ℝ) ^ n) * ((∑ i, d1 i ^ 2) + (∑ i, d2 i ^ 2) - ∑ i, (d1 i - d2 i) ^ 2) / 2 := by
  have hpt : ∀ s : Fin n → Bool,
      blockScore d1 Finset.univ s * blockScore d2 Finset.univ s
        = (blockScore d1 Finset.univ s ^ 2 + blockScore d2 Finset.univ s ^ 2
          - blockScore (fun i ↦ d1 i - d2 i) Finset.univ s ^ 2) / 2 := by
    intro s
    rw [← blockScore_sub]
    ring
  rw [Finset.sum_congr rfl fun s _ ↦ hpt s, ← Finset.sum_div, Finset.sum_sub_distrib,
    Finset.sum_add_distrib, sum_blockScore_sq, sum_blockScore_sq, sum_blockScore_sq]
  ring

/-- A genotype-linear score has mean zero under the genotype-and-noise law. -/
theorem exp_blockScore_mean {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ blockScore d Finset.univ p.1) = 0 := by
  rw [exp_geno, uniform_geno_eq, sum_blockScore_mean]
  ring

/-- Second moment of a genotype-linear score under the genotype-and-noise law. -/
theorem exp_blockScore_sq {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d : Fin n → ℝ) :
    genotypeNoiseExp n noise (fun p ↦ blockScore d Finset.univ p.1 ^ 2) = ∑ i, d i ^ 2 := by
  rw [exp_geno noise (fun s ↦ blockScore d Finset.univ s ^ 2), uniform_geno_eq,
    sum_blockScore_sq]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp

/-- Cross moment of two genotype-linear scores under the genotype-and-noise law. -/
theorem exp_blockScore_cross {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (d1 d2 : Fin n → ℝ) :
    genotypeNoiseExp n noise
        (fun p ↦ blockScore d1 Finset.univ p.1 * blockScore d2 Finset.univ p.1)
      = ((∑ i, d1 i ^ 2) + (∑ i, d2 i ^ 2) - ∑ i, (d1 i - d2 i) ^ 2) / 2 := by
  rw [exp_geno noise (fun s ↦ blockScore d1 Finset.univ s * blockScore d2 Finset.univ s),
    uniform_geno_eq, sum_blockScore_cross]
  have h2 : ((2 : ℝ) ^ n) ≠ 0 := by positivity
  field_simp

/-- **The deployed population generated by one realized effect architecture**, PL (5.1) /
DC (4.1).  The expectation is the exhibited product of `n` fair signs with the noise law;
the scored and causal codings are the `±1` genotypes; the causal effects are `aᵢσᵢ`; and
the residual is the environmental noise `ε`.  Nothing about the reports is built in. -/
def architecturePop (n : ℕ) {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    DeploymentPopulation ((Fin n → Bool) × V) (Fin n) (Fin n) where
  E := genotypeNoiseExp n noise
  X := fun p i ↦ signValue (p.1 i)
  C := fun p i ↦ signValue (p.1 i)
  β := fun i ↦ a i * signValue (σ i)
  h := fun p ↦ ξ p.2

/-- The population expectation is the genotype-and-noise law. -/
theorem architecturePop_exp {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    (architecturePop n noise a σ ξ).E = genotypeNoiseExp n noise := rfl

/-- The deployed score is `S = ∑ aᵢGᵢ`. -/
theorem architecturePop_score {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    (architecturePop n noise a σ ξ).score a = fun p ↦ blockScore a Finset.univ p.1 := rfl

/-- The phenotype is `Y_σ = ∑ aᵢσᵢGᵢ + ε`. -/
theorem architecturePop_phenotype {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    (architecturePop n noise a σ ξ).phenotype
      = fun p ↦ blockScore (fun i ↦ a i * signValue (σ i)) Finset.univ p.1 + ξ p.2 := rfl

/-- The residual is the reversed-effect block score plus the noise. -/
theorem architecturePop_residual {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    (fun p ↦ (architecturePop n noise a σ ξ).phenotype p
        - (architecturePop n noise a σ ξ).score a p)
      = fun p ↦ blockScore (residualCoeff a σ) Finset.univ p.1 + ξ p.2 := by
  funext p
  have h3 : blockScore (residualCoeff a σ) Finset.univ p.1
      = blockScore (fun i ↦ a i * signValue (σ i)) Finset.univ p.1
        - blockScore a Finset.univ p.1 := (blockScore_sub _ _ _ _).symm
  rw [architecturePop_phenotype, architecturePop_score, h3]
  ring

/-- The squared residual of the realized architecture, written through the reversed-effect
block score and the noise.  Shared by the mean-squared-error and loss-variance laws. -/
theorem architecturePop_residual_sq {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) :
    (fun p : (Fin n → Bool) × V ↦ ((architecturePop n noise a σ ξ).phenotype p
        - (architecturePop n noise a σ ξ).score a p) ^ 2)
      = fun p ↦ (blockScore (residualCoeff a σ) Finset.univ p.1 + ξ p.2) ^ 2 := by
  have hres := architecturePop_residual noise a σ ξ
  funext p
  rw [show (architecturePop n noise a σ ξ).phenotype p
      - (architecturePop n noise a σ ξ).score a p
      = blockScore (residualCoeff a σ) Finset.univ p.1 + ξ p.2 from congrFun hres p]

/-- **Unit genetic variance**: the deployed score has variance one. -/
theorem architecture_score_variance {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1) :
    (architecturePop n noise a σ ξ).scoreVariance a = 1 := by
  rw [DeploymentPopulation.scoreVariance, variance_eq_expect_sq_sub_sq_mean,
    architecturePop_exp, architecturePop_score, exp_blockScore_mean, exp_blockScore_sq,
    hnorm]
  ring

/-- **Outcome variance** `1 + ν`, for every architecture. -/
theorem architecture_outcome_variance {n : ℕ} {V : Type*} [Fintype V]
    (noise : ExpFunctional V) (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ)
    (hnorm : ∑ i, a i ^ 2 = 1) (hmean : noise ξ = 0) :
    (architecturePop n noise a σ ξ).outcomeVariance = 1 + noise (fun e ↦ ξ e ^ 2) := by
  rw [DeploymentPopulation.outcomeVariance, variance_eq_expect_sq_sub_sq_mean,
    architecturePop_exp, architecturePop_phenotype, exp_lin_noise_mean,
    exp_lin_noise_sq noise _ ξ hmean, sum_effect_sq, hnorm, hmean]
  ring

/-- **Predictive covariance** `Cov(S, Y_σ) = A_σ`. -/
theorem architecture_predictive_covariance {n : ℕ} {V : Type*} [Fintype V]
    (noise : ExpFunctional V) (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ)
    (hmean : noise ξ = 0) :
    (architecturePop n noise a σ ξ).predictiveCovariance a = alignment a σ := by
  have hsplit : (fun p : (Fin n → Bool) × V ↦ blockScore a Finset.univ p.1
        * (blockScore (fun i ↦ a i * signValue (σ i)) Finset.univ p.1 + ξ p.2))
      = (fun p : (Fin n → Bool) × V ↦ blockScore a Finset.univ p.1
          * blockScore (fun i ↦ a i * signValue (σ i)) Finset.univ p.1)
        + (fun p : (Fin n → Bool) × V ↦ blockScore a Finset.univ p.1 * ξ p.2) := by
    funext p
    simp only [Pi.add_apply]
    ring
  rw [DeploymentPopulation.predictiveCovariance, covariance_eq_expect_mul_sub_means,
    architecturePop_exp, architecturePop_score, architecturePop_phenotype, hsplit,
    (genotypeNoiseExp n noise).add_eval, exp_blockScore_cross,
    exp_mul noise (fun s ↦ blockScore a Finset.univ s) ξ, uniform_geno_eq,
    sum_blockScore_mean, exp_blockScore_mean, exp_lin_noise_mean, hmean, sum_effect_sq]
  have hres : ∑ i, (a i - a i * signValue (σ i)) ^ 2
      = 2 * (∑ i, a i ^ 2) - 2 * alignment a σ := by
    have hpt : ∀ i : Fin n,
        (a i - a i * signValue (σ i)) ^ 2
          = 2 * a i ^ 2 - 2 * (a i ^ 2 * signValue (σ i)) := by
      intro i
      have hs : signValue (σ i) ^ 2 = 1 := signValue_sq _
      linear_combination (a i ^ 2) * hs
    rw [Finset.sum_congr rfl fun i _ ↦ hpt i, Finset.sum_sub_distrib, ← Finset.mul_sum,
      ← Finset.mul_sum]
    rfl
  rw [hres]
  ring

/-- **PL (5.2), first boxed formula / DC (4.2), first boxed formula**: the conditional
squared correlation of one realized architecture is `A_σ² / (1 + ν)`. -/
theorem architecture_r2 {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1)
    (hmean : noise ξ = 0) :
    (architecturePop n noise a σ ξ).r2 a
      = alignment a σ ^ 2 / (1 + noise (fun e ↦ ξ e ^ 2)) := by
  rw [DeploymentPopulation.r2, architecture_predictive_covariance noise a σ ξ hmean,
    architecture_score_variance noise a σ ξ hnorm,
    architecture_outcome_variance noise a σ ξ hnorm hmean]
  ring

/-- **PL (5.2), second boxed formula / DC (4.2), second boxed formula**: the conditional
mean squared error is `ν + 2(1 - A_σ)`. -/
theorem architecture_mse {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1)
    (hmean : noise ξ = 0) :
    (architecturePop n noise a σ ξ).deployedMse a
      = noise (fun e ↦ ξ e ^ 2) + 2 * (1 - alignment a σ) := by
  have hfun := architecturePop_residual_sq noise a σ ξ
  rw [DeploymentPopulation.deployedMse, expMse, architecturePop_exp, hfun,
    exp_lin_noise_sq noise _ ξ hmean, residualCoeff_sq_sum, hnorm]
  ring

/-- **PL (5.3) / DC (4.3)**: the exact variance of the individual squared loss generated by
one realized architecture.  Only `E ε = 0` is assumed about the noise beyond the finite
moments it has by construction; the third noise moment cancels against the vanishing first
genotype moment. -/
theorem architecture_loss_variance {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1)
    (hmean : noise ξ = 0) :
    variance (architecturePop n noise a σ ξ).E
        (fun p ↦ ((architecturePop n noise a σ ξ).phenotype p
          - (architecturePop n noise a σ ξ).score a p) ^ 2)
      = 2 * (2 * (1 - alignment a σ)) ^ 2 - 32 * reversedWeightSq a σ
        + 4 * noise (fun e ↦ ξ e ^ 2) * (2 * (1 - alignment a σ))
        + noise (fun e ↦ ξ e ^ 4) - noise (fun e ↦ ξ e ^ 2) ^ 2 := by
  have hfun := architecturePop_residual_sq noise a σ ξ
  have hfour : (fun p : (Fin n → Bool) × V ↦
        ((blockScore (residualCoeff a σ) Finset.univ p.1 + ξ p.2) ^ 2) ^ 2)
      = fun p ↦ (blockScore (residualCoeff a σ) Finset.univ p.1 + ξ p.2) ^ 4 := by
    funext p
    ring
  rw [architecturePop_exp, hfun, variance_eq_expect_sq_sub_sq_mean, hfour,
    exp_lin_noise_quartic noise _ ξ hmean, exp_lin_noise_sq noise _ ξ hmean,
    residualCoeff_sq_sum, residualCoeff_quartic_sum, hnorm]
  ring


/-! ## The equal-weight specialization DC (4.2) / (4.3) -/

/-- The noise variance is nonnegative, so `1 + ν` never vanishes. -/
theorem noise_var_nonneg {V : Type*} [Fintype V] (noise : ExpFunctional V) (ξ : V → ℝ) :
    0 ≤ noise (fun e ↦ ξ e ^ 2) := noise.nonneg_eval _ fun e ↦ sq_nonneg _

/-- `M(σ) = ∑ᵢ σᵢ = 2 N(σ) - n`, tying the architecture's sign sum to the occupied count
of `Descent.Portability.ConvexOrderCoupling`. -/
theorem sum_signValue_eq {n : ℕ} (σ : Fin n → Bool) :
    ∑ i, signValue (σ i)
      = 2 * ((ConvexOrderCoupling.occupiedCount σ : ℕ) : ℝ) - (n : ℝ) := by
  have hpt : ∀ i : Fin n, signValue (σ i) = 2 * (if σ i = true then (1 : ℝ) else 0) - 1 := by
    intro i
    cases h : σ i
    · simp [signValue, TraitPortabilityRange.sign]
    · simp only [signValue, TraitPortabilityRange.sign]
      norm_num
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, Finset.sum_sub_distrib, ← Finset.mul_sum,
    ← ConvexOrderCoupling.occupiedCount_eq_sum, Finset.sum_const, Finset.card_univ,
    Fintype.card_fin, nsmul_eq_mul, mul_one]

/-- `J(σ)`, the number of reversed effects of DC §4.1. -/
def reversedCount {n : ℕ} (σ : Fin n → Bool) : ℝ :=
  (n : ℝ) - ((ConvexOrderCoupling.occupiedCount σ : ℕ) : ℝ)

/-- `M(σ) = n - 2 J(σ)`. -/
theorem sum_signValue_reversed {n : ℕ} (σ : Fin n → Bool) :
    ∑ i, signValue (σ i) = (n : ℝ) - 2 * reversedCount σ := by
  rw [sum_signValue_eq]
  simp only [reversedCount]
  ring

/-- The equal-weight score `aᵢ = n^{-1/2}` of DC (4.1). -/
def equalWeights (n : ℕ) : Fin n → ℝ := fun _ ↦ (Real.sqrt (n : ℝ))⁻¹

/-- Each equal weight carries `wᵢ = 1/n`. -/
theorem equalWeights_sq {n : ℕ} (hn : 0 < n) (i : Fin n) :
    equalWeights n i ^ 2 = ((n : ℝ))⁻¹ := by
  simp only [equalWeights]
  rw [inv_pow, Real.sq_sqrt (Nat.cast_nonneg n)]

/-- The equal-weight score has unit genetic variance. -/
theorem equalWeights_norm {n : ℕ} (hn : 0 < n) : ∑ i, equalWeights n i ^ 2 = 1 := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [Finset.sum_congr rfl fun i _ ↦ equalWeights_sq hn i, Finset.sum_const, Finset.card_univ,
    Fintype.card_fin, nsmul_eq_mul]
  field_simp

/-- With equal weights, `A_σ = M(σ)/n = (n - 2J)/n`. -/
theorem equalWeights_alignment {n : ℕ} (hn : 0 < n) (σ : Fin n → Bool) :
    alignment (equalWeights n) σ = ((n : ℝ) - 2 * reversedCount σ) / (n : ℝ) := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  have hpt : ∀ i : Fin n, equalWeights n i ^ 2 * signValue (σ i)
      = ((n : ℝ))⁻¹ * signValue (σ i) := by
    intro i
    rw [equalWeights_sq hn i]
  simp only [alignment]
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, ← Finset.mul_sum, sum_signValue_reversed]
  field_simp

/-- With equal weights, `∑_{σᵢ = -1} wᵢ² = J/n²`. -/
theorem equalWeights_reversedWeightSq {n : ℕ} (hn : 0 < n) (σ : Fin n → Bool) :
    reversedWeightSq (equalWeights n) σ = reversedCount σ / (n : ℝ) ^ 2 := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  have hpt : ∀ i : Fin n, (equalWeights n i ^ 2) ^ 2 * ((1 - signValue (σ i)) / 2)
      = (((n : ℝ))⁻¹) ^ 2 * ((1 - signValue (σ i)) / 2) := by
    intro i
    rw [equalWeights_sq hn i]
  have hsum : ∑ i : Fin n, ((1 - signValue (σ i)) / 2) = reversedCount σ := by
    have h1 : ∀ i : Fin n,
        (1 - signValue (σ i)) / 2 = (1 : ℝ) / 2 - (1 / 2) * signValue (σ i) := fun i ↦ by ring
    rw [Finset.sum_congr rfl fun i _ ↦ h1 i, Finset.sum_sub_distrib, ← Finset.mul_sum,
      sum_signValue_reversed, Finset.sum_const, Finset.card_univ, Fintype.card_fin,
      nsmul_eq_mul]
    ring
  simp only [reversedWeightSq]
  rw [Finset.sum_congr rfl fun i _ ↦ hpt i, ← Finset.mul_sum, hsum]
  field_simp

/-- **DC (4.2), first boxed formula**: with equal weights the conditional squared
correlation is `M(σ)² / (n²(1 + ν))`. -/
theorem equal_weight_r2 {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (σ : Fin n → Bool) (ξ : V → ℝ) (hn : 0 < n) (hmean : noise ξ = 0) :
    (architecturePop n noise (equalWeights n) σ ξ).r2 (equalWeights n)
      = (∑ i, signValue (σ i)) ^ 2 / ((n : ℝ) ^ 2 * (1 + noise (fun e ↦ ξ e ^ 2))) := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  have hc : (1 + noise (fun e ↦ ξ e ^ 2)) ≠ 0 := by
    have := noise_var_nonneg noise ξ
    intro hcon
    linarith
  rw [architecture_r2 noise _ σ ξ (equalWeights_norm hn) hmean, equalWeights_alignment hn,
    sum_signValue_reversed]
  field_simp

/-- **DC (4.2), second boxed formula**: with equal weights the conditional mean squared
error is `ν + 4J(σ)/n`. -/
theorem equal_weight_mse {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (σ : Fin n → Bool) (ξ : V → ℝ) (hn : 0 < n) (hmean : noise ξ = 0) :
    (architecturePop n noise (equalWeights n) σ ξ).deployedMse (equalWeights n)
      = noise (fun e ↦ ξ e ^ 2) + 4 * reversedCount σ / (n : ℝ) := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [architecture_mse noise _ σ ξ (equalWeights_norm hn) hmean, equalWeights_alignment hn]
  field_simp
  ring

/-- **DC (4.3)**: with equal weights the individual squared-loss variance is
`32 J(J-1)/n² + 16 J ν/n + κ - ν²`. -/
theorem equal_weight_loss_variance {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (σ : Fin n → Bool) (ξ : V → ℝ) (hn : 0 < n) (hmean : noise ξ = 0) :
    variance (architecturePop n noise (equalWeights n) σ ξ).E
        (fun p ↦ ((architecturePop n noise (equalWeights n) σ ξ).phenotype p
          - (architecturePop n noise (equalWeights n) σ ξ).score (equalWeights n) p) ^ 2)
      = 32 * reversedCount σ * (reversedCount σ - 1) / (n : ℝ) ^ 2
        + 16 * reversedCount σ * noise (fun e ↦ ξ e ^ 2) / (n : ℝ)
        + noise (fun e ↦ ξ e ^ 4) - noise (fun e ↦ ξ e ^ 2) ^ 2 := by
  have hne : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hn.ne'
  rw [architecture_loss_variance noise _ σ ξ (equalWeights_norm hn) hmean,
    equalWeights_alignment hn, equalWeights_reversedWeightSq hn]
  field_simp
  ring

/-! ## Averaging architectures is not pooling them, and the pathwise report -/

/-- **DC Proposition 4.6, the aggregation gap.** Mean conditional squared correlation
exceeds the pooled squared correlation by exactly `Var(A_Σ)/(1 + ν)`.  Both sides are
computed from the same architecture law; nothing is substituted for the pooling rule. -/
theorem aggregation_gap {n : ℕ} {V A : Type*} [Fintype V] [Fintype A]
    (noise : ExpFunctional V) (arch : ExpFunctional A) (arche : A → (Fin n → Bool))
    (a : Fin n → ℝ) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1) (hmean : noise ξ = 0) :
    arch (fun d ↦ (architecturePop n noise a (arche d) ξ).r2 a)
        - arch (fun d ↦ alignment a (arche d)) ^ 2 / (1 + noise (fun e ↦ ξ e ^ 2))
      = variance arch (fun d ↦ alignment a (arche d)) / (1 + noise (fun e ↦ ξ e ^ 2)) := by
  have hc : (1 + noise (fun e ↦ ξ e ^ 2)) ≠ 0 := by
    have := noise_var_nonneg noise ξ
    intro hcon
    linarith
  have hfun : (fun d ↦ (architecturePop n noise a (arche d) ξ).r2 a)
      = (1 + noise (fun e ↦ ξ e ^ 2))⁻¹ • (fun d ↦ alignment a (arche d) ^ 2) := by
    funext d
    rw [architecture_r2 noise a (arche d) ξ hnorm hmean]
    simp only [Pi.smul_apply, smul_eq_mul]
    ring
  rw [hfun, arch.smul_eval, variance_eq_expect_sq_sub_sq_mean]
  field_simp

/-- Conditional mean loss `a_d = ν + 2(1 - A_{σ_d})` in cell `d`, DC §4.4. -/
def cellLossMean {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) : ℝ :=
  noise (fun e ↦ ξ e ^ 2) + 2 * (1 - alignment a σ)

/-- Conditional loss variance `b_d` in cell `d`, DC §4.4. -/
def cellLossVar {n : ℕ} {V : Type*} [Fintype V] (noise : ExpFunctional V)
    (a : Fin n → ℝ) (σ : Fin n → Bool) (ξ : V → ℝ) : ℝ :=
  2 * (2 * (1 - alignment a σ)) ^ 2 - 32 * reversedWeightSq a σ
    + 4 * noise (fun e ↦ ξ e ^ 2) * (2 * (1 - alignment a σ))
    + noise (fun e ↦ ξ e ^ 4) - noise (fun e ↦ ξ e ^ 2) ^ 2

/-- **DC Theorem 4.5, the exact pathwise distance-explainability decomposition.**
Total individual-loss variance over the realized collection of cell architectures splits
into the mean conditional loss variance plus the variance of the conditional mean loss.
Each cell carries its own realized architecture, so this is a function of the whole
collection. -/
theorem pathwise_loss_variance_split {n : ℕ} {V D : Type*} [Fintype V]
    (noise : ExpFunctional V) (cells : ExpFunctional D) (arche : D → (Fin n → Bool))
    (a : Fin n → ℝ) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1) (hmean : noise ξ = 0) :
    variance (mixture cells (fun _ ↦ genotypeNoiseExp n noise))
        (fun z ↦ ((architecturePop n noise a (arche z.1) ξ).phenotype z.2
          - (architecturePop n noise a (arche z.1) ξ).score a z.2) ^ 2)
      = cells (fun d ↦ cellLossVar noise a (arche d) ξ)
        + variance cells (fun d ↦ cellLossMean noise a (arche d) ξ) := by
  rw [total_variance]
  congr 1
  · exact congrArg cells.eval
      (funext fun d ↦ architecture_loss_variance noise a (arche d) ξ hnorm hmean)
  · exact congrArg (variance cells)
      (funext fun d ↦ architecture_mse noise a (arche d) ξ hnorm hmean)

/-- **DC (4.9)**: the explainable fraction `η_D` is the ratio of the between-cell variance
of the conditional mean loss to that variance plus the mean conditional loss variance.
It is a function of the whole realized collection of architectures, not a ratio of
separately averaged numerator and denominator. -/
theorem pathwise_distance_explainability {n : ℕ} {V D : Type*} [Fintype V]
    (noise : ExpFunctional V) (cells : ExpFunctional D) (arche : D → (Fin n → Bool))
    (a : Fin n → ℝ) (ξ : V → ℝ) (hnorm : ∑ i, a i ^ 2 = 1) (hmean : noise ξ = 0) :
    explainableFraction (variance cells (fun d ↦ cellLossMean noise a (arche d) ξ))
        (variance (mixture cells (fun _ ↦ genotypeNoiseExp n noise))
          (fun z ↦ ((architecturePop n noise a (arche z.1) ξ).phenotype z.2
            - (architecturePop n noise a (arche z.1) ξ).score a z.2) ^ 2))
      = variance cells (fun d ↦ cellLossMean noise a (arche d) ξ)
        / (variance cells (fun d ↦ cellLossMean noise a (arche d) ξ)
          + cells (fun d ↦ cellLossVar noise a (arche d) ξ)) := by
  rw [explainableFraction, Descent.Core.ratio,
    pathwise_loss_variance_split noise cells arche a ξ hnorm hmean, add_comm]

end

end Descent.Portability.TurnoverArchitectureMetrics
