/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.MarginalTurnoverRegion

assert_below Descent.Decision Descent.Program

/-!
# The exact finite-horizon coupling polytope

Each locus has a prescribed one-locus transition law; a coadapted coupling is a
joint next-state kernel, allowed to depend on the whole past, whose one-locus
marginals are the prescribed ones. UPT Theorem 5.3 says the complete collection
of coadapted path laws up to a finite horizon is exactly the set of nonnegative
history masses obeying normalisation, prefix flow (5.3), and the marginal
transition constraints (5.4). Both inclusions are proved here: a path law built
from a coadapted kernel family satisfies the constraints, and conversely every
solution of the constraints is reproduced by the conditional kernel it defines,
with the independent product coupling used at zero-mass prefixes and beyond the
horizon. The polytope is nonempty (the independent product coupling) and convex,
so every intermediate value of any finite-horizon path report is attained.

Histories are lists with the most recent state first, so a kernel family is
indexed by the history itself and no dependent-length bookkeeping is needed. The
loci share one finite state alphabet `Z`; the manuscript allows a different
alphabet at each locus, which is a relabelling of this statement and is noted in
the accompanying report.

## Empirical status

None. The bodies here are algebra: an initial law, a joint kernel family and the
prescribed one-locus kernels are inputs, and every definition multiplies or sums
them along a history. No definition names a measurable quantity or carries a
fitted constant.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Portability.TurnoverCouplingPolytope

open Foundations

noncomputable section

variable {ι : Type*} {Z : Type*}

section PathLaws

/-- **The path law** generated by an initial law and a family of joint transition kernels.
A history is a list with the most recent state first. -/
def pathLaw (μ : (ι → Z) → ℝ) (J : List (ι → Z) → (ι → Z) → ℝ) : List (ι → Z) → ℝ
  | [] => 1
  | [a] => μ a
  | a :: z :: h => pathLaw μ J (z :: h) * J (z :: h) a

/-- The empty history carries unit mass. -/
@[simp] theorem pathLaw_nil (μ : (ι → Z) → ℝ) (J : List (ι → Z) → (ι → Z) → ℝ) :
    pathLaw μ J [] = 1 := rfl

/-- A one-state history carries the initial law. -/
@[simp] theorem pathLaw_single (μ : (ι → Z) → ℝ) (J : List (ι → Z) → (ι → Z) → ℝ)
    (a : ι → Z) : pathLaw μ J [a] = μ a := rfl

/-- Successive multiplication along the path. -/
@[simp] theorem pathLaw_cons (μ : (ι → Z) → ℝ) (J : List (ι → Z) → (ι → Z) → ℝ)
    (a z : ι → Z) (h : List (ι → Z)) :
    pathLaw μ J (a :: z :: h) = pathLaw μ J (z :: h) * J (z :: h) a := rfl

end PathLaws

section Kernels

variable [Fintype ι]

/-- **The independent product coupling**: every locus moves by its own kernel, independently
of the others. -/
def productKernel (K : ℕ → ι → (ι → Z) → Z → ℝ) : List (ι → Z) → (ι → Z) → ℝ
  | [] => fun _ ↦ 0
  | z :: rest => fun a ↦ ∏ i, K rest.length i z (a i)

/-- Value of the product coupling at a nonempty history. -/
@[simp] theorem productKernel_cons (K : ℕ → ι → (ι → Z) → Z → ℝ) (z : ι → Z)
    (rest : List (ι → Z)) (a : ι → Z) :
    productKernel K (z :: rest) a = ∏ i, K rest.length i z (a i) := rfl

/-- **The conditional kernel read off a feasible history-mass vector**, with the independent
product coupling used at zero-mass prefixes and beyond the horizon. -/
def condKernel (K : ℕ → ι → (ι → Z) → Z → ℝ) (T : ℕ) (γ : List (ι → Z) → ℝ) :
    List (ι → Z) → (ι → Z) → ℝ
  | [] => fun _ ↦ 0
  | z :: h => fun a ↦ if h.length + 1 ≤ T ∧ γ (z :: h) ≠ 0
      then γ (a :: z :: h) / γ (z :: h) else ∏ i, K h.length i z (a i)

/-- **Value of the conditional kernel at a prefix of positive mass inside the horizon.**
The premise supplies the nonvanishing denominator the quotient needs. -/
theorem condKernel_cons_pos (K : ℕ → ι → (ι → Z) → Z → ℝ) (T : ℕ) (γ : List (ι → Z) → ℝ)
    (z : ι → Z) (h : List (ι → Z)) (a : ι → Z)
    (hcase : h.length + 1 ≤ T ∧ γ (z :: h) ≠ 0) :
    condKernel K T γ (z :: h) a = γ (a :: z :: h) / γ (z :: h) := if_pos hcase

/-- Value of the conditional kernel at a zero-mass prefix or beyond the horizon: there it is
the independent product coupling. -/
theorem condKernel_cons_neg (K : ℕ → ι → (ι → Z) → Z → ℝ) (T : ℕ) (γ : List (ι → Z) → ℝ)
    (z : ι → Z) (h : List (ι → Z)) (a : ι → Z)
    (hcase : ¬(h.length + 1 ≤ T ∧ γ (z :: h) ≠ 0)) :
    condKernel K T γ (z :: h) a = productKernel K (z :: h) a := if_neg hcase

end Kernels

variable [Fintype ι] [DecidableEq ι] [Fintype Z] [DecidableEq Z]

section ProductSums

omit [DecidableEq Z] in
/-- A sum over joint states of a coordinatewise product factorises. -/
theorem sum_prod_pi (f : ι → Z → ℝ) : ∑ a : ι → Z, ∏ i, f i (a i) = ∏ i, ∑ b, f i b :=
  (Fintype.prod_sum f).symm

/-- The `i`-marginal of a product law over joint states is its `i`-th factor. -/
theorem sum_prod_pi_marginal (f : ι → Z → ℝ) (hsum : ∀ i, ∑ b, f i b = 1) (i0 : ι) (b0 : Z) :
    ∑ a ∈ Finset.univ.filter fun a : ι → Z ↦ a i0 = b0, ∏ i, f i (a i) = f i0 b0 := by
  rw [Finset.sum_filter]
  have hone : ∀ g : ι → ℝ, ∏ i, (if i = i0 then g i else 1) = g i0 := by
    intro g
    rw [Finset.prod_eq_single i0 (fun l _ hl ↦ if_neg hl)
      (fun hc ↦ absurd (Finset.mem_univ i0) hc), if_pos rfl]
  have hrw : ∀ a : ι → Z, (if a i0 = b0 then ∏ i, f i (a i) else 0)
      = ∏ i, ((if i = i0 then (if a i = b0 then (1 : ℝ) else 0) else 1) * f i (a i)) := by
    intro a
    rw [Finset.prod_mul_distrib, hone fun i ↦ if a i = b0 then (1 : ℝ) else 0]
    by_cases hb : a i0 = b0
    · rw [if_pos hb, if_pos hb, one_mul]
    · rw [if_neg hb, if_neg hb, zero_mul]
  rw [Finset.sum_congr rfl fun a _ ↦ hrw a,
    sum_prod_pi fun j c ↦ (if j = i0 then (if c = b0 then (1 : ℝ) else 0) else 1) * f j c]
  have hfac : ∀ j : ι,
      (∑ c, (if j = i0 then (if c = b0 then (1 : ℝ) else 0) else 1) * f j c)
        = if j = i0 then f i0 b0 else 1 := by
    intro j
    by_cases hj : j = i0
    · subst hj
      rw [if_pos rfl]
      have hterm : ∀ c : Z, (if j = j then (if c = b0 then (1 : ℝ) else 0) else 1) * f j c
          = if c = b0 then f j b0 else 0 := by
        intro c
        rw [if_pos rfl]
        by_cases hc : c = b0
        · rw [if_pos hc, if_pos hc, hc, one_mul]
        · rw [if_neg hc, if_neg hc, zero_mul]
      rw [Finset.sum_congr rfl fun c _ ↦ hterm c,
        Finset.sum_ite_eq' Finset.univ b0 fun _ ↦ f j b0, if_pos (Finset.mem_univ b0)]
    · rw [if_neg hj]
      have hterm : ∀ c : Z, (if j = i0 then (if c = b0 then (1 : ℝ) else 0) else 1) * f j c
          = f j c := by
        intro c
        rw [if_neg hj, one_mul]
      rw [Finset.sum_congr rfl fun c _ ↦ hterm c]
      exact hsum j
  rw [Finset.prod_congr rfl fun j _ ↦ hfac j, hone fun _ ↦ f i0 b0]

end ProductSums

section Definitions

/-- **A coadapted joint kernel family.**  Conditional on the complete joint past, each
locus's next-state marginal is the prescribed one-locus kernel applied to its current
state; the loci may have arbitrary joint next-state dependence. -/
def Coadapted (K : ℕ → ι → (ι → Z) → Z → ℝ) (J : List (ι → Z) → (ι → Z) → ℝ) : Prop :=
  ∀ (z : ι → Z) (h : List (ι → Z)),
    (∀ a, 0 ≤ J (z :: h) a) ∧ (∑ a, J (z :: h) a = 1) ∧
      ∀ (i : ι) (b : Z),
        ∑ a ∈ Finset.univ.filter fun a : ι → Z ↦ a i = b, J (z :: h) a = K h.length i z b

/-- **The finite-horizon coupling polytope**, UPT (5.3) and (5.4): nonnegativity, the
prescribed initial law, prefix flow, and the marginal transition constraints. -/
def InPolytope (μ : (ι → Z) → ℝ) (K : ℕ → ι → (ι → Z) → Z → ℝ) (T : ℕ)
    (γ : List (ι → Z) → ℝ) : Prop :=
  (∀ v : List (ι → Z), 1 ≤ v.length → v.length ≤ T + 1 → 0 ≤ γ v) ∧
    (∀ a, γ [a] = μ a) ∧
    (∀ (z : ι → Z) (h : List (ι → Z)), h.length + 1 ≤ T → ∑ a, γ (a :: z :: h) = γ (z :: h)) ∧
    ∀ (z : ι → Z) (h : List (ι → Z)) (i : ι) (b : Z), h.length + 1 ≤ T →
      ∑ a ∈ Finset.univ.filter fun a : ι → Z ↦ a i = b, γ (a :: z :: h)
        = K h.length i z b * γ (z :: h)

end Definitions

section ProductWitness

/-- **The independent product coupling is coadapted**, so the coadaptation hypothesis is not
vacuous. -/
theorem productKernel_coadapted (K : ℕ → ι → (ι → Z) → Z → ℝ)
    (hKnn : ∀ t i z b, 0 ≤ K t i z b) (hKsum : ∀ t i z, ∑ b, K t i z b = 1) :
    Coadapted K (productKernel K) := by
  intro z h
  refine ⟨?_, ?_, ?_⟩
  · intro a
    rw [productKernel_cons]
    exact Finset.prod_nonneg fun i _ ↦ hKnn _ _ _ _
  · rw [Finset.sum_congr rfl fun a _ ↦ productKernel_cons K z h a,
      sum_prod_pi fun i c ↦ K h.length i z c]
    simp [hKsum]
  · intro i b
    rw [Finset.sum_congr rfl fun a _ ↦ productKernel_cons K z h a]
    exact sum_prod_pi_marginal (fun j c ↦ K h.length j z c) (fun j ↦ hKsum _ _ _) i b

/-- **The product coupling is the product sign law of `MarginalTurnoverRegion`** when each
locus carries a two-point alphabet and the prescribed one-locus kernel has mean `mrg i` at
locus `i`.  The independent coupling of the finite-horizon polytope and the independent
sign law of the one-time marginal-turnover region are the same object. -/
theorem productKernel_eq_productSign (m : ℕ) (mrg : Fin m → ℝ) (z : Fin m → Bool)
    (rest : List (Fin m → Bool)) (a : Fin m → Bool) :
    productKernel (fun _ i _ b ↦ (1 + mrg i * TurnoverDependence.sgn b) / 2) (z :: rest) a
      = MarginalTurnoverRegion.productSign m mrg a := rfl

/-- A path law built from a coadapted family is nonnegative.

Assumes: `Coadapted K J`, witnessed by `productKernel_coadapted`. -/
theorem pathLaw_nonneg {μ : (ι → Z) → ℝ} (hμ : ∀ a, 0 ≤ μ a)
    {K : ℕ → ι → (ι → Z) → Z → ℝ} {J : List (ι → Z) → (ι → Z) → ℝ} (hJ : Coadapted K J) :
    ∀ v : List (ι → Z), 0 ≤ pathLaw μ J v
  | [] => by simp
  | [a] => by simpa using hμ a
  | a :: z :: h => by
      rw [pathLaw_cons]
      exact mul_nonneg (pathLaw_nonneg hμ hJ (z :: h)) ((hJ z h).1 a)

end ProductWitness

section BothInclusions

/-- **UPT Theorem 5.3, first inclusion.**  Every coadapted path law satisfies prefix flow
and the marginal transition constraints.

Assumes: `Coadapted K J`, witnessed by `productKernel_coadapted`. -/
theorem pathLaw_inPolytope {μ : (ι → Z) → ℝ} (hμ : ∀ a, 0 ≤ μ a)
    {K : ℕ → ι → (ι → Z) → Z → ℝ} {J : List (ι → Z) → (ι → Z) → ℝ} (hJ : Coadapted K J)
    (T : ℕ) : InPolytope μ K T (pathLaw μ J) := by
  refine ⟨fun v _ _ ↦ pathLaw_nonneg hμ hJ v, fun a ↦ rfl, ?_, ?_⟩
  · intro z h _
    rw [Finset.sum_congr rfl fun a _ ↦ pathLaw_cons μ J a z h, ← Finset.mul_sum,
      (hJ z h).2.1, mul_one]
  · intro z h i b _
    rw [Finset.sum_congr rfl fun a _ ↦ pathLaw_cons μ J a z h, ← Finset.mul_sum,
      (hJ z h).2.2 i b, mul_comm]

/-- **The conditional kernel of a feasible mass vector is coadapted.**

Assumes: `InPolytope μ K T γ`, witnessed by `productKernel_pathLaw_inPolytope`. -/
theorem condKernel_coadapted {μ : (ι → Z) → ℝ} {K : ℕ → ι → (ι → Z) → Z → ℝ} {T : ℕ}
    {γ : List (ι → Z) → ℝ} (hpoly : InPolytope μ K T γ) (hKnn : ∀ t i z b, 0 ≤ K t i z b)
    (hKsum : ∀ t i z, ∑ b, K t i z b = 1) : Coadapted K (condKernel K T γ) := by
  intro z h
  by_cases hcase : h.length + 1 ≤ T ∧ γ (z :: h) ≠ 0
  · have hlenz : (z :: h).length ≤ T + 1 := by
      simp only [List.length_cons]
      omega
    have hlena : ∀ a : ι → Z, (a :: z :: h).length ≤ T + 1 := by
      intro a
      simp only [List.length_cons]
      omega
    have hpos : 0 < γ (z :: h) :=
      lt_of_le_of_ne (hpoly.1 _ (by simp) hlenz) (Ne.symm hcase.2)
    have hval : ∀ a : ι → Z, condKernel K T γ (z :: h) a = γ (a :: z :: h) / γ (z :: h) :=
      fun a ↦ condKernel_cons_pos K T γ z h a hcase
    refine ⟨?_, ?_, ?_⟩
    · intro a
      rw [hval a]
      exact div_nonneg (hpoly.1 _ (by simp) (hlena a)) hpos.le
    · rw [Finset.sum_congr rfl fun a _ ↦ hval a, ← Finset.sum_div,
        hpoly.2.2.1 z h hcase.1, div_self hcase.2]
    · intro i b
      rw [Finset.sum_congr rfl fun a _ ↦ hval a, ← Finset.sum_div,
        hpoly.2.2.2 z h i b hcase.1, mul_div_assoc, div_self hcase.2, mul_one]
  · have hval : ∀ a : ι → Z, condKernel K T γ (z :: h) a = productKernel K (z :: h) a :=
      fun a ↦ condKernel_cons_neg K T γ z h a hcase
    obtain ⟨hp1, hp2, hp3⟩ := productKernel_coadapted K hKnn hKsum z h
    refine ⟨fun a ↦ by rw [hval a]; exact hp1 a, ?_, ?_⟩
    · rw [Finset.sum_congr rfl fun a _ ↦ hval a]
      exact hp2
    · intro i b
      rw [Finset.sum_congr rfl fun a _ ↦ hval a]
      exact hp3 i b

/-- **UPT Theorem 5.3, second inclusion.**  Every feasible history-mass vector is reproduced
up to the horizon by the path law of its own conditional kernel.

Assumes: `InPolytope μ K T γ`, witnessed by `productKernel_pathLaw_inPolytope`. -/
theorem polytope_eq_pathLaw {μ : (ι → Z) → ℝ} {K : ℕ → ι → (ι → Z) → Z → ℝ} {T : ℕ}
    {γ : List (ι → Z) → ℝ} (hpoly : InPolytope μ K T γ) :
    ∀ v : List (ι → Z), 1 ≤ v.length → v.length ≤ T + 1 →
      γ v = pathLaw μ (condKernel K T γ) v
  | [], hcon, _ => absurd hcon (by simp)
  | [a], _, _ => by simpa using hpoly.2.1 a
  | a :: z :: h, _, hlen => by
      have hlen' : h.length + 1 ≤ T := by
        simp only [List.length_cons] at hlen
        omega
      have hprev : γ (z :: h) = pathLaw μ (condKernel K T γ) (z :: h) := by
        refine polytope_eq_pathLaw hpoly (z :: h) (by simp) ?_
        simp only [List.length_cons]
        omega
      rw [pathLaw_cons, ← hprev]
      by_cases hz : γ (z :: h) = 0
      · have hsum := hpoly.2.2.1 z h hlen'
        rw [hz] at hsum
        have hnn : ∀ a' ∈ (Finset.univ : Finset (ι → Z)), 0 ≤ γ (a' :: z :: h) := by
          intro a' _
          refine hpoly.1 _ (by simp) ?_
          simp only [List.length_cons]
          omega
        have hall := (Finset.sum_eq_zero_iff_of_nonneg hnn).mp hsum a (Finset.mem_univ a)
        rw [hall, hz, zero_mul]
      · rw [condKernel_cons_pos K T γ z h a ⟨hlen', hz⟩]
        field_simp

/-- **UPT Theorem 5.3.**  The coadapted path laws up to a finite horizon are exactly the
solutions of the coupling polytope. -/
theorem coadapted_iff_inPolytope {μ : (ι → Z) → ℝ} (hμ : ∀ a, 0 ≤ μ a)
    {K : ℕ → ι → (ι → Z) → Z → ℝ} (hKnn : ∀ t i z b, 0 ≤ K t i z b)
    (hKsum : ∀ t i z, ∑ b, K t i z b = 1) (T : ℕ) (γ : List (ι → Z) → ℝ) :
    (∃ J, Coadapted K J ∧ ∀ v : List (ι → Z), 1 ≤ v.length → v.length ≤ T + 1 →
        γ v = pathLaw μ J v)
      ↔ InPolytope μ K T γ := by
  constructor
  · rintro ⟨J, hJ, hagree⟩
    obtain ⟨-, hinit, hflow, hmarg⟩ := pathLaw_inPolytope hμ hJ T
    refine ⟨?_, ?_, ?_, ?_⟩
    · intro v h1 h2
      rw [hagree v h1 h2]
      exact pathLaw_nonneg hμ hJ v
    · intro a
      rw [hagree [a] (by simp) (by simp)]
      exact hinit a
    · intro z h hlen
      have hext : ∀ a : ι → Z, γ (a :: z :: h) = pathLaw μ J (a :: z :: h) := by
        intro a
        refine hagree _ (by simp) ?_
        simp only [List.length_cons]
        omega
      rw [Finset.sum_congr rfl fun a _ ↦ hext a, hflow z h hlen]
      refine (hagree (z :: h) (by simp) ?_).symm
      simp only [List.length_cons]
      omega
    · intro z h i b hlen
      have hext : ∀ a : ι → Z, γ (a :: z :: h) = pathLaw μ J (a :: z :: h) := by
        intro a
        refine hagree _ (by simp) ?_
        simp only [List.length_cons]
        omega
      rw [Finset.sum_congr rfl fun a _ ↦ hext a, hmarg z h i b hlen]
      congr 1
      refine (hagree (z :: h) (by simp) ?_).symm
      simp only [List.length_cons]
      omega
  · intro hpoly
    exact ⟨condKernel K T γ, condKernel_coadapted hpoly hKnn hKsum,
      polytope_eq_pathLaw hpoly⟩

/-- **The polytope is nonempty** whenever the one-locus kernels are probability laws. -/
theorem productKernel_pathLaw_inPolytope {μ : (ι → Z) → ℝ} (hμ : ∀ a, 0 ≤ μ a)
    (K : ℕ → ι → (ι → Z) → Z → ℝ) (hKnn : ∀ t i z b, 0 ≤ K t i z b)
    (hKsum : ∀ t i z, ∑ b, K t i z b = 1) (T : ℕ) :
    InPolytope μ K T (pathLaw μ (productKernel K)) :=
  pathLaw_inPolytope hμ (productKernel_coadapted K hKnn hKsum) T

end BothInclusions

section MixturesAndReports

/-- **The polytope is convex.**  A mixture of two feasible history-mass vectors is feasible,
so mixtures of coadapted couplings are coadapted-realisable.

Assumes: `InPolytope μ K T`, witnessed by `productKernel_pathLaw_inPolytope`. -/
theorem inPolytope_mixture {μ : (ι → Z) → ℝ} {K : ℕ → ι → (ι → Z) → Z → ℝ} {T : ℕ}
    {γ₁ γ₂ : List (ι → Z) → ℝ} (h₁ : InPolytope μ K T γ₁) (h₂ : InPolytope μ K T γ₂)
    {θ : ℝ} (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1) :
    InPolytope μ K T fun v ↦ θ * γ₁ v + (1 - θ) * γ₂ v := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro v h1 h2
    exact add_nonneg (mul_nonneg hθ0 (h₁.1 v h1 h2)) (mul_nonneg (by linarith) (h₂.1 v h1 h2))
  · intro a
    show θ * γ₁ [a] + (1 - θ) * γ₂ [a] = μ a
    rw [h₁.2.1 a, h₂.2.1 a]
    ring
  · intro z h hlen
    have hrw : ∀ a : ι → Z, θ * γ₁ (a :: z :: h) + (1 - θ) * γ₂ (a :: z :: h)
        = θ * γ₁ (a :: z :: h) + (1 - θ) * γ₂ (a :: z :: h) := fun _ ↦ rfl
    show ∑ a, (θ * γ₁ (a :: z :: h) + (1 - θ) * γ₂ (a :: z :: h))
      = θ * γ₁ (z :: h) + (1 - θ) * γ₂ (z :: h)
    rw [Finset.sum_congr rfl fun a _ ↦ hrw a, Finset.sum_add_distrib, ← Finset.mul_sum,
      ← Finset.mul_sum, h₁.2.2.1 z h hlen, h₂.2.2.1 z h hlen]
  · intro z h i b hlen
    show ∑ a ∈ Finset.univ.filter fun a : ι → Z ↦ a i = b,
        (θ * γ₁ (a :: z :: h) + (1 - θ) * γ₂ (a :: z :: h))
      = K h.length i z b * (θ * γ₁ (z :: h) + (1 - θ) * γ₂ (z :: h))
    rw [Finset.sum_add_distrib, ← Finset.mul_sum, ← Finset.mul_sum,
      h₁.2.2.2 z h i b hlen, h₂.2.2.2 z h i b hlen]
    ring

/-- **Every intermediate expected path report is attained.**  For any finite collection of
paths and any report on them, the values taken on the polytope between two feasible values
are all attained by feasible history-mass vectors.

Assumes: `InPolytope μ K T`, witnessed by `productKernel_pathLaw_inPolytope`. -/
theorem inPolytope_report_intermediate {μ : (ι → Z) → ℝ} {K : ℕ → ι → (ι → Z) → Z → ℝ}
    {T : ℕ} {γ₁ γ₂ : List (ι → Z) → ℝ} (h₁ : InPolytope μ K T γ₁)
    (h₂ : InPolytope μ K T γ₂) (paths : Finset (List (ι → Z))) (F : List (ι → Z) → ℝ)
    (y : ℝ) (hy1 : ∑ v ∈ paths, γ₁ v * F v ≤ y) (hy2 : y ≤ ∑ v ∈ paths, γ₂ v * F v) :
    ∃ γ, InPolytope μ K T γ ∧ ∑ v ∈ paths, γ v * F v = y := by
  set c₁ := ∑ v ∈ paths, γ₁ v * F v with hc₁
  set c₂ := ∑ v ∈ paths, γ₂ v * F v with hc₂
  have hmix : ∀ θ : ℝ, ∑ v ∈ paths, (θ * γ₁ v + (1 - θ) * γ₂ v) * F v
      = θ * c₁ + (1 - θ) * c₂ := by
    intro θ
    have hrw : ∀ v : List (ι → Z), (θ * γ₁ v + (1 - θ) * γ₂ v) * F v
        = θ * (γ₁ v * F v) + (1 - θ) * (γ₂ v * F v) := fun v ↦ by ring
    rw [Finset.sum_congr rfl fun v _ ↦ hrw v, Finset.sum_add_distrib, ← Finset.mul_sum,
      ← Finset.mul_sum, hc₁, hc₂]
  by_cases hdeg : c₁ = c₂
  · refine ⟨γ₁, h₁, ?_⟩
    rw [← hc₁]
    rw [hdeg] at hy1
    linarith
  · have hlt : c₁ < c₂ := lt_of_le_of_ne (le_trans hy1 hy2) hdeg
    have hden : (0 : ℝ) < c₂ - c₁ := by linarith
    refine ⟨fun v ↦ (c₂ - y) / (c₂ - c₁) * γ₁ v + (1 - (c₂ - y) / (c₂ - c₁)) * γ₂ v,
      inPolytope_mixture h₁ h₂ (div_nonneg (by linarith) hden.le) ?_, ?_⟩
    · rw [div_le_one hden]
      linarith
    · rw [hmix]
      field_simp
      ring

end MixturesAndReports

end

end Descent.Portability.TurnoverCouplingPolytope
