/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Portability.AncestryCalibration
import Descent.Portability.AncientPrediction
import Descent.Portability.AncestrySpecificPower
import Descent.Portability.BayesianPGSTheory
import Descent.Portability.ClinicalUtilityFairness
import Descent.Portability.ContinuumCalibration
import Descent.Portability.ContinuumCalibrationProgram
import Descent.Portability.CorrectionBiology
import Descent.Portability.CorrectionWidths
import Descent.Portability.DemographyAccuracyFiber
import Descent.Portability.DiscriminationLaw
import Descent.Portability.EmpiricalAUCComparison
import Descent.Portability.EquityAndImplementation
import Descent.Portability.ExactFiniteHistoryLaw
import Descent.Portability.ExactMetricEvaluation
import Descent.Portability.EndToEndScoreLaw
import Descent.Portability.FiniteDemographicSampling
import Descent.Portability.GenerativePortabilityLaw
import Descent.Portability.HorizonCurve
import Descent.Portability.HumanDemography
import Descent.Portability.ImputationPortability
import Descent.Portability.LongitudinalPortability
import Descent.Portability.MeasurePortabilityLaw
import Descent.Portability.MechanisticPortabilityWitnesses
import Descent.Portability.MetricSpecificPortability
import Descent.Portability.MetricSpecificPortability.ARoneFrontier
import Descent.Portability.MetricSpecificPortability.CalibrationVsDiscrimination
import Descent.Portability.MetricSpecificPortability.GeneticFrontier
import Descent.Portability.MetricSpecificPortability.MetricAndClinicalDecisions
import Descent.Portability.MetricSpecificPortability.PrecisionRecall
import Descent.Portability.MetricSpecificPortability.R2Decomposition
import Descent.Portability.MetricSpecificPortability.SharedCorrectionFamily
import Descent.Portability.MomentAUCNonidentifiability
import Descent.Portability.MultiAncestryTheory
import Descent.Portability.PartialMetricMixture
import Descent.Portability.PCCorrectability
import Descent.Portability.PCCorrectability.Core
import Descent.Portability.PCCorrectability.DemographicCapacity
import Descent.Portability.PCCorrectability.Design
import Descent.Portability.PCCorrectability.Diagnostic
import Descent.Portability.PCCorrectability.EndToEnd
import Descent.Portability.PCCorrectability.Frequency
import Descent.Portability.PCCorrectability.Geometry
import Descent.Portability.PCCorrectability.ImitationCapacity
import Descent.Portability.PCCorrectability.Nonidentifiability
import Descent.Portability.PCCorrectability.Overlap
import Descent.Portability.PCCorrectability.Phase
import Descent.Portability.PCCorrectability.Threshold
import Descent.Portability.PGSCalibrationTheory
import Descent.Portability.PGSCalibrationTheory.CalibrationDefinitions
import Descent.Portability.PGSCalibrationTheory.CalibrationVsDiscrimination
import Descent.Portability.PGSCalibrationTheory.DecisionImplications
import Descent.Portability.PGSCalibrationTheory.PopulationCalibrationDrift
import Descent.Portability.PGSCalibrationTheory.RecalibrationMethods
import Descent.Portability.PhenomeWidePortability
import Descent.Portability.PolygenicContinuumCalibration
import Descent.Portability.PopulationAUC
import Descent.Portability.PortabilityBounds
import Descent.Portability.PortabilityDrift
import Descent.Portability.PortabilityDrift.ClosedPopulationRegime
import Descent.Portability.PortabilityDrift.Definitions
import Descent.Portability.PortabilityDrift.Generational
import Descent.Portability.PortabilityDrift.MigrationDrift
import Descent.Portability.PortabilityDrift.MigrationDriftRecurrence
import Descent.Portability.PortabilityDrift.MutationDrift
import Descent.Portability.PortabilityDrift.NonreversibleFlow
import Descent.Portability.PortabilityDrift.PresentDayMetrics
import Descent.Portability.PortabilityDrift.PresentDayMoments
import Descent.Portability.PortabilityMasterTheorem
import Descent.Portability.RareVariantPortability
import Descent.Portability.SampleOverlapBias
import Descent.Portability.ScoreDistribution
import Descent.Portability.StatisticalGeneticsMethodology
import Descent.Portability.StratificationConfounding
import Descent.Portability.TransferLearningPGS
import Descent.Portability.TransferLearningPGS.FeatureRepresentation
import Descent.Portability.TransferLearningPGS.FineTuning
import Descent.Portability.TransferLearningPGS.ImportanceWeighting
import Descent.Portability.TransferLearningPGS.PGSPortabilityDerivation
import Descent.Portability.TransplantationStability
import Descent.Portability.UniversalMetricIdentification

import Descent.Portability.ProbitTrainingLaw
import Descent.Portability.ScoreMomentLaw
import Descent.Portability.TrainingNoiseAccuracy
import Descent.Portability.AncestralEventLaw
import Descent.Portability.AncestralEpochLaw
import Descent.Portability.MarkedAncestralLaw
import Descent.Portability.TimedAncestralLaw
import Descent.Portability.NucleotideMutationLaw
import Descent.Portability.AncestralBranchExposure
import Descent.Portability.GenealogyGenotypeLaw
import Descent.Portability.OrderedMutationCatalogue
import Descent.Portability.SimulationAccuracy
import Descent.Portability.AncestralAbsorptionLaw
import Descent.Portability.OrderedCladeLaw
import Descent.Portability.AncestralGenealogyLaw
import Descent.Portability.AncestralCladePartition
import Descent.Portability.AncestralGenealogyOrdering
import Descent.Portability.StoppedAncestralTiming
import Descent.Portability.CalibrationLaw
import Descent.Portability.InterleavedMutationLaw
import Descent.Portability.InterleavedMutationMeasurability
import Descent.Portability.GaussianEffectPortabilityLaw
import Descent.Portability.AncestralMutationTransfer
import Descent.Portability.AncestralMutationAbsorption
import Descent.Portability.StoppedGenotypeLaw
import Descent.Portability.StoppedGenotypeReadiness
import Descent.Portability.AncestralMutationLimit
import Descent.Portability.DistanceBinnedPortabilityLaw
import Descent.Portability.ReservoirSamplingLaw
import Descent.Portability.AncestralEpochGenotypeLaw
import Descent.Portability.AncestralMutationResolvent
import Descent.Portability.SamplingDesignLaw
import Descent.Portability.SourceDesignLaw
import Descent.Portability.PortabilityRatioGeometry
import Descent.Portability.InterleavedMutationExponential
import Descent.Portability.SimulationDemographyLaw
import Descent.Portability.ChunkedGenotypeLaw
import Descent.Portability.ExponentialPoissonRace
import Descent.Portability.RatioPoleLaw
import Descent.Portability.WholeGenomeMutationSemigroup
import Descent.Portability.FiniteProductExponential
import Descent.Portability.WholeGenomeMutationRace
import Descent.Portability.StoppedGenotypeRenewal
import Descent.Portability.SignedTransferIdentification
import Descent.Portability.GaussianSlabLaw
import Descent.Portability.RatioSourceDegeneracy
import Descent.Portability.PThresholdTrainingLaw
import Descent.Portability.FirthFiniteIterationLaw
import Descent.Portability.SimulationBaselineLaw
import Descent.Portability.SimulationCohortLaw
import Descent.Portability.SimulationDesignDecoder
import Descent.Portability.AncestralEpochGenotypeSupport
import Descent.Portability.MutationChannelBridge
import Descent.Portability.GaussianInverseQuadratic
import Descent.Portability.AcceptedBinIntegrability
import Descent.Portability.ExactMemoryLaw
import Descent.Portability.FiniteNumericalCertificate
import Descent.Portability.ConditionalErrorCertificate
import Descent.Portability.FiniteMetricIdentification
import Descent.Portability.ReportConditionalRiskLaw
import Descent.Portability.ObservableClosureLaw
import Descent.Portability.GuardedMetricOptimization
import Descent.Portability.OptimalMeasurementAllocation
import Descent.Portability.TargetUncertainty
import Descent.Portability.AdaptiveLinearMeasurements
import Descent.Portability.EllipsoidTargetRadius
import Descent.Portability.FiniteTargetSpectrum
import Descent.Portability.ReportFiniteCalibrationLaw
import Descent.Portability.ReportCalibrationTransport
import Descent.Portability.MinimalObservableLaw
import Descent.Portability.LowMomentObstruction
import Descent.Portability.DiploidEffectLaw
import Descent.Portability.DiploidBernsteinLaw
import Descent.Portability.EvolutionaryObservability
import Descent.Portability.DiscountedObservability
import Descent.Portability.DynamicBlindness
import Descent.Portability.HWEInteractionLaw
import Descent.Portability.CombinedPredictionCertificate
import Descent.Portability.FiniteIndependentMoments
import Descent.Portability.BalancedHWEInteraction
import Descent.Portability.DiploidEffectFieldLaw
import Descent.Portability.QuadraticRigidityLaw
import Descent.Portability.GaussianCovarianceSeparation
import Descent.Portability.BalancedHWECounterexample
import Descent.Portability.ControlledCoarseGraining
import Descent.Portability.MatrixOperatorBridge
import Descent.Portability.MarkovPoissonLaw
import Descent.Portability.MarkovCoarseGraining
import Descent.Portability.BanachEulerExponential
import Descent.Portability.OneLocusCompatibilityLaw
import Descent.Portability.ConditionalSeparatorLaw
import Descent.Portability.GaussianPanelLaw
import Descent.Portability.ContinuousMemoryLaw
import Descent.Portability.GaussianPolynomialMoments
import Descent.Portability.IndependentShiftOperator
import Descent.Portability.BalancedHWEOperatorLimit
import Descent.Portability.BalancedHWEWeakLimit
import Descent.Portability.RareEventInformationLaw
import Descent.Portability.GaussianHermiteLaw
import Descent.Portability.ObservationAsymptotics
import Descent.Portability.ContinuousObservabilityGramian
import Descent.Portability.MarkovSeparatorLaw
import Descent.Portability.BalancedHWEVanishingLaw
import Descent.Portability.ThreeLocusInformation
import Descent.Portability.GaussianEvenMoments
import Descent.Portability.GraphColoringLaw
import Descent.Portability.BalancedHWEJumpOperator
import Descent.Portability.BalancedHWEFiniteIntensity
import Descent.Portability.BalancedHWECompoundPoisson
import Descent.Portability.FiniteHorizonLoss
import Descent.Portability.ExponentialRemainder
import Descent.Portability.NonreversibleLossExpansion
import Descent.Portability.CrossCoordinateRigidityLaw
import Descent.Portability.FiniteCovarianceMoments

import Descent.Portability.GaussianInvariantMoments
import Descent.Portability.NonreversibleResolvent
import Descent.Portability.StationaryPoissonLaw
import Descent.Portability.TensorInterpolationLaw
import Descent.Portability.RealVaryingEuler
import Descent.Portability.BalancedHWEGaussianCharacteristic

assert_below Descent.Program

/-!
# `Descent.Portability` -- the layer head

**Every module under `Descent/Portability/`, and nothing else.**

The root file used to import 171 modules directly, with a comment explaining that orphan
modules get named there "rather than left to be picked up by whoever remembers to name
them".  That comment was right about the hazard -- `ResonanceSpectrum` failed all day on a
missing import while every whole-corpus build reported zero errors, because no target ever
named it -- and wrong about the remedy: a list somebody maintains by hand has the same
failure mode as no list, one memory lapse later.

A layer head does not need remembering.  `validation/code/check.py --only heads` reads the
directory and fails if a file in it is missing here, so a new module is either imported or
the build says which one is not.  The root then names eleven heads instead of 171 modules,
and its import list stops being a place where coverage can quietly lapse.

This file contains no declarations.  It is a table of contents, and a table of contents
that states a theorem is a module pretending to be a table of contents.
-/
