/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Descent.Pangenome.AncestralLocality.CylinderSamplingAlgebra
import Mathlib.MeasureTheory.Integral.Pi

assert_below Descent.PopGen Descent.Spectral Descent.Blindness Descent.Conditionals
assert_below Descent.Portability Descent.Decision Descent.Program

/-!
# Sampling polynomials of several genomes

Theorem 9 of the ancestral-locality note rests on the density of the cylinder sampling
polynomials `H_f(p) = ∫ f(x_1, …, x_n) p(dx_1) … p(dx_n)` in `C(P(H))` for the genome states
`H = {0,1}^V` of a countable genome `V`. `CylinderSamplingAlgebra` proves the density for the
algebra generated by the linear sampling observables; this module shows that every sampling
polynomial of `n` genomes belongs to that algebra and is the integral against `n` independent
genomes.

`patternIndicator features pattern` is the indicator readout of one letter pattern on finitely
many features. `samplingPolynomial n features readout` combines, over the letter patterns of the
`n` genomes, the value of the readout with the product of the linear sampling observables of the
pattern's letters. It lies in the algebra (`samplingPolynomial_mem_samplingAlgebra`), every
readout is that combination of its values (`readout_eq_sum_patterns`), and the polynomial at a
genome law `p` is the integral of the readout against the `n`-fold product law
(`samplingPolynomial_apply`).

Scope. Every sampling polynomial lies in the generated algebra; that every member of the algebra
is a single sampling polynomial is not formalized.

## Empirical status

None. The bodies here are algebra and measure theory: finite combinations of cylinder integrals
and the product formula for integrals against product measures, so no measurement can bear on
them.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Descent.Pangenome.AncestralLocality.CylinderSamplingPolynomials

open MeasureTheory Topology CylinderSamplingAlgebra

noncomputable section

variable {V : Type*} [Countable V] [DecidableEq V]

omit [Countable V] [DecidableEq V] in
/-- The indicator readout of one letter pattern on a finite set of features. -/
def patternIndicator (features : Finset V) (pattern : features → Bool) :
    (features → Bool) → ℝ :=
  fun letters ↦ if letters = pattern then 1 else 0

/-- **The cylinder sampling polynomial** of a readout of `n` genomes through finitely many
features: over the letter patterns of the `n` genomes, the readout at the pattern times the
product of the linear sampling observables of the pattern's letters. -/
def samplingPolynomial (n : ℕ) (features : Finset V)
    (readout : (Fin n → features → Bool) → ℝ) : C(ProbabilityMeasure (V → Bool), ℝ) :=
  ∑ patterns : Fin n → features → Bool,
    readout patterns • ∏ k, samplingMonomial features (patternIndicator features (patterns k))

/-- Every cylinder sampling polynomial lies in the sampling algebra. -/
theorem samplingPolynomial_mem_samplingAlgebra (n : ℕ) (features : Finset V)
    (readout : (Fin n → features → Bool) → ℝ) :
    samplingPolynomial n features readout ∈ samplingAlgebra V :=
  sum_mem fun _ _ ↦ SMulMemClass.smul_mem _
    (prod_mem fun _ _ ↦ samplingMonomial_mem_samplingAlgebra features _)

omit [Countable V] in
/-- A readout of `n` genomes is the combination of its values with the pattern indicators of the
letters it reads. -/
theorem readout_eq_sum_patterns (n : ℕ) (features : Finset V)
    (readout : (Fin n → features → Bool) → ℝ) (letters : Fin n → features → Bool) :
    readout letters = ∑ patterns : Fin n → features → Bool,
      readout patterns * ∏ k, patternIndicator features (patterns k) (letters k) := by
  have hproduct : ∀ patterns : Fin n → features → Bool,
      ∏ k, patternIndicator features (patterns k) (letters k) =
        if letters = patterns then 1 else 0 := by
    intro patterns
    by_cases hequal : letters = patterns
    · subst hequal
      simp [patternIndicator]
    · rw [if_neg hequal]
      obtain ⟨k, hk⟩ : ∃ k, letters k ≠ patterns k := by
        by_contra hnone
        push_neg at hnone
        exact hequal (funext hnone)
      exact Finset.prod_eq_zero (Finset.mem_univ k) (by simp [patternIndicator, hk])
  simp only [hproduct, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq, Finset.mem_univ, if_true]

/-- Reading the letters of one genome at finitely many features is continuous. -/
theorem continuous_patternIndicator_restrict (n : ℕ) (features : Finset V)
    (pattern : features → Bool) (k : Fin n) :
    Continuous fun genomes : Fin n → V → Bool ↦
      patternIndicator features pattern (features.restrict (genomes k)) := by
  have hrestrict : Continuous fun genomes : Fin n → V → Bool ↦ features.restrict (genomes k) :=
    continuous_pi fun v ↦ continuous_apply_apply k (v : V)
  have hletter : Continuous (patternIndicator features pattern) := continuous_of_discreteTopology
  exact hletter.comp hrestrict

/-- **A sampling polynomial is the expectation of its readout over `n` independent genomes.** Its
value at a genome law `p` is `∫ f(x_1, …, x_n) p(dx_1) … p(dx_n)`. -/
theorem samplingPolynomial_apply (n : ℕ) (features : Finset V)
    (readout : (Fin n → features → Bool) → ℝ) (μ : ProbabilityMeasure (V → Bool)) :
    samplingPolynomial n features readout μ =
      ∫ genomes, readout (fun k ↦ features.restrict (genomes k))
        ∂(Measure.pi fun _ : Fin n ↦ (μ : Measure (V → Bool))) := by
  have hcontinuous : ∀ patterns : Fin n → features → Bool,
      Continuous fun genomes : Fin n → V → Bool ↦ readout patterns *
        ∏ k, patternIndicator features (patterns k) (features.restrict (genomes k)) :=
    fun patterns ↦ continuous_const.mul (continuous_finset_prod _ fun k _ ↦
      continuous_patternIndicator_restrict n features (patterns k) k)
  have hexpand : (fun genomes : Fin n → V → Bool ↦
      readout (fun k ↦ features.restrict (genomes k))) =
        fun genomes ↦ ∑ patterns : Fin n → features → Bool, readout patterns *
          ∏ k, patternIndicator features (patterns k) (features.restrict (genomes k)) :=
    funext fun genomes ↦ readout_eq_sum_patterns n features readout _
  rw [hexpand, integral_finset_sum _ fun patterns _ ↦
    (hcontinuous patterns).integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)]
  simp only [samplingPolynomial, ContinuousMap.sum_apply, ContinuousMap.smul_apply,
    ContinuousMap.prod_apply, smul_eq_mul]
  refine Finset.sum_congr rfl fun patterns _ ↦ ?_
  rw [integral_const_mul, integral_fintype_prod_eq_prod fun k (genome : V → Bool) ↦
    patternIndicator features (patterns k) (features.restrict genome)]
  rfl

end

end Descent.Pangenome.AncestralLocality.CylinderSamplingPolynomials
